### ISSUE TITLE
data_structures.py is quite large

### ISSUE THREAD

**Issue by stefankoegl** [SoCo/SoCo#148]
``data_structures.py`` is becoming quite large, and I've been thinking about how to split it up.

I'd propose the following

Module ``soco.data_structures``
* ``MusicInfoItem``
* ``QueueItem``
* ``URI`` (from #147)

Module ``soco.data_structures.musiclib``
* ``MusicLibraryItem``
* ``ML``* classes

Module ``soco.data_structures.services``
* MusicServiceItem
* ``MS``* classes

What do you think?

**Comment by KennethNielsen** [comment]
@stefankoegl I believe this is no longer an issue after @lawrenceakka's rewrite. The module is below 1k lines and only contains core DIDL data structures. Please re-open if you think it is still relevant.
