### ISSUE TITLE
Spotify plugin metadata issue

### ISSUE THREAD

**Issue by nicerworld** [SoCo/SoCo#210]
When I do a play_uri I do not get metadata in controller apps. I printed the response of get_current_track_info to get the DIDL to pass into play_uri meta field as below but to no avail. I tried with an MP3 and I can overwrite the MP3 meta with the passed in meta and the overwritten is displayed on controller so I know that passing in meta is normally working but not on Spotify plugin. 

Ideas?

zone.play_uri(uri=u'x-sonos-spotify:spotify%3atrack%3a1Lx5Dxj8H6l6EJrbxwLgAn?sid=9&flags=32', meta=u'<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="-1" parentID="-1" restricted="true"><res protocolInfo="sonos.com-spotify:*:audio/x-spotify:*" duration="0:03:17">x-sonos-spotify:spotify%3atrack%3a1Lx5Dxj8H6l6EJrbxwLgAn?sid=9&amp;flags=32</res><r:streamContent>/r:streamContentupnp:albumArtURI/getaa?s=1&amp;u=x-sonos-spotify%3aspotify%253atrack%253a1Lx5Dxj8H6l6EJrbxwLgAn%3fsid%3d9%26flags%3d32/upnp:albumArtURIdc:titleSugarcane/dc:titleupnp:classobject.item.audioItem.musicTrack/upnp:classdc:creatorMissy Higgins/dc:creatorupnp:albumOn A Clear Night [Australian Version]/upnp:album</item></DIDL-Lite>')

**Comment by KennethNielsen** [comment]
The spotify plugin has been deprecated, see #423 for details. Closing this now as no longer valid.
