### ISSUE TITLE
Function to set metadata for current track

### ISSUE THREAD

**Issue by nicerworld** [SoCo/SoCo#213]
It would be great to have a feature to be able to set the metadata associated with a track that is visible in the controller screens. This would be useful to get over the Spotify/ Tunein radio plugin metadata bug as could store the metadata retrieved from get_current_track and then set it again if I do play_uri or add_to_queue on a Spotify track.

The metadata would only be relevant to the current track and would be automatically set for subsequent tracks or in case of radio, it would be updated by radio plugin. 

Thanks

Rich

**Comment by ghcs27** [comment]
I'm not sure I understand what the proposal is here and I think the problem it tries to solve has already been resolved. If I'm mistaken, please reopen.
