### ISSUE TITLE
Music service tracks from .browse() are treated as MLTrack instead of MSTrack

### ISSUE THREAD

**Issue by Legoben** [SoCo/SoCo#234]
``` python
list = player.get_sonos_playlists()[0] #Songs from music services
tracks = player.browse(list)
```

The items in tracks are the `MLTrack` class and every one of their `item_id`s are `None`. This makes it so they can't be added to Queue (error), and you have to resort to using the URIs

**Comment by ghcs27** [comment]
This seeems to work now.
