### ISSUE TITLE
Release notes 0.11

### ISSUE THREAD

**Issue by stefankoegl** [SoCo/SoCo#261]
Please add your release note items for 0.11 here

**Comment by lawrenceakka** [comment]
#269 and #271 

* Bugfixes for discovery code

**Comment by lawrenceakka** [comment]
#256:  

* A fairly extensive re-organisation of the DIDL metadata handling code, which brings SoCo more into line with the DIDL-Lite spec, as adopted by Sonos. DIDL objects can have now have multiple URIs, and the interface is much simpler. 

Deprecation Note: The exception `DidlCannotCreateMetadata` has been deprecated. Use `DidlMetadataError` instead.

**Comment by lawrenceakka** [comment]
#273:

- Old code which has been deprecated for more than three releases has been removed

- discover is now in its own module, discovery.py.  Note that `from soco import discover` will work just as it did before.

- logging has been improved (clarified a few messages, removed pointless ones etc)

- Event objects now have a timestamp field

**Comment by KennethNielsen** [comment]
#307 An example has been added that shows how to play local files by settings up a temporary HTTP server in python

**Comment by stefankoegl** [comment]
I have now created the proposed release notes in #311. Please make any further comments or corrections there.
