### ISSUE TITLE
program codes

### ISSUE THREAD

**Issue by nicklasriedel** [SoCo/SoCo#268]
hi all.

sorry if i ask stupid but I am in doubt, whether rested program I need to and send the codes from ?? it is from telnet to the Sonos or how I do it. when I need to send the codes / commands ???

hope you will help.

**Comment by lawrenceakka** [comment]
@nicklasriedel 

Is this what you wanted to know? If not, please re-open this bug.

Lawrence

**Comment by nicklasriedel** [comment]
Hi David

Thank you bother to respond

sorry if I ask a little silly but I am not so well known in these codes. but I can open a browser directly and test a command eg http: //192.168.10/Pause or in the style ??

Med venlig hilsen - Kind Regards

Nicklas Riedel
Serviceteknikker
Sikkerhed–service Glostrup
[cid:_1_0A1758A80A17563C003E5782C1257BC9]


Lindpro A/S
Fabriksparken 58, DK-2600 Glostrup


Dir.: +45 40 90 71 11
Mail: niri@lindpro.dk<mailto:niri@lindpro.dk> / Web: www.lindpro.dk
Velkommen til Lindpro
Lindpro er mere end en traditionel el-installatørvirksomhed. Vi kan vores håndværk, og vi ved, hvordan vi omsætter erfaring og viden til værdiskabende løsninger for vores kunder.  Scan QR-koden - og oplev vores engagerede og kompetente medarbejdere. <http://www.youtube.com/watch?v=z7eUjUNm3qM>
[cid:image001.gif@01CE99D4.F2BD93F0]

Fra: David [mailto:notifications@github.com]
Sendt: 30. december 2014 11:20
Til: SoCo/SoCo
Cc: Nicklas Riedel
Emne: Re: [SoCo] program codes (#268)


Hi, if I understand your question you are asking how the commands get sent to Sonos.
The commands sent are UPNP commands over TCP IP. You can send commands manually from tools like UPNP Device Spy. To automate things SoCo is a set of Python scripts which does all the hard work for you. EG: a simple example to pause a Sonos device:

import soco

device = soco.SoCo('192.168.0.72')  #set to the IP of your sonos device

device.pause()

Hope this helps, good luck
Cheers David

**Comment by DPH** [comment]
Hi Nicklas,
The short answer is NO.
You can't issue commands to Sonos from the browser.

You can read information from Sonos by using port 1400 eg: http://[Sonos
player IP]:1400/status
more info at: https://github.com/SoCo/SoCo/wiki/Information-Adresses

To get Sonos to do something you need to send it a upnp command.
You can do this from a Python program using SoCo,.

There is also a command line interface called SoCo/Socos see:
https://github.com/SoCo/socos
This allows you to enter lines in Dos or Linux to make Sonos do things

There are also utilities such as Device Spy that allow you to send UNP
commands.

Hope this helps.
Cheers David

**Comment by nicklasriedel** [comment]
Cant i rul pyton om Windows server ?

Sendt fra min iPhone

Den 09/01/2015 kl. 18.30 skrev David <notifications@github.com<mailto:notifications@github.com>>:

Hi Nicklas,
The short answer is NO.
You can't issue commands to Sonos from the browser.

You can read information from Sonos by using port 1400 eg: http://[Sonos
player IP]:1400/status
more info at: https://github.com/SoCo/SoCo/wiki/Information-Adresses

To get Sonos to do something you need to send it a upnp command.
You can do this from a Python program using SoCo,.

There is also a command line interface called SoCo/Socos see:
https://github.com/SoCo/socos
This allows you to enter lines in Dos or Linux to make Sonos do things

There are also utilities such as Device Spy that allow you to send UNP
commands.

Hope this helps.
Cheers David





On 7 January 2015 at 20:39, nicklasriedel <notifications@github.com<mailto:notifications@github.com>> wrote:

> Hi David
>
> Thank you bother to respond
>
> sorry if I ask a little silly but I am not so well known in these codes.
> but I can open a browser directly and test a command eg http:
> //192.168.10/Pause or in the style ??
>
> Med venlig hilsen - Kind Regards
>
> Nicklas Riedel
> Serviceteknikker
> Sikkerhed-service Glostrup
> [cid:_1_0A1758A80A17563C003E5782C1257BC9]
>
>
> Lindpro A/S
> Fabriksparken 58, DK-2600 Glostrup
>
>
> Dir.: +45 40 90 71 11
> Mail: niri@lindpro.dk<mailto:niri@lindpro.dk><mailto:niri@lindpro.dk> / Web: www.lindpro.dk<http://www.lindpro.dk>
> Velkommen til Lindpro
> Lindpro er mere end en traditionel el-installat?rvirksomhed. Vi kan vores
> h?ndvaerk, og vi ved, hvordan vi omsaetter erfaring og viden til
> vaerdiskabende l?sninger for vores kunder. Scan QR-koden - og oplev vores
> engagerede og kompetente medarbejdere. <
> http://www.youtube.com/watch?v=z7eUjUNm3qM>
> [cid:image001.gif@01CE99D4.F2BD93F0]
>
> Fra: David [mailto:notifications@github.com]
> Sendt: 30. december 2014 11:20
> Til: SoCo/SoCo
> Cc: Nicklas Riedel
> Emne: Re: [SoCo] program codes (#268)
>
>
> Hi, if I understand your question you are asking how the commands get sent
> to Sonos.
> The commands sent are UPNP commands over TCP IP. You can send commands
> manually from tools like UPNP Device Spy. To automate things SoCo is a set
> of Python scripts which does all the hard work for you. EG: a simple
> example to pause a Sonos device:
>
> import soco
>
> device = soco.SoCo('192.168.0.72') #set to the IP of your sonos device
>
> device.pause()
>
> Hope this helps, good luck
> Cheers David
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/SoCo/SoCo/issues/268#issuecomment-68345183>.
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/SoCo/SoCo/issues/268#issuecomment-69087941>.
>

-

**Comment by stefankoegl** [comment]
For making use of the SoCo library you *have to know how to write programs in Python*. Based on your questions it seems that this is not the case.

If you do want to write your own program to control your Sonos speakers, please start with one of the many [Python tutorials](https://www.google.at/search?q=python+tutorial) first. Additionally [this article](http://www.catb.org/esr/faqs/smart-questions.html) would also be a good read.
