### ISSUE TITLE
SoCo 0.10 discover() not working with Python 3.4?

### ISSUE THREAD

**Issue by poirier** [SoCo/SoCo#271]
Just downloaded SoCo and started trying the tutorial:

    $ python3.4
    Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
    [GCC 4.8.2] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import soco
    >>> soco.discover()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/poirier/working/SoCo/soco/core.py", line 102, in discover
        if "Sonos" not in data:
    TypeError: Type str doesn't support the buffer API
    >>> soco.__version__
    '0.10'
    >>>

**Comment by lawrenceakka** [comment]
This should be fixed now. Thanks for the report. If you want to use your installed version, replace `"Sonos"` with `b"Sonos"` at line 104 of `core.py`
