### ISSUE TITLE
Wrong title for spotify track 

### ISSUE THREAD

**Issue by pfischi** [SoCo/SoCo#272]
When I try to add a spotify item to the queue (with the add_to_queue fuction) the track title for this item is wrong (the internal spotify url is shown instead of the title). The item was prevoiusly generated from the "get_queue" function in core.py. This step seems to be fine whereas the variable is set with the right dc:title value.

Thanks,

Stefan

**Comment by KennethNielsen** [comment]
Hallo @pfischi 

Thanks for reporting this. What you are describing is a known problem. Basically, the information that you get with get_queue does not contain enough information to re-add it to the queue and have it be recognized as a proper music service track.

Then only way I see around this, is to get music service plugins (#262) working properly first, and then using the those, and then use the initialized music service plugins for the service to add the missing information, either at get_queue time or at add_to_queue time.

But I guess a fix for this is still a ways out.

Regards Kenneth

**Comment by lawrenceakka** [comment]
Apologies for the long delay. This is now possible with the development version of SoCo. See here for an example: https://gist.github.com/lawrenceakka/c8597d2533b6cc3e0d18
