### ISSUE TITLE
Tunein example don't work

### ISSUE THREAD

**Issue by sdomotica** [SoCo/SoCo#274]
Could you verify the tunein example.
Seems don't work anymore.
Thks

**Comment by lawrenceakka** [comment]
Which tunein example do you mean? Are you talking about `examples\commandline\tunein.py`?  That one works OK for me.  

If you are experiencing a problem, you need to say a bit more than "doesn't work", or we can't really help. For example, are you getting an error message? If so, what is it? What operating system are you using? What version of python?

Lawrence

**Comment by sdomotica** [comment]
Sorry, please close this. I made a stupid typo error.
