### ISSUE TITLE
album compalition

### ISSUE THREAD

**Issue by clemenstyp** [SoCo/SoCo#280]
Hello, 
i had an error in the data_structures.py file:
  File "/Library/Python/2.7/site-packages/soco/data_structures.py", line 48, in get_didl_object
    cls = DIDL_CLASS_TO_CLASS[xml.find(ns_tag('upnp', 'class')).text]
KeyError: 'object.container.album.musicAlbum.compilation'

I think it's because the data structure for album compilitons aren't defined. I think it's because I set the album grouping in the sonos settings to "itunes compalitions",

![bildschirmfoto 2015-01-21 um 19 50 56](https://cloud.githubusercontent.com/assets/1587123/5842668/f53c381c-a1a6-11e4-945b-421f5f73cb53.png)
 
I solved it by adding an DidlMusicAlbumCompilation class after the DidlMusicAlbum class definition. It is the same as the DidlMusicAlbum but with an item_class = 'object.container.album.musicAlbum.compilation'

Perhaps you can add this to the next version of soco.

I don't know if there is an easier way to do so. 

My new class declaration:

    class DidlMusicAlbumCompilation(DidlAlbum):
    
    """Class that represents a music library compalition album.

    :ivar item_class: The item_class for DidlMusicTrack is
        'object.container.album.musicAlbum.compilation'
    :ivar _translation: The dictionary-key-to-xml-tag-and-namespace-
        translation used when instantiating a DidlAlbum from XML. The value is
        shown below

        .. code-block :: python

            # key: (ns, tag)
            _translation = {
                'title': ('dc', 'title'),
                'creator': ('dc', 'creator'),
                'album_art_uri': ('upnp', 'albumArtURI'),
                'uri': ('', 'res')
            }

    """

    item_class = 'object.container.album.musicAlbum.compilation'
    # name: (ns, tag)
    _translation = {
        'title': ('dc', 'title'),
        'creator': ('dc', 'creator'),
        'album_art_uri': ('upnp', 'albumArtURI'),
        'uri': ('', 'res')
    }

    @property
    def album_art_uri(self):
        """Get and set the album art URI as an unicode object."""
        return self.content.get('album_art_uri')

    @album_art_uri.setter
    def album_art_uri(self, album_art_uri):  # pylint: disable=C0111
        self.content['album_art_uri'] = album_art_uri

**Comment by KennethNielsen** [comment]
Hallo  @clemenstyp and thanks for the report.

There has been some fairly extensive refactoring going on lately sorrounding the data structures, so it would be nice to know which version you are using:

```python
import soco
print(soco.__version__)
```

That being said. A quick glance at the code suggests that the new code also does not have support for `object.container.album.musicAlbum.compilation`, so it will probably need to be fixed up anyway.

**Comment by clemenstyp** [comment]
I am using Version  0.10, but it's the same when I use the latest github code.

I just have very little knowledge about python and I down't really understand how the DidlMusicAlbum Class work and how the programs knows that it has to use this class.  But my created DidlMusicAlbumCompilation Class has only one change (item_class = 'object.container.album.musicAlbum.compilation'), therefor it should only be a subclass of the DidlMusicAlbum class.

**Comment by lawrenceakka** [comment]
Thanks @clemenstyp
