### ISSUE TITLE
0.11 Pre-release straight switch gives error

### ISSUE THREAD

**Issue by robwebset** [SoCo/SoCo#284]
Hi all,I wasn't sure exactly how to raise this so thought I'd just do an issue that could easily be closed.

I thought I'd try doing a straight swap from 0.10 to 0.11 (pre-release) thinking that it would be a conpatible release - but now I'm not sure if it is? (Should we be highlighting this clearly in the release notes?)

I seem to be getting lots of errors like:
AttributeError: 'DidlMusicArtist' object has no attribute 'uri'
AttributeError: 'DidlPlaylistContainer' object has no attribute 'uri'

Any ideas? I use the uri as my unique ID accross the system (There is a case where I need a stateless interface - so passing the URI between the caller and my system was working well) - however it now looks like something has removed this.

Any help/suggestions for getting this working again would be great.

Thanks, Rob

**Comment by lawrenceakka** [comment]
We had a fairly extensive rewrite of the DIDL metadata code, which was started before 0.10 and has continued into 0.11:  see PR #256 

Each DIDL object (DidlMusicArtist, DidlPlaylistContainer) now has a `resources` property which is a *list* of `DidlResource` items. Each of those has a `uri` property, which is probably what you want. Note that in theory it is possible for a DIDL object to have more than one resource, ie. more than one `uri`

So, if t is, e.g., a DidlMusicTrack:
```python
>>>t.resources[0].uri
'x-sonos-http:track%3a3402413.mp3?sid=2&flags=32&sn=4'
```

**Comment by robwebset** [comment]
@lawrenceakka Thanks for the help - that got me passed that problem - do we need to mention this case in the release notes?

I do have another issue which it would be great if you could help with (I don't know if this is to do with any of the recent changes or not).  Previously I was able to browse/navigate down to a given track - using something like:

```
subCategory = urllib.quote(subCategory)
list = sonosDevice.browse_by_idstring(folderName, subCategory, totalCollected, batchSize, True)```

However I seem to be getting an error in some cases now - not sure if it is something to do with character encoding, any suggestions would be appreciated.

The message sent seens to be:

```
06:39:14 T:7268   DEBUG: script.sonos: Sending {u'SOAPACTION': u'urn:schemas-upnp-org:service:ContentDirectory:1#Browse', u'Content-Type': u'text/xml; charset="utf-8"'}, <?xml version="1.0" ?>
                                            <s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
                                              <s:Body>
                                                <u:Browse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1">
                                                  <ObjectID>A:ALBUMARTIST/4%2520Non%2520Blondes/Bigger%2C%20Better%2C%20Faster%2C%20More%21</ObjectID>
                                                  <BrowseFlag>BrowseDirectChildren</BrowseFlag>
                                                  <Filter>*</Filter>
                                                  <StartingIndex>0</StartingIndex>
                                                  <RequestedCount>100</RequestedCount>
                                                  <SortCriteria/>
                                                </u:Browse>
                                              </s:Body>
                                            </s:Envelope>
```

And the reply is:

```
06:39:14 T:7268   DEBUG: script.sonos: Received {'ext': '', 'content-type': 'text/xml; charset="utf-8"', 'connection': 'close', 'content-length': '347', 'server': 'Linux UPnP/1.0 Sonos/28.1-83040 (ZPS1)'}, <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>701</errorCode></UPnPError></detail></s:Fault></s:Body></s:Envelope>
06:39:14 T:7268   DEBUG: script.sonos: Received status 500 from 192.168.0.16
06:39:14 T:7268   DEBUG: script.sonos: Error <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>701</errorCode></UPnPError></detail></s:Fault></s:Body></s:Envelope>
06:39:14 T:7268   DEBUG: script.sonos: UPnP Error 701 received: No such object from 192.168.0.16
```
Thanks, Rob

**Comment by robwebset** [comment]
Not to worry about the other error I posted - looks like things got escaped twice - not sure how - but at least I know the main issue.

Thanks

Rob

**Comment by KennethNielsen** [comment]
@lawrenceakka I wonder if we should re-add uri as a property that points to just that, and document in the docstring that it just returns the first one. It would be a small addition and could be accompanied by a deprecation warning.

**Comment by lawrenceakka** [comment]
Given the delay, I'm not sure we need to do this now. No-one seems to have complained!
