### ISSUE TITLE
Trigger music library update

### ISSUE THREAD

**Issue by poirier** [SoCo/SoCo#285]
I'd like to be able to trigger Sonos to rescan my music share(s) and update my music library using SoCo, as that seems to be the only thing I have to go back to the Android app for.

I don't see a way to do that from SoCo right now. I haven't seen an API for that in the UPnP specs I've skimmed either, like the ContentDirectory service. But if anyone can point me to how to tell the Sonos to do the update, I'd be happy to take a stab at adding that to SoCo.

**Comment by lawrenceakka** [comment]
Sons adds various commands to the UPnP specs.  Here is a quick script I use to dump available commands to the terminal:

```python
# -*- coding: utf-8 -*-

""" Dump all known UPnP commands """

from __future__ import unicode_literals

from pprint import pprint

from soco import SoCo, discover, services

# get a zone player - any one will do
z1 = discover().pop()
print "Querying %s" % z1.player_name
# get an instance of each service
services = (srv(z1) for srv in services.Service.__subclasses__())
for srv in services:
    name = srv.service_type
    box = "="*79
    print "{0}\n|{1:^77}|\n{0}\n".format(box, name)
    for action in srv.iter_actions():
        print action.name
        print "~"*len(action.name)
        print "\n  Input"
        for arg in action.in_args:
            print "    ", arg
        print "\n  Output"
        for arg in action.out_args:
            print "    ", arg
        print "\n\n"

    # for var in srv.iter_event_vars():
    #     print "{}\n".format(var)
    print "\n\n"

```

From this, it looks like the RefreshShareIndex command of the ContentDirectory service might be what you are looking for. I haven't tested it though, so let us know what happens.

**Comment by poirier** [comment]
Thanks! Your script was really helpful. I've opened a pull request.
