### ISSUE TITLE
Builds failing - pep8 upgraded

### ISSUE THREAD

**Issue by lawrenceakka** [SoCo/SoCo#290]
pep8.py 1.6 has just been released. It has introduced new tests, which are causing all Travis builds to fail with error E402:  see https://github.com/jcrocholl/pep8/pull/304#issuecomment-66939162

I'm looking into it

**Comment by lawrenceakka** [comment]
Fixed up quite a lot of whitespace issues. I have also disabled the flake8 E402 check in Makefile. We can reenable it once pep8.py has issued a fixed release for some of the issues (e.g. imports within a try..except block, we we use a fair bit)

**Comment by dundeemt** [comment]
pep8 conformance can and probably should be a proper test in unittest.  See http://pep8.readthedocs.org/en/latest/advanced.html

Currently, you (me) can forget to run before commit and then have Travis fail on you - when this task could be automated and run as part of py.test.  Comments?

**Comment by KennethNielsen** [comment]
@dundeemt I think we have earlier not added linting to the test suite, because a test suite must be lightning fast to serve its purpose. pylint takes much too long to be executed as a unittest, but pep8 is about a second on my laptop, which **may** be ok. What does everyone else thinks?

**Comment by lawrenceakka** [comment]
I wouldn't be inclined to add a pep8 check as part of the unit tests (though I not that pytest has a pep8 plugin which might be useful)

If you forget to check the code before commit (which I do regularly) you can set up a git pre-commit hook to run make for you.  This will run flake8 over the changed files and disallow the committing of any non-pep8 code.

**Comment by dundeemt** [comment]
@lawrenceakka  pytest-pep8 is handy. 

My argument is that, If the CI tests are going to include pep8 requirements then they should run by default in the local test suite to avoid surprises.  pytest-pep8 uses pytest-cache and only runs pep8 against those files that were modified or untested previously.  You can also configure it via pytest.ini to allow certain exceptions and skip certain files.   

If my argument is not enough to sway the group, it is ok, but I thought I should bring up the subject.
Best,
Jeff

**Comment by KennethNielsen** [comment]
I tend to agree with @lawrenceakka then, that the pre-commit hook is probably the better option, from my point of view, to keep the unittest suite fast. (There are already a few tests that takes annoyingly long ;))

**Comment by KennethNielsen** [comment]
The build is no longer failing ... The pre-commit implemented and this discussion hasn't seen any activity in a while. I'll close this. Feel free to re-open if it turns out to still be relevant.

**Comment by ghcs27** [comment]
This has been here for some time...
Any reason why it's not closed?

**Comment by KennethNielsen** [comment]
@ghcs27 looks like I intended to close it, but forgot
