### ISSUE TITLE
tunein example UnicodeEncodeError

### ISSUE THREAD

**Issue by ulleberg** [SoCo/SoCo#293]
Hi 

I get an UnicodeEncodeError when running tunein.py, I'm using Python 2.7.9

I believe it's because my 4th station is named "NRK P1 Trønderlag" [ø, is the issue I believe]

C:\<path>>python Sono_tunein.py 10.0.1.20 4
returned 1 of a possible 10 radio stations:
Traceback (most recent call last):
  File "Sono_tunein.py", line 51, in <module>
    print station['title']
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\xf8' in position 9: character maps to <
undefined>

thanks

**Comment by lawrenceakka** [comment]
Takk, @ulleberg
