### ISSUE TITLE
Error while playing a specified radio station

### ISSUE THREAD

**Issue by pfischi** [SoCo/SoCo#294]
An error occurs if the station "Alsterradio 106.8 Rock" is played. You can find this station in TunIn -> Location -> Europe -> Germany -> Hamburg.

Here is the error:

File "/home/s/projects/shSonos/server.sonos/soco/events.py", line 230, in do_NOTIFY
    variables = parse_event_xml(content)
  File "/home/s/projects/shSonos/server.sonos/soco/events.py", line 136, in parse_event_xml
    value = from_didl_string(value)[0]
  File "/home/s/projects/shSonos/server.sonos/soco/data_structures.py", line 78, in from_didl_string
    items.append(cls.from_element(elt))
  File "/home/s/projects/shSonos/server.sonos/soco/data_structures.py", line 385, in from_element
    title = really_unicode(title_elt.text)
  File "/home/s/projects/shSonos/server.sonos/soco/utils.py", line 30, in really_unicode
    raise ValueError('%s is not a string at all.' % in_string)

Because the argument in_string is None, the really_unicode function fails. The metadata given by the radio station is a little bit strange. E.g. the track title comes in this format "\"Beat It Von Michael Jackson\"". This could be the issue.

As a workaround, i check for a none value in really_unicode(). A hack, but it seems to work.

```
def really_unicode(in_string):
 
    if not in_string:
        return
    if type(in_string) is StringType:
        for args in (('utf-8',), ('latin-1',), ('ascii', 'replace')):
            try:
                in_string = in_string.decode(*args)
                break
            except UnicodeDecodeError:
                continue
    if type(in_string) is not UnicodeType:
        raise ValueError('%s is not a string at all.' % in_string)
    return in_string
```

Pfischi

**Comment by lawrenceakka** [comment]
I am unable to reproduce this (sorry it has taken me so long to try). Is it still a problem?  If so, please re-open this bug report
