### ISSUE TITLE
Play URI to local file

### ISSUE THREAD

**Issue by RobSmith2** [SoCo/SoCo#297]
Hi, 

I've been trying to get play_url. to work with a local .mp3 file.

I've tried sonos.play_uri('path/to/file.mp3') and sonos.play_url('file://path/to/file.mp3') however I get a UPnP error 714 thrown. 

The question is can the module play from local files or do songs have to come from .mp3 http streams? All examples i've seen show remote http streams however i'd ideally like to simply play local mp3 files. 

Thanks!

**Comment by crummy** [comment]
Sonos doesn't have access to files hosted locally on your computer by default. You could run a simple HTTP server to change this, however, and then play_url('http://yourcomputer/file.mp3')

**Comment by DPH** [comment]
You can play files from any file system via Sonos, but the permissions must be set so Sonos can read from the file system. I use SoCo to play tracks from my NAS which has read access to all local devices.
```
import soco
device = soco.SoCo('192.168.1.xx')
device.play_uri('x-file-cifs://My_NAS/Music/track_1.mp3')
```
You have to use the prefix 'x-file-cifs://' 
You can play tracks form your PC if you set the permissions correctly and use the PC host name. 

Hope this helps,
Cheers David

**Comment by KennethNielsen** [comment]
Hallo @RobSmith2 

I can see that there are a couple of suggestions on how to do what you want, so I'll consider this closed. Please feel free to re-open if your question was not answered.
