### ISSUE TITLE
Events no longer received in 0.11

### ISSUE THREAD

**Issue by robwebset** [SoCo/SoCo#317]
Hi All,

I just noticed that my app is no longer receiving events with 0.11 - I normally use this to be notified of the "Next Track" when "random" is enabled.

Looking at the log I can see all the subscribe details:
```
Event listener started
Event listener running on ('192.168.0.31', 1400)
Subscribed to http://192.168.0.16:1400/MediaRenderer/AVTransport/Event, sid: uuid:RINCON_000E58C8FC4601400_sub0000000063
```

I guess that when these notifications are received I would then see:

```
Event content: ...
```

In the log, but I never see that.

Is anyone else seeing this?
(Sorry for raising a bug, wasn't really sure the best way to ask the question)

Thanks

Rob

**Comment by KennethNielsen** [comment]
Hi @robwebset 

Sorry about the long wait on this. Can you share code and instructions to reproduce, that I will check it here.

Regards Kenneth

**Comment by robwebset** [comment]
Hi @KennethNielsen 

Not on my Sonos system at the moment, but it is pretty much like this:

```
sonosDevice = SoCo("IP-ADDESS")

# Subscribe to receive notifications of changes
sub = sonosDevice.avTransport.subscribe()

keepLooping = True
queueItem = None
while keepLooping:
        try:
            # Get the most recent event received
            while not sub.events.empty():
                try:
                    # Get the next event - but do not block or wait for an event
                    # if there is not already one there
                    queueItem = sub.events.get(False)
                except:
                    log("Sonos: Queue get failed: %s" % traceback.format_exc())

            # Now log the details of an event if there is one there
            if queueItem is not None:
                log("Event details: %s" % queueItem)
        except:
            log("Sonos: Failed to get latest event details: %s" % traceback.format_exc())

	if queueItem is not None:
		keepLooping = False
```

Thanks

Rob

**Comment by KennethNielsen** [comment]
If I run the example code from the events module on 0.11.1:

```python
from __future__ import print_function
try:
    from queue import Empty
except:  # Py2.7
    from Queue import Empty

import soco
from pprint import pprint
from soco.events import event_listener
# pick a device at random
device = soco.discover().pop()
print (device.player_name)
sub = device.renderingControl.subscribe()
#sub2 = device.avTransport.subscribe()

while True:
    try:
        event = sub.events.get(timeout=0.5)
        pprint (event.variables)
    except Empty:
        pass

    except KeyboardInterrupt:
        sub.unsubscribe()
        sub2.unsubscribe()
        event_listener.stop()
        break
```
and only listen for rendering control, then yes, I get events.

**Comment by KennethNielsen** [comment]
Hallo @robwebset 

I just remembered that you are probably using this for the Kodi plugin, in which case you may not see the exceptions. All the event parsing exceptions happen in their own threads, which mean that they do not make the program stop. So, if you do not see terminal output, but simply wait for events on the queue, it would seem as if none is ever received. So, if this is the case, this issue is probably the same as #276.

**Comment by robwebset** [comment]
Hi @KennethNielsen 

Thanks for your assistance - I managed to get a little time today to look more at this - I think the Sonos has actually stopped sending the "Next Track" information in events now (last firmware update) - as the way the playlist is generated has changed - so the next item in the playlist (even if random is enabled) will always be the next track (Which was not the case if random was enabled previously)

Thanks
Rob
