### ISSUE TITLE
data_structures.py : DidlResource - add to_dict method

### ISSUE THREAD

**Issue by dundeemt** [SoCo/SoCo#318]
When using get_queue.to_dict, it returns a dict that has a 'resources' element that is a DidlResource object -- which is not serializable in json.  Have a to_dict method on the DidlResource would make life easier, and then get_queue's to_dict could call to_dict on the DidlResource.

I'll submit a patch but I have a question first.  When a DidlResource property is None, should the to_dict method return {'property_foo': None, ...}  or just not include the key in the returned dict?  I would think that the first option is preferable as it requires simpler logic to deal with key=>None than deal with a missing key.    Let me know and I'll start on the patch.   (I'll open a second issue on the get_queue.to_dict calling to_dict on the DidlResource, if/when this patch is accepted, because that might have other ramifications.)

**Comment by KennethNielsen** [comment]
Hallo @dundeemt 

Sorry about the long response time, it seems everyone was busy over the summer.

Regarding the behavior for properties that are None I agree with you, that the preferable way to do it is to include it in the dict with a None value rather than leaving it out. So I'm for options number 1 and happy hacking. We look forward to the PR.

**Comment by dundeemt** [comment]
gotcha.  I'll start on it -- I'm doing a web app, so making the .to_dict()
work recursively makes my json results cleaner.  Currently I'm stripping
out the DidlResource and just returning the resources[0].uri for the
container.

On Wed, Aug 12, 2015 at 2:04 PM, Kenneth Nielsen <notifications@github.com>
wrote:

> Hallo @dundeemt <https://github.com/dundeemt>
>
> Sorry about the long response time, it seems everyone was busy over the
> summer.
>
> Regarding the behavior for properties that are None I agree with you, that
> the preferable way to do it is to include it in the dict with a None value
> rather than leaving it out. So I'm for options number 1 and happy hacking.
> We look forward to the PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SoCo/SoCo/issues/318#issuecomment-130413691>.
>



-- 
Best,

Jeff Hinrichs
dundeemt@gmail.com
402.218.1473

**Comment by KennethNielsen** [comment]
Sounds great. I'll have a look at the PR.

BTW, I should mention, that you are also welcome to add to_json and from_json methods, to save you the serialization in your code. We used to have it in the data structures, but when they were re-written, we decided not to put them in again before someone actually needed them, which might be now ;)

**Comment by dundeemt** [comment]
I am not sure that adding a to_json /( from_json) would be of wide benefit
and puts another requirement (although in stdlib) on SoCo.  After this PR
and then the upcoming issue that changes DidlObject.to_dict(), SoCo is
returning a clean usable structure that a developer can easily change to
json on their own.  For example: the DidlResource.uri, a very important
piece of info that logically should have a 1 to 1 relation with a
DidlObject is returned as an element in a list (I'm sure that is the UPnP
definition.) However, it is more painful to deal with that in javascript
then to have my 3rd party python service make the first DidlResource.uri of
the list, a proper member of the DidlObject info I am returing to the
javascript.

This works for my usage, so I wouldn't benefit from a to_json method, since
I am going to transform the data before I pass it on.  So you still haven't
found someone that actually needs / benefits from SoCo supplying a to_json
method.  So please don't add it on  my account. ;)

Best,
Jeff


On Mon, Aug 17, 2015 at 10:26 AM, Kenneth Nielsen <notifications@github.com>
wrote:

> Sounds great. I'll have a look at the PR.
>
> BTW, I should mention, that you are also welcome to add to_json and
> from_json methods, to save you the serialization in your code. We used to
> have it in the data structures, but when they were re-written, we decided
> not to put them in again before someone actually needed them, which might
> be now ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SoCo/SoCo/issues/318#issuecomment-131861489>.
>



-- 
Best,

Jeff Hinrichs
dundeemt@gmail.com
402.218.1473

**Comment by KennethNielsen** [comment]
Requirements in stdlib are no problem but if you do not benefit let's not do it until there is a call for it. My point was just, if you need it, I'd have no objection to having it added.
