### ISSUE TITLE
Testing documentation - broken?  py.test fails to import soco

### ISSUE THREAD

**Issue by dundeemt** [SoCo/SoCo#319]
following the docs, py.test will fail to run the unit tests complaining about "No module named soco"

This can be fixed by either modifying sys.path (ugly) in the tests or installing the soco source in editable mode

`pip install -e .`

Should probably add the part about installing the soco module in editable mode to http://docs.python-soco.com/en/latest/unittests.html

**Comment by KennethNielsen** [comment]
Hallo @dundeemt 

I agree that there is something missing from the docs about how to execute the unittest (There does indeed seem to several things missing from that section).

However, the unittest is meant purely for development, and since potential developers will need to run the source code directly from a git clone, I don't think it makes much to discuss the pip solution. Properly there should be some information about how to modify the path without editing the test code.

What do you think?

**Comment by dundeemt** [comment]
Sure.  You can manually edit your path, I tend to always work in virutalenvs so I gravitate to `pip install -e .` to let pip do the heavy lifting of path modification.  Only time you need worry about it is after your do a release and have a new version number, but then just a quick `pip install -e .` and you are back in business.  
What changes do you make to your path to enable py.test to find what it needs without making a mess? Honest question, I picked up on -e trick from working on twine.  That's how they handle it.

I am good to go with however you decide, it should be documented so potential contributors can easily reproduce a good environment (be able to run the test suite) before they start hacking on their pull request; ")

**Comment by KennethNielsen** [comment]
Actually, having looked at it a little more I think the -e trick is really neat and the version that we should include in the doce. I guess people that want to modify the path of their virtual environment knows how. I will have a look at the docs and propose a change for you to review.

Just for the record. The way to modify the path in a virtual environment (at least on Linux and I guess Mac) is to edit the bin/activate script (which is a bash script) and add a line at the end along the lines of:

```bash
export PYTHONPATH=$HOME/myvirtualenvs/soco/SoCo
```

where that last `SoCo` is the path of the git archive.

**Comment by dundeemt** [comment]
My initial reaction to seeing the -e trick was the same as yours.  What
magic is this?!   But once I tried it, it came quite naturally.

On Wed, Jul 29, 2015 at 3:04 PM, Kenneth Nielsen <notifications@github.com>
wrote:

> Actually, having looked at it a little more I think the -e trick is really
> neat and the version that we should include in the doce. I guess people
> that want to modify the path of their virtual environment knows how. I will
> have a look at the docs and propose a change for you to review.
>
> Just for the record. The way to modify the path in a virtual environment
> (at least on Linux and I guess Mac) is to edit the bin/activate script
> (which is a bash script) and add a line at the end along the lines of:
>
> export PYTHONPATH=$HOME/myvirtualenvs/soco/SoCo
>
> where that last SoCo is the path of the git archive.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SoCo/SoCo/issues/319#issuecomment-126081029>.
>



-- 
Best,

Jeff Hinrichs
dundeemt@gmail.com
402.218.1473

**Comment by KennethNielsen** [comment]
Hey @dundeemt 

Can you have a look at #327 and see if you think it fixes the problem?
