### ISSUE TITLE
Drop support for python 3.2

### ISSUE THREAD

**Issue by KennethNielsen** [SoCo/SoCo#324]
Quoted from the original description in #263

> From #255

> The new versions of pylint and astroid have dropped support for Python 2.6 (and presumably also for python 3.2). At the moment, we have pinned to old versions in requirements-dev.txt. We will have to decide what to do about our own Python 2.6 support going forward. One option may be to have Travis use different versions of pylon etc for Py2.6, but this seems a bit messy.

I suggest to split the discussion up, and in this issue only discuss dropping 3.2

This will not solve the problem with dropped support for old versions in some of the projects we depend on, but will get us rid of some of the old version in the support. At least python 3.2 have some annoying coding requirements that it would be nice to get rid of.

One problem is that I think the current version of Raspbian (Debian for Raspberry Pis) still replies on Pythons 3.2 and since people are doing fun things with Raspberry Pis and SoCo, I don't think we should pull support until some time after Raspbian has upgraded. I will see if I can find some information about their support plan.

Python 3.2 is from February 11.

**Comment by stefankoegl** [comment]
As far as I know we do not support Python 3.0 and 3.1 at all (at least tests are not run against those versions).

How exactly is the situation with Raspbian? Is it possible to install 3.3 / 3.4 in addition to 3.2? If so, we could just advise to run SoCo in a virtualenv with a more recent Python version.

**Comment by KennethNielsen** [comment]
@stefankoegl ah, you are correct about 3.0 ad 3.1.

I don't think you can install newer versions without compiling it yourself, but I will have to check. 

However, as I mentioned above, since we can't remove 2.6 yet, removing 3.2 would only be for coding convenience and would not fix the problems with pinned versions of dependencies. For this reason, I would rather try and figure out what the raspbian plans are and then figure out a plan from there. Because if they say like 6 months, then maybe it is ok to just wait it out.

BTW. I will edit the issue description only discuss 3.2.

**Comment by KennethNielsen** [comment]
Raspbian has just been debased to Jessie (http://www.phoronix.com/scan.php?page=news_item&px=Raspbian-Jessie-Released) which most likely means a newer Python. I will check it Monday.

**Comment by stefankoegl** [comment]
Any news?

**Comment by lawrenceakka** [comment]
Raspbian/Jessie comes with Python 2.7 and 3.4

More and more packages are dropping 3.2, e.g. pep8 and Mock 2 (though the latter still supports Python 2.6). I can see no reason to continue supporting 3.2 in SoCo (and would lie to upgrade to Mock 2), so I will officially drop it unless anyone complains shortly!

**Comment by KennethNielsen** [comment]
Yeah, sorry about not getting back sooner. Regarding Python versions in raspbian, what @lawrenceakka said.

@lawrenceakka I agree, there have been no objections for a good long while,  so I think we are about ready to drop it.
