### ISSUE TITLE
Drop support for python 2.6

### ISSUE THREAD

**Issue by KennethNielsen** [SoCo/SoCo#325]
Quoted from the original description in #263

> From #255
> 
> The new versions of pylint and astroid have dropped support for Python 2.6 (and presumably also for python 3.2). At the moment, we have pinned to old versions in requirements-dev.txt. We will have to decide what to do about our own Python 2.6 support going forward. One option may be to have Travis use different versions of pylon etc for Py2.6, but this seems a bit messy.

For reference, please see the lengthy discussion about the issues pertaining to dropping support for Python 2.6 in #263.

**Comment by robwebset** [comment]
Just for the record as this seems to keep coming up again and again - I would like to keep Python 2.6 support.  Full discussion on a couple of other issues that have been raised in the past.

I would suggest closing this issue and just keeping the Python 2.6 support. (Rather than keep having the same discussion again and again) ... Groundhog Day anyone?

**Comment by KennethNielsen** [comment]
@robwebset 

I wasn't bringing it up again. I was merely splitting an old issue up into 2, one that could probably be resolved soon (3.0-3.2) and one that probably won't be (2.6).

I do however still however consider it an issue, so I think we should leave it open until it is resolved. But I was not trying to restart the discussion. I guess we can revisit this every 6 months and see if the Kodi devs pulls it together.

**Comment by stefankoegl** [comment]
I guess we will remove Python 2.6 eventually (eg when Kodi has been updated). Until then we should keep the issue open as @KennethNielsen suggested.

**Comment by lawrenceakka** [comment]
This commit from October 2015 updates Kodi to use Python 2.7, a mere three years after EOL for Python 2.6 😉: https://github.com/xbmc/xbmc/commit/c1adca4c79727f2d0683a7f8144e1af722649f3f

It did not make it into Kodi 16 (released Feb 2016) so presumably will make it into Kodi 17 when it eventually comes out. No sign of Python 3 yet, though!

**Comment by lawrenceakka** [comment]
See also here: https://github.com/xbmc/xbmc/pull/8207 and here: http://forum.kodi.tv/showthread.php?tid=250936

**Comment by robwebset** [comment]
Hi @lawrenceakka 

Yes, it's slow, but some progress.  Can I suggest we keep SoCo supporting 2.6 until the release **after** Kodi goes to python 2.7?
i.e. If it goes into Kodi v17 - then the Soco release after v18 is released has 2.6 support removed? (That way it will be safe enough that Kodi will not back the change out!)

Thanks, Rob

**Comment by KennethNielsen** [comment]
\o/ \o/ \o/

**Comment by robwebset** [comment]
I've got no issue with "Wait and See" :) maybe wait until at least 17.1 is released before we take the decision>

**Comment by KennethNielsen** [comment]
Sounds reasonable

**Comment by hugovk** [comment]
Kodi 17.5 is now out with Python 2.7.
https://github.com/xbmc/xbmc/blob/17.5-Krypton/tools/depends/native/Makefile#L9

Here's the pip installs for SoCo from PyPI for the last month, supporting a drop of 2.6:
```
$ pypinfo --percent --pip soco pyversion
python_version percent download_count
-------------- ------- --------------
3.5              37.2%            823
3.6              29.0%            641
2.7              17.0%            377
3.4              15.3%            338
3.3               1.5%             33
2.6               0.0%              1

```

Python 3.3 went EOL last month and also has low numbers, how about dropping that too?

**Comment by stefankoegl** [comment]
+1 for both 2.6 and 3.3

**Comment by hugovk** [comment]
See PR #523.

**Comment by KennethNielsen** [comment]
@robwebset since we are way past the 17.1 that we agreed on, I assume you are satisfied as well.

**Comment by KennethNielsen** [comment]
Personally I don't see any pressing need to drop 3.3, since as I remember it, there are penalties in code quality for supporting that, like there are for 2.6 (and like there were for 3.0 -> 3.2).

**Comment by robwebset** [comment]
@KennethNielsen I think we should be OK to drop 2.6 support - but not 100% convinced by the pull request that's about for deliberately changing things just for the sake of it :) - But having new code support 2.7+ seems OK to me.

**Comment by robwebset** [comment]
Oh, BTW: I don't think the Download of version graph is really a useful metric in this case - it just shows recent downloads - not people using it.

For example - The iOS version 10.2 downloads at the moment will be pretty much zero (as you can't install it) - but there are still a lot of phones using ios 10.2 (i.e. not updated to ios11).

Downloads != Usage

**Comment by stefankoegl** [comment]
> Oh, BTW: I don't think the Download of version graph is really a useful metric in this case - it just 
> shows recent downloads - not people using it.

That's right. But what it does show is installations and updates. And it seems that barely anyone is installing SoCo on 2.6 or 3.3 anymore. Even if we drop support, the people that are using the current version can continue to do so.

Suggestion: let's release 1.13 (#442) soon (maybe on the upcoming weekend), and merge this pull request right afterwards, including the removal of 3.3.

**Comment by KennethNielsen** [comment]
@stefankoegl yeah, but Python 2.6 support is starting to block merging PR's, as the test fail due to dependencies no longer installing on Python 2.6. What I would suggest is a minimal removal of Python 2.6 **now** (as in just removing it from the list of supported and tested versions). Then we can argue about cleaning up (which I also think should happen) later.

**Comment by KennethNielsen** [comment]
BTW. This issue is about Python 2.6 only. I think we should have a separate one about dropping 3.3, since the arguments seriously differ AFAIK. 3.3 is just EOL'ed, 2.6 is seriously holding us back.

**Comment by stefankoegl** [comment]
OK, agreed.

**Comment by hugovk** [comment]
See https://github.com/SoCo/SoCo/issues/525 to discuss dropping 3.3.
