### ISSUE TITLE
Building docs fail on inheritance diagram extension in data_structures

### ISSUE THREAD

**Issue by KennethNielsen** [SoCo/SoCo#326]
Building the docs fail with python 3 and current versions of dependencies from pypi. The error is:

``
writing output... [  6%] data-structures-mod                                               
Exception occurred:
  File "/home/kenneth/tmp/socodoc/lib/python3.4/site-packages/sphinx/ext/inheritance_diagram.py", line 262, in generate_dot
    for name, fullname, bases, tooltip in sorted(self.class_info):
TypeError: unorderable types: str() < NoneType()
The full traceback has been saved in /tmp/sphinx-err-40j5sr86.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:45: recipe for target 'html' failed
make: *** [html] Error 1
``

The only thing that we do to trigger this, is the use of a module for the inheritance-diagram extension. This module works under python 3, so this may be an upstream bug. I will report it and see what happens.

**Comment by KennethNielsen** [comment]
Here is a link to the complete traceback that is mentioned: http://pastebin.com/28hvZdgY

**Comment by lawrenceakka** [comment]
This is caused by the way in which `DidlMetaClass` is declared as a metaclass of `DidlObject`. I don't think we can really blame Sphinx, since what we are doing is rather hacky, to attempt to achieve Py2/3 compatibility.  

Replacing
```python
class DidlObject(DidlMetaClass(str('DidlMetaClass'), (object,), {})):
```
with
```
class DidlObject(object):
    __metaclass__ = DidlMetaClass
```
makes the doc build work on Python 3, but of course it then breaks on Python 2. It may be that using `six` or `python-future` fixes it. I haven't tried yet.

**Comment by lawrenceakka** [comment]
The code from `python-future` works nicely. I have put it in `compat.py`, and the inheritance diagram now builds correctly in Py2/3
