### ISSUE TITLE
Release notes for 0.12

### ISSUE THREAD

**Issue by KennethNielsen** [SoCo/SoCo#332]
For every change that goes into the 0.12 release. Please make a small description here, link to the PR (any issues) and mention whether it is a bug fix or not.

@stefankoegl you usually open these, but I thought I would just get it started.

**Comment by KennethNielsen** [comment]
Add information to the docs about how to put SoCo in the Python path, for test execution. PR #327 issue #319.

**Comment by KennethNielsen** [comment]
Clear zone group cache and reparse zone group information after join and unjoin to prevent giving wrong topology information. (BUGFIX). PR #323 issue #321.

**Comment by mikix** [comment]
Fix typo preventing SoCo from parsing the audio metadata object used when a TV is playing. PR #331.

**Comment by dundeemt** [comment]
added to_dict() / from_dict() to DidlResource PR #330  Issue #318

**Comment by lawrenceakka** [comment]
New MusicService class for access to all the music services known to Sonos.  Note that some of this code is still unstable, and in particular the data structures returned by methods such as `get_metadata` may change in future. (#262)

**Comment by lawrenceakka** [comment]
All tests have been moved from the unittests directory to the tests directory ( #336 )

**Comment by lawrenceakka** [comment]
For developers, more make targets, and a better sdist build ( #346 )

**Comment by lawrenceakka** [comment]
Added `discovery.any_soco()`, for when you need a SoCo instance, but you don't care which. This is slightly better than the traditional `device = soco.discover().pop()` since it will return an existing instance if one is available, without sending discovery packets ( #262 )

**Comment by dundeemt** [comment]
Modified `DidlObject.to_dict()` so that any associated `resources` list will be also returned as a list of dictionaries instead of returning a list of DidlResource objects. (#340)

**Comment by lawrenceakka** [comment]
Added a `sonosdump` tool in `dev_tools`, which can print out the various UPnP methods which Sonos uses

**Comment by lawrenceakka** [comment]
Methods relating to the music library (`get_artists`, `get_album_artists`, `get_albums` and others) have been moved to the music_library module. Instead of `device.get_album_artists()`, please now use `device.music_library.get_album_artists()` etc. Old code will continue to work for the moment, but will raise deprecation warnings (#350)

**Comment by dundeemt** [comment]
Added remove_sonos_playlist method.  Closes issue #341 (PR #345)

**Comment by dundeemt** [comment]
Added methods for sonos playlist management: `reorder_sonos_playlist`, `clear_sonos_playlist`, `move_in_sonos_playlist`, `remove_from_sonos_playlist`, `get_sonos_playlist_by_attr` (PR #352)

**Comment by quatauta** [comment]
Support playmodes repeat-one (`REPEAT_ONE`) and shuffle-repeat-one (`SHUFFLE_REPEAT_ONE`) introduced by Sonos 6.0 (PR #387)

**Comment by KennethNielsen** [comment]
Fix bug where SoCo would raise exception if music services sent metadata with invalid XML characters (PR #392, Issue #386)

**Comment by lawrenceakka** [comment]
Better discovery (PR #395): SoCo tries harder to find devices on the local network, particularly where there are multiple network interfaces. The default discovery timeout is also increased to 5 seconds

**Comment by lawrenceakka** [comment]
Drop support for Python 3.2 (Issue #324)

**Comment by KennethNielsen** [comment]
Large work package on the docs, which contains a new front page, more sections, some advanced topics and an example page (PR #406).

**Comment by KennethNielsen** [comment]
#302 added optional timeout argument to be passed onto requests when getting speaker info.

**Comment by KennethNielsen** [comment]
#425 Ignore .# specified subclasses in Didl xml.

Several music services seem to use an out-of-spec way to make sub classes in Didl, by specifying the subclass name or function after a #. This caused our implementation of Didl to reject it. This has now been fixed by simple ignoring these un-official subclasses.

**Comment by lawrenceakka** [comment]
#430 Event lister was (incorrectly) responding to GET and HEAD requests, which could result in local files being served.

**Comment by agriffis** [comment]
Rather than call out #432 separately, might as well roll it into: Better discovery (PR #395, #432) ...

**Comment by americanwookie** [comment]
Added methods to manipulate sonos sleep functionality: `set_sleep_timer`, `get_sleep_timer` (PR #413)

**Comment by KennethNielsen** [comment]
Made a hard deprecation of the Spotify plugin #423 since the API it relied on has been deprecated and it therefore no longer worked #401.
