### ISSUE TITLE
create_playlist_from_queue results in UPnP Error 803 - but, playlist is created

### ISSUE THREAD

**Issue by dundeemt** [SoCo/SoCo#334]
calling method results in a UPNP Error 803 but playlist is created.

```python
>>> sonos.get_sonos_playlists()
SearchResult(items=[<DidlPlaylistContainer '80's College' at 0x7efc9ec255d0>, <DidlPlaylistContainer 'Alexs Only' at 0x7efc9ec25bd0>, <DidlPlaylistContainer 'Classical' at 0x7efc9ec25250>, <DidlPlaylistContainer 'Gillians playlist' at 0x7efc9ec25190>, <DidlPlaylistContainer 'Kool Christmas' at 0x7efc9ec25890>, <DidlPlaylistContainer 'Soul' at 0x7efc9ec253d0>, <DidlPlaylistContainer 'Workout' at 0x7efc9ec25d90>], search_type='sonos_playlists')
>>> newpl = sonos.create_sonos_playlist_from_queue(title='Foo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jlh/projects/chilledsoco/local/lib/python2.7/site-packages/soco/core.py", line 95, in inner_function
    return function(self, *args, **kwargs)
  File "/home/jlh/projects/chilledsoco/local/lib/python2.7/site-packages/soco/core.py", line 1759, in create_sonos_playlist_from_queue
    ('ObjectID', '')
  File "/home/jlh/projects/chilledsoco/local/lib/python2.7/site-packages/soco/services.py", line 156, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/home/jlh/projects/chilledsoco/local/lib/python2.7/site-packages/soco/services.py", line 357, in send_command
    self.handle_upnp_error(response.text)
  File "/home/jlh/projects/chilledsoco/local/lib/python2.7/site-packages/soco/services.py", line 417, in handle_upnp_error
    error_xml=xml_error
soco.exceptions.SoCoUPnPException: UPnP Error 803 received:  from 192.168.2.191

>>> sonos.get_sonos_playlists()
SearchResult(items=[<DidlPlaylistContainer '80's College' at 0x7efc9ec25690>, <DidlPlaylistContainer 'Alexs Only' at 0x7efc9ec251d0>, <DidlPlaylistContainer 'Classical' at 0x7efc9ec25410>, <DidlPlaylistContainer 'Foo' at 0x7efc9ec25b90>, <DidlPlaylistContainer 'Gillians playlist' at 0x7efc9ec25b10>, <DidlPlaylistContainer 'Kool Christmas' at 0x7efc9ec25850>, <DidlPlaylistContainer 'Soul' at 0x7efc9ec25350>, <DidlPlaylistContainer 'Workout' at 0x7efc9ec25490>], search_type='sonos_playlists')
```

Device Information:
<softwareVersion>29.5-91030</softwareVersion>
<hardwareVersion>1.9.1.10-1</hardwareVersion>
<minCompatibleVersion>28.0-00000</minCompatibleVersion>
<legacyCompatibleVersion>24.0-0000</legacyCompatibleVersion>
<displayVersion>5.4</displayVersion>

soco version: 0.11.1

Google search could only find that this error is defined by the UPnP vendor.
http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.1.pdf
800-899 -- TBD Action-specific errors for non-standard actions. --  Defined by UPnP vendor. 

I am hoping that someone can confirm what I am seeing.

**Comment by dundeemt** [comment]
Here is a short script that should confirm the error.  If you would, please run and report back your results.

```python
"""demonstrate the UPnP 803 Error when creating a playlist from the queue"""
import sys
import soco

def main():
    soni = soco.discover()
    if not soni:
        sys.exit("Sorry, No sonos devices could be found.")

    sonos = list(soni)[0]
    print "Found: %s" % sonos
    print "==== begin speaker info ===="
    print sonos.get_speaker_info()
    print "==== end speaker info ===="
    print
    print "please include speaker info with your comment."

    queue_list = sonos.get_queue()
    if not queue_list:
        sys.exit("Please add atleast 1 item to your %s queue and rerun" % sonos)
    print "Ok, you have stuff in your queue. Let's create a playlist from it."

    print "Ok the next should error out, please report if it does."
    print
    sonos.create_sonos_playlist_from_queue(title='Foo')

    print "No error for you. Please Report the fact"


if __name__ == '__main__':
    main()

```

**Comment by lawrenceakka** [comment]
It works fine for me. How many speakers do you have in the group?  Are you, for example, trying to create a playlist on a zone which is not the group coordinator?

**Comment by dundeemt** [comment]
I have three zones, and have gone against the coordinator for each.  The
weird thing is that it creates the named sonos playlist and still returns
the 803 error.  I am going to find a windows machine and watch it over
wireshark to see what the app does differently than me.   I've created a
delete_sonos_playlist using DestroyObject and it works fine against the
same coordinators.   weird but I'll get it sorted.

3 zones
* playbar + right/left
* play:1
* play:1

The two other zones with play:1 are different devices than the right/left
that are grouped with the playbar. 5 speakers total.

On Thu, Aug 27, 2015 at 12:41 PM, Lawrence Akka <notifications@github.com>
wrote:

> It works fine for me. How many speakers do you have in the group? Are you,
> for example, trying to create a playlist on a zone which is not the group
> coordinator?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SoCo/SoCo/issues/334#issuecomment-135503401>.
>



-- 
Best,

Jeff Hinrichs
dundeemt@gmail.com
402.218.1473

**Comment by KennethNielsen** [comment]
Also no errors for me.

**Comment by dundeemt** [comment]
After a bit of looking, it turns out that some of the tracks of the queue did not exist. I had been re-arranging my library last week, and the queue was made prior to that.  So an 803 could be a "1 or more tracks are invalid."   Any way it was interesting and I got it sorted while I was writing the tests for remove_sonos_playlist.  Marking this as closed.
