### ISSUE TITLE
Easier python 2/3 compatible code, six or python-future

### ISSUE THREAD

**Issue by KennethNielsen** [SoCo/SoCo#337]
I current code base quite a lot of ugly hacks (especially in `compat.py`) for bridging the differences between python 2 and 3. This prompted me in #333 to suggest adding `six` to the dependencies. With the following comment:

> (first of, and besides the main content here, I have added six to the requirements. It is a convenience module used by everyone for easier 2 and 3 compatible imports of things that changed name or nature and is written by one of the core maintainers. I suspect we can replace much or our own code that does this, with this more well tested module, but in here, I just use to get a BytesIO object. If you think this must be handled in a separate PR, then let me know)

To this @lawrenceakka replied the following:

> In my view, however, [python-future](http://python-future.org) might be a neater solution. It is also widely-used, but targets only Python2.6 and greater (which is what we need) so it avoids cruft dealing with earlier python versions.  The best part, for me, is that it enables you to write clean and normal python3 code, which will then just work on earlier versions.  In other words, you can just import a module as usual, without having to remember to import from `six.moves`. It also includes more back ported functionality, so we can use more modern constructs without worrying so much.  Have a look at http://python-future.org/faq.html#what-is-the-relationship-between-future-and-six

Since it turned out not to be a no-brainer (adding six) I have moved the discussion here.

**Comment by KennethNielsen** [comment]
@lawrenceakka After looking at python-future, I tend to agree with you that it is probably the way to go. For one thing, it seems to be more about being able to write python 3 code that also works on earlier versions (than the other way around), which I really am a big fan of. It also seems like a well thought through project. There was a few things that initially worried me (which are actually many of the things they do more than six);
 1. When talking about more backports, one might of course worry about the quality of these backports, especially if in the code it looks the functions your're calling is the stdlib, but they have adopted a fair amount of tests from the standard library for that backported functionality, so that makes me a little more at ease.
 2. They also do a few things like shadowing builtin types, which I must admit, still makes a little uneasy. But the main author claims that it is actually "unproblematic" (http://www.youtube.com/watch?v=KOqk8j11aAI&t=10m14s) and in any case I guess we decide for out selves which of the features we want to use.

All in all, I will recommend python-future as well. What do you think @stefankoegl and others?

**Comment by lawrenceakka** [comment]
python-future is also a recommended tool on https://docs.python.org/3/howto/pyporting.html

There is also https://github.com/timothycrosley/pies , but there seems to be nothing to recommend it over python-future

**Comment by ghcs27** [comment]
Is this finished? It would be really neat to have python-future sometimes.

**Comment by polyzen** [comment]
https://pythonclock.org/

**Comment by KennethNielsen** [comment]
@poirier agreed. I would be in favor of discussing deprecating Python 2.7 NOW. We wouldn't be the first project to do that, but so far historically the SoCo user base has seemed to still require Python 2.7 support.

However, since with python-future we would be writing Python 3 code, that might be an more forward pointing way of doing 2 and 3 compat code. I'm still a little uneasy about some of the magic, but maybe it's about time I got over it.

I would be in favor of adding python-future to the requirements, so that we could start doing smarter compatible code.

**Comment by stefankoegl** [comment]
+1 for python-future

**Comment by stefankoegl** [comment]
For 2.7 support: I am not sure of removing of 2.7 support is feasible yet. I'd be open to deprecating it now, with the following implications
* we would still fix any bugs and maintain existing code and features
* we could - if effort for comatability would be too high - add new features that are 3.x only (given that they don't break at import)
* we would line up removal with the official end of maintenance in 2020 (https://pythonclock.org/)

However I think this discussion should probably go into yet another separate issue.

**Comment by KennethNielsen** [comment]
There seems to be consensus for adding future. I guess if someone wants to do a PR that adds it to the dependencies and uses it in one of the modules, that would be the way to go.

@stefankoegl yeah, let's take that discussion in a separate issue, if anyone dares to open it ;)

**Comment by stefankoegl** [comment]
> yeah, let's take that discussion in a separate issue, if anyone dares to open it ;)

#591 :boom:

**Comment by KennethNielsen** [comment]
We will be deprecating python 2.7 shortly, so this is no longer relevant.

**Comment by pwt** [comment]
Python 2.x compatibility code removed as of v0.22.
