### ISSUE TITLE
DidlObject.to_dict() does not return resources as a dict

### ISSUE THREAD

**Issue by dundeemt** [SoCo/SoCo#338]
This is the next phase of Issue #318  DidlObject.to_dict() does not return the resources as a dict.  The resources key of the returned dictionary returns a list of DidlResource objects.

To implement, there will be changes in the to_dict, and from_dict methods.  This will be a change that "could" break someone code since it is changing the returned dictionary.  It will require documentation changes as well.   And, of course, tests.

The idea was forwarded in issue #318 and generally agreed upon, but is awaiting feed back from interested parties.

**Comment by KennethNielsen** [comment]
Just to re-iterate my point. I think ``to_dict`` and ``from_dict`` should aim at working as a middlestep towards serialization, and as such should only return simple types. I therefore consider the current behavior a bug (although a small one) and think that it is ok to fix despite of breaking API.
