### ISSUE TITLE
sonos_playlist how to play it

### ISSUE THREAD

**Issue by thedangler** [SoCo/SoCo#339]
I'm having trouble figuring out how to get the a sonos playlist and play it.
I thought I figured it out when I got the resource uri but when I tried to play it I got a mime-type error.

any help would be appreciated.

**Comment by dundeemt** [comment]
I am fairly new to SoCo and you didn't specify what method you were using. I believe that play_uri expects a uri of a stream-able thing. A song, etc.
I think you need to use add_item_to_sonos_playlist which can be a stream or a DidlContainer (Playlist, album, etc).  If you posted some code, we could better answer your question.

**Comment by lawrenceakka** [comment]
@thedangler We need a bit more to go on please :wink:. Tell us exactly what you tried, and what happened. A python traceback is useful if you are getting errors

**Comment by thedangler** [comment]
Hi sorry , I should have added code. here is some stuff I was trying
import soco
>>> zone_list = list(soco.discover())
>>> speaker = zone_list[0]
>>> sonos_pl = speaker.get_sonos_playlists()
>>> item = sonos_pl.pop()
>>> resource = item.resources
>>> resource
[<DidlResource 'file:///jffs/settings/savedqueues.rsq#0' at 0x10f59ef90>]
>>> re = resource.pop()
>>> re
<DidlResource 'file:///jffs/settings/savedqueues.rsq#0' at 0x10f59ef90>
>>> re.import_uri
>>> re.uri
'file:///jffs/settings/savedqueues.rsq#0'

This is where I started to get lost and couldn't figure out how to play and item in the play list.

I ended up just trying to play the song myself from my local mapped network which path has this
speaker.play_uri('\\matt-pc\music\bonethugs-fistofthemonth.mp3'). But that didn't work
I ended up playing the song then looking up the currently playing song and it gave me back a crazy url: 'http://6fe7bf9d-a4b5-4ebc-86a8-35f9673b58dd.x-udn/WMPNSSv4/1406306825/1_NC0xMDMyMw.mp3'

Anyways I was having trouble needless to say..  

Thanks for the help.

**Comment by lawrenceakka** [comment]
You were close. The next step would be `speaker.add_uri_to_queue(re.uri)`

The whole thing is:
```python

playlist = s.get_sonos_playlists()[1]  # <--- number of playlist here
speaker.add_uri_to_queue(playlist.resources[0].uri)

```

**Comment by KennethNielsen** [comment]
@thedangler I think there is often some misconception about when to use uris and when not to, because we have support for them. But for any normal soco functionality, you really do not need to. Sonos playlists are not really meant to be played as a stream (as you seemed to be trying to do, that is only for radios and others such stream to be played in single play mode without affecting the queue), they are meant to be added to the queue and player from there. When you do that, this whole thing becomes much less magical:

```python
>>> # Provided z is my sonos zone
... 
>>> print(z)
<SoCo object at ip 192.168.0.30>
>>> first_sonos_playlist = z.get_sonos_playlists()[0]
>>> # Asking for sonos playlists, returns to you a SearchResult, which can be iterated over and indexed like a list, so we pull out the first item
...
>>> print(first_sonos_playlist)
<DidlPlaylistContainer 'b'?h Abe'' at 0x7f9105182668>
>>> # So asking for playlists, actually returns playlists, which can be added to the queue
... 
>>> z.get_queue()
Queue(items=[])
>>> # Ok, so it is empty now
... 
>>> z.add_to_queue(first_sonos_playlist)
1
>>> z.get_queue()
Queue(items=[<DidlMusicTrack 'b'Aben (Album Version)'' at 0x7f910515ba20>, <DidlMusicTrack 'b'Elefantens Vuggevise (Album Version)'' at 0x7f910515b358>, <DidlMusicTrack 'b'Sur, Sur, Sur (Album Version)'' at 0x7f910515be48>, <DidlMusicTrack 'b'H?jt P? En Gren En Krage (Album Version)'' at 0x7f910515bb00>, <DidlMusicTrack 'b'Lille F?l, Ved Du Hvad? (Album Version)'' at 0x7f910515b080>, <DidlMusicTrack 'b'Posemandes Bil (Album Version)'' at 0x7f910515bf28>, <DidlMusicTrack 'b'Mester Jacob (Album Version)'' at 0x7f910515bdd8>, <DidlMusicTrack 'b'Jeg Har Fanget Mig En Myg / Lille Peter '' at 0x7f910515bd68>, <DidlMusicTrack 'b'Se Min Kjole (Album Version)'' at 0x7f910515b240>, <DidlMusicTrack 'b'Solen Er S? R?d, Mor (Album Version)'' at 0x7f910515b8d0>, <DidlMusicTrack 'b'Pippi Langstr?mpe (Album Version)'' at 0x7f910515b9e8>, <DidlMusicTrack 'b'Bro, Bro, Brille (Album Version)'' at 0x7f910515b978>, <DidlMusicTrack 'b'H?r Den Lille St?r (Album Version)'' at 0x7f910515bb70>, <DidlMusicTrack 'b'Den Lille Fr?kke Frederik (Album Version'' at 0x7f910518a278>, <DidlMusicTrack 'b'Bjerget I Skoven (Album Version)'' at 0x7f910515b550>, <DidlMusicTrack 'b'Verden Er S? Stor, S? Stor (Album Versio'' at 0x7f910515beb8>, <DidlMusicTrack 'b'Jens Hansens Bondeg?rd (Album Version)'' at 0x7f910515b198>])
>>> # and now just play
... 
```

The entire soco library was built, so that when you deal with music library items and sonos queue and such, you can do it purely as high level object, no need to mess around with the low level stuff like uris and metadata yourself.
