### ISSUE TITLE
New demo - adding a track to the queue WITH METADATA!!

### ISSUE THREAD

**Issue by lawrenceakka** [SoCo/SoCo#347]
I have been experimenting with the new music services code. It looks as though we can now add a track to the queue, given only its id (eg Spotify or Deezer track_id).  All the metadata is filled in automatically.

Please test and comment.

https://gist.github.com/lawrenceakka/2d21dca590b4fa7e3af2

**Comment by zapp42** [comment]
Works fine. Tested with Deezer.

Thanks!!

-Rolf

**Comment by KennethNielsen** [comment]
Hi @lawrenceakka 

This demo was used for inspiration for the work in #455 which has been merged and should be release soon, so I think we can close this one. Feel free to re-open if you think we need it still.
