### ISSUE TITLE
Preferred return structure

### ISSUE THREAD

**Issue by dundeemt** [SoCo/SoCo#348]
working on reorder_sonos_playlist PR, I have 3 values to return from the call. I've been looking at existing code trying to get a feel on whether to return a tuple of values or a dict.  I've found two examples. One returns a tuple of two values (_music_lib_search) tuple(dict, int) and the other returns a dictionary(__get_radio_favorites).

Given that I am new to the project, I am unsure what the current project preference is in this situation.  I am leaning towards returning a dict. It looks cleaner for the caller. The values have assigned names (keys).  Looking for guidance.

On a different topic: update_id.  Most methods just hard code a 0, while the add_item_to_sonos_playlist fetches the current update_id and use that.   How sensitive is update_id?  I am currently mimicing add_item if update_id is set to 0, otherwise I use what is given and then returning the NewUpdateID from reorder_sonos_playlist so if multiple reorders are called in a row, we can save the extra call to fetch the current.  Good / Bad / meaningless?

**Comment by KennethNielsen** [comment]
Hallo @dundeemt 

The radio stuff is a matter of legacy. I think for all cases where (some of) the returned information fits into on of the data structures for a media, then that is the preferred form. I have a PR (#328) to finally make this happen for the radio stuff.

I don't think we have every really decided on a general practice in the project, so this is just my personal view. In general I think it depends on the nature if the returned information:

 * I think, that if the information fits **naturally** in a data structure, then use or make one. See e.g. all the search and browse methods. If not then:
 * If these are all "values" for a single entity of something, then I think a dict would be a good choice.
 * The there are only a few (2-3) and 1 or 2 or these are more support information then actual information (say the number of results, success status etc.) then I would use multiple returns i.e. tuple. As a side note, I really fond of named tuples for these cases (well after I learned about them anyway).

If you can give information about what it is you are returning, then I can give you my personal view on this specific case.

**Comment by dundeemt** [comment]
The method's return signature:
            (int): Change in size between original playlist and the
resulting playlist.
            (int): Length of resulting playlist.
            (int): update_id for next operation.
The  reorder call can not only move tracks, but can be used to delete
tracks from a Sonos playlist. All of the values are status values, except
for update_id. Out of the 3 return results, the softest is the first,
because it can be calculated, in the calling code, by tracking the length
of the original playlist. I included it because it is part of the
underlying call's output.  If am -0 on keeping it but wanted group input
before I just dropped it.


On Thu, Sep 3, 2015 at 3:56 AM, Kenneth Nielsen <notifications@github.com>
wrote:

> Hallo @dundeemt <https://github.com/dundeemt>
>
> The radio stuff is a matter of legacy. I think for all cases where (some
> of) the returned information fits into on of the data structures for a
> media, then that is the preferred form. I have a PR (#328
> <https://github.com/SoCo/SoCo/pull/328>) to finally make this happen for
> the radio stuff.
>
> I don't think we have every really decided on a general practice in the
> project, so this is just my personal view. In general I think it depends on
> the nature if the returned information:
>
>    - I think, that if the information fits *naturally* in a data
>    structure, then use or make one. See e.g. all the search and browse
>    methods. If not then:
>    - If these are all "values" for a single entity of something, then I
>    think a dict would be a good choice.
>    - The there are only a few (2-3) and 1 or 2 or these are more support
>    information then actual information (say the number of results, success
>    status etc.) then I would use multiple returns i.e. tuple. As a side note,
>    I really fond of named tuples for these cases (well after I learned about
>    them anyway).
>
> If you can give information about what it is you are returning, then I can
> give you my personal view on this specific case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SoCo/SoCo/issues/348#issuecomment-137382951>.
>



-- 
Best,

Jeff Hinrichs
dundeemt@gmail.com
402.218.1473

**Comment by lawrenceakka** [comment]
I'd go for a dict I think. Keep it simple, and bear in mind that the idea is to hide complexity and make things pythonic.

In my dreams (when I have been coding too much!) the queue is a list like object (list subclass?) on which one can use slicing, len, iterate etc, e.g. `queue[3]` is the third (fourth?) item, and `queue.extend(an_item)` adds an_item to the end of the queue.  See my comments to similar effect in a different context on #192 .  That would render return values such as the length of the new queue irrelevant. But perhaps that is for another day.

From memory, update ids are a part of the UPnP spec. But it is not clear (to me) how Sonos uses it. See what works!

**Comment by lawrenceakka** [comment]
> In my dreams (when I have been coding too much!) the queue is a list like object (list subclass?) on which one can use slicing, len, iterate etc, e.g. queue[3] is the third (fourth?) item, and queue.extend(an_item) adds an_item to the end of the queue.

Of course, Queue is a list subclass at the moment. What I meant was that adding to the queue could be as simple as q.extend, and removal could be done with `del` or `pop`. This would require further implementation of the python sequence/iter protocols

Lawrence

**Comment by KennethNielsen** [comment]
Unless we can figure out if we need the update id for anything, I think just return the two values. In that case, either of tuple, namedtuple or dict would do the trick for me.

**Comment by KennethNielsen** [comment]
@lawrenceakka sounds like a fun idea

**Comment by dundeemt** [comment]
add_item_to_sonos_playlist goes out of it's way to get the current
update_id (it's an extra call.) I did the same thing if update_id was
passed in as 0.  If you have it, and more reorder ops to do, it saves a
network call.  I can return all three as a dict.  It then can be easily
ignored, if desired.  Sound ok?

On Wed, Sep 9, 2015 at 3:26 AM, Kenneth Nielsen <notifications@github.com>
wrote:

> Unless we can figure out if we need the update id for anything, I think
> just return the two values. In that case, either of tuple, namedtuple or
> dict would do the trick for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SoCo/SoCo/issues/348#issuecomment-138822800>.
>



-- 
Best,

Jeff Hinrichs
dundeemt@gmail.com
402.218.1473

**Comment by KennethNielsen** [comment]
> Souncs ok?

@dundeemt  yup.
