### ISSUE TITLE
.play_uri() doesn't work on Sound Bar if in "TV Mode"

### ISSUE THREAD

**Issue by shah80** [SoCo/SoCo#355]
First - fantastic work - this library is really helpful!

My application functions well with the Play1 and Play3, but not always with the Soundbar. 

If the Soudbar had been in "TV Mode", even if TV is currently off, the call to play_uri() doesn't do anything. Typically, when the soundbar is this mode and I use the controller from my iPhone, it asks me to confirm switching the Audio source from my TV to the controller. I assume a similar issue exits when trying through SoCo but I was unable to find the hook that let me override that confirmation or explicitly switch modes before calling play_uri()

Any ideas on how to work around this?

**Comment by lawrenceakka** [comment]
No sound bar here to test I'm afraid (unless you wish to send one for testing :wink:) . Someone else may be along who can help out.  Otherwise, we need to see the network data passing between your controller and the songs system. Are you able to use wireshark?

**Comment by shah80** [comment]
Yeah - I'll grab a pcap this weekend and upload. 

Did a little more anecdotal testing. Seems like if the TV is on, I can't get it to switch to play a hosted MP3 via play_uri(). If the TV has just turned off, still no dice. However, If i wait hours (like the next morning) it seems to work. 

Will capture some traffic and share.

**Comment by KennethNielsen** [comment]
The question is if we need the traffic here. Asking it to play music, while in a different input, may be one of those kind of undefined situations like asking slaves to perform actions. Therefore, a possible solution would be to modify (and change/rename) the only_on_master decorator to do all sort of different pre-execution checks. It could them, given a particular argument ``not_on_line_in_or_tv``, also do these check and raise an exceptions.

**Comment by dundeemt** [comment]
if you call `device.play()` that will switch the soundbar from tv over to the queue.  I just confirmed this on my own playbar.

```python
import soco
device = soco.SoCo('you_playbar_address_here')
device.play()   # force from playing_tv to playing the queue
device.play_uri(something) # will work now since the soundbar is playing from the queue
device.switch_to_tv()    # back to tv audio
```
play as compared to play_uri, seems to force the input mode change.

**Comment by KennethNielsen** [comment]
Hmm, ok. If you can get a wireshark grab of what the official app does, when it asks you for confirmation and then actually does it, we should hopefully be able to mirror that.

**Comment by KennethNielsen** [comment]
@shah80 Were you able to get a pcap from Wireshark for this issue?

**Comment by KennethNielsen** [comment]
It seems this issue has turned stale. @shah80 if you still have the issue please re-open and we can try and get the Wireshark dumps we need.
