### ISSUE TITLE
Pandora account is not listed in MusicService.get_subscribed_services_names()

### ISSUE THREAD

**Issue by mikix** [SoCo/SoCo#357]
Doing the following:

from soco.music_services import MusicService
MusicService.get_subscribed_services_names()

Gives most of my subscribed services.  It misses TuneIn (which I'd expect).  But it also misses Pandora, which I wouldn't expect.  It seems Pandora is missing from the xml returned by the device.musicServices.ListAvailableServices() call in music_services.py.  I don't know why.

**Comment by lawrenceakka** [comment]
Since Pandora is only in the US, I don't have it to test (and I suspect neither do @KennethNielsen or @stefankoegl ). It looks as thought Pandora is one of the music services which has not been moved over to the new Sonos SMAPI interface, which is why it is not in the XML, and will therefore need some custom code.

Are you able to do any wiresharking for us to capture what happens when you play Pandora on your system?

**Comment by mikix** [comment]
I am able to do that yeah.  Will do so when I have some time.

**Comment by KennethNielsen** [comment]
@lawrenceakka correct, I'm in Denmark.

**Comment by mikix** [comment]
I sat down to capture the Pandora packets, but failed.  :(

I installed wireshark on my Ubuntu laptop.  Set it to capture in promiscuous and monitor modes (so in theory getting everything on the WLAN).  Then used my Android tablet to control my Sonos speakers.  But I couldn't see any packets that looked related.

Do you happen to know of a good way to capture the data?  Maybe a good packet sniffer for Android, so I can capture the data locally on the tablet?

**Comment by lawrenceakka** [comment]
It may depend on which ports you are looking at. Sonos generally communicates on port 1400, so you may need to tell Wireshark to dissect traffic on that port as http. 

I then use a packet display filter as follows to filter out the junk:

`http and (eth.addr_resolved contains "Sonos")  and not (http.request.method == NOTIFY) and not (xml.cdata == UMTracking) and not (xml.cdata == NoReport)`

If that doesn't work, you might try using something like [mitmproxy](mitmproxy.org) in transparent mode `mitmproxy -T --host --tcp HOST` and persuading your tablet that your laptop is in fact the gateway router

**Comment by KennethNielsen** [comment]
This issue is still needs info and is rather old. @mikix please re-open if it is still an issue, and we can try and help you with settings up Wireshark.

**Comment by kberg** [comment]
Am I understanding correctly that interacting with Pandora won't work until someone collects network packets? (And I assume that's just step one.)

**Comment by KennethNielsen** [comment]
@kberg That is correct.
