### ISSUE TITLE
building docs: sphinx issues warning about template classic

### ISSUE THREAD

**Issue by dundeemt** [SoCo/SoCo#361]
`make html` emits the following configuration warning.

WARNING: 'default' html theme has been renamed to 'classic'. Please change your html_theme setting either to the new 'alabaster' default theme, or to 'classic' to keep using the old default.

Also, 3 other minor warnings;
/home/jlh/projects/soco/SoCo/soco/data_structures.py:docstring of soco.data_structures.DidlObject.from_dict:3: WARNING: Inline strong start-string without end-string.

/home/jlh/projects/soco/SoCo/soco/**init**.py:docstring of soco.SoCo.album_artist_display_option:1: WARNING: Inline strong start-string without end-string.

/home/jlh/projects/soco/SoCo/soco/**init**.py:docstring of soco.SoCo.library_updating:1: WARNING: Inline strong start-string without end-string.

I hesitate submitting a PR for these while @lawrenceakka and @KennethNielsen are both making major documentation changes, but wanted to mention them so they could be cleaned up.

**Comment by lawrenceakka** [comment]
Thanks Jeff.  I'll probably pick up on these as I go through the docstrings.  I have discovered that it is now possible in Sphinx's `conf.py` to set `keep_warnings=True` which puts the warnings into the body of the docs themselves, where it is much easier to see them as you work

**Comment by ghcs27** [comment]
This is quite old. Is it still an issue?

**Comment by DPH** [comment]
@dundeemt - not heard back for some time so closing this issue. 
If still a problem please re-open issue.
Cheers David
