### ISSUE TITLE
Build fails on Python 3.5

### ISSUE THREAD

**Issue by stefankoegl** [SoCo/SoCo#364]
Python 3.5 was released recently (see https://docs.python.org/3.5/whatsnew/3.5.html). I've tried to enable builds for 3.5 but they are failing.

According to http://code.activestate.com/lists/python-list/688177/ it seems that pylint relies on some internals that might have changed in 3.5.

**Comment by lawrenceakka** [comment]
Hence the commit message for https://github.com/SoCo/SoCo/commit/34e6323abf96ef5fd96d1a1736266d7d2a6c81d0

:wink:

Travis also supports Pypy3 now, but I haven't tried it.

Lawrence
