### ISSUE TITLE
Docs build is failing

### ISSUE THREAD

**Issue by lawrenceakka** [SoCo/SoCo#369]
After the update to the docs, the build on ReadTheDocs is failing. @stefankoegl please could you add me as a maintainer on the RTD account (username lawrenceakka) and I will try to fix it.

Thanks

Lawrence

**Comment by stefankoegl** [comment]
Are you sure about the username? RTD claims it doesn't exist...

**Comment by lawrenceakka** [comment]
Apparently, it has a capital letter:   Lawrenceakka

Perhaps it is case sensitive.

Thanks a lot

**Comment by stefankoegl** [comment]
Worked, you're now a maintainer!

**Comment by lawrenceakka** [comment]
Thanks Stefan. I'll see if I can work out what's wrong

**Comment by lawrenceakka** [comment]
Seems to have been some internal RTD problem with a database connection.  Working now.
