### ISSUE TITLE
Next Track

### ISSUE THREAD

**Issue by Reborn2** [SoCo/SoCo#375]
Hello

Using SoCo and have a question about commands.

SonosSoCo.get_current_track_info() lets report the informations of the current track where i can read the informations like artist album title, thats all okay

SonosSoCo.get_queue() lets report the playlist as queue but i cant pick out the information about the next track

Is there an command for getting just the information of the next track

Regards

**Comment by Reborn2** [comment]
Hello

Is there somebody who can help me ?

get_next_track_info()

Or something else how i can read it out of the queue ?

Regards

**Comment by Reborn2** [comment]
Hello

Happy Hollidays

Just asking if somebody can helps me with my problem how can i get the informations about the next track?

Regards

**Comment by DPH** [comment]
Hi, Sonos doesn't support a get_next_track_info() type command - therefore SoCo don't!

The best way is to subscribe to the events in Sonos. SoCo caters for this. Then you get information when the current or next track changes. See https://github.com/SoCo/SoCo/blob/master/soco/events.py
the code includes an example that works. 

This basically sits in a loop waiting for events from Sonos - and when they occur you can act on them. The example program just prints out what's received. Works well.
For current next track you are interested in the avTransport events.

hope this helps,
Cheers Daivd

**Comment by Reborn2** [comment]
Hy

Thanks for your answer, by the way i cant resolve the problem.

            from __future__ import print_function
			
            import soco
			
            from soco.events import event_listener

icant get the right commands in the examples to get the avTransport events

Hope you can help me

Regards

**Comment by DPH** [comment]
Hi, I am not clear what is failing.
 below reduced code

```
from __future__ import print_function
try:
    from queue import Empty
except:  # Py2.7
    from Queue import Empty

import soco
from pprint import pprint
from soco.events import event_listener

device = soco.SoCo('192.168.1.71')
print (device.player_name)  # prove we have a valid zone for testing

sub_av = device.avTransport.subscribe()

while True:
    try:
        event = sub_av.events.get(timeout=0.5)
        pprint(event.variables)
    except Empty:
        pass

    except KeyboardInterrupt:  # (control C on windows)
        sub_av.unsubscribe()
        event_listener.stop()
        break
```
If you have SoCo installed and are using python 2.7 or 3.2 or higher this should work. 
If not please explain what is failing and what version of python you are using.
Please confirm you have installed the current vesion of SoCo 
Please advise what platform you are running on.

Cheers David

**Comment by Reborn2** [comment]
Hy

I am running Python 2.7.9 on a enigma 2 Satelite Receiver where i copy the current version of the soco directory into the phyton directory of the receiver


>>> from __future__ import print_function
>>> from Queue import Empty
>>> import soco
>>> from pprint import pprint
>>> from soco.events import event_listener
>>> device = soco.SoCo('192.168.0.84')
>>> print (device.player_name)
Wohnzimmer
>>> sub_av = device.avTransport.subscribe()
>>> ----------------------------------------
Exception happened during processing of request from ('192.168.0.84', 35319)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/lib/python2.7/soco/events.py", line 227, in do_NOTIFY
    variables = parse_event_xml(content)
  File "/usr/lib/python2.7/soco/events.py", line 130, in parse_event_xml
    value = from_didl_string(value)[0]
  File "/usr/lib/python2.7/soco/data_structures.py", line 92, in from_didl_string
    raise DIDLMetadataError("Unknown UPnP class: %s" % item_class)
DIDLMetadataError: Unknown UPnP class: object.container.playlistContainer.sonos-favorite
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.168.0.84', 35320)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/lib/python2.7/soco/events.py", line 227, in do_NOTIFY
    variables = parse_event_xml(content)
  File "/usr/lib/python2.7/soco/events.py", line 130, in parse_event_xml
    value = from_didl_string(value)[0]
  File "/usr/lib/python2.7/soco/data_structures.py", line 92, in from_didl_string
    raise DIDLMetadataError("Unknown UPnP class: %s" % item_class)
DIDLMetadataError: Unknown UPnP class: object.container.playlistContainer.sonos-favorite
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.168.0.84', 35321)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/lib/python2.7/soco/events.py", line 227, in do_NOTIFY
    variables = parse_event_xml(content)
  File "/usr/lib/python2.7/soco/events.py", line 130, in parse_event_xml
    value = from_didl_string(value)[0]
  File "/usr/lib/python2.7/soco/data_structures.py", line 92, in from_didl_string
    raise DIDLMetadataError("Unknown UPnP class: %s" % item_class)
DIDLMetadataError: Unknown UPnP class: object.container.playlistContainer.sonos-favorite
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.168.0.84', 35323)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/lib/python2.7/soco/events.py", line 227, in do_NOTIFY
    variables = parse_event_xml(content)
  File "/usr/lib/python2.7/soco/events.py", line 130, in parse_event_xml
    value = from_didl_string(value)[0]
  File "/usr/lib/python2.7/soco/data_structures.py", line 92, in from_didl_string
    raise DIDLMetadataError("Unknown UPnP class: %s" % item_class)
DIDLMetadataError: Unknown UPnP class: object.container.playlistContainer.sonos-favorite
----------------------------------------
event = sub_av.events.get(timeout=0.5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/Queue.py", line 176, in get
    raise Empty
Queue.Empty
>>> ----------------------------------------
Exception happened during processing of request from ('192.168.0.84', 35327)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/lib/python2.7/soco/events.py", line 227, in do_NOTIFY
    variables = parse_event_xml(content)
  File "/usr/lib/python2.7/soco/events.py", line 130, in parse_event_xml
    value = from_didl_string(value)[0]
  File "/usr/lib/python2.7/soco/data_structures.py", line 92, in from_didl_string
    raise DIDLMetadataError("Unknown UPnP class: %s" % item_class)
DIDLMetadataError: Unknown UPnP class: object.container.playlistContainer.sonos-favorite
----------------------------------------
pprint(event.variables)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'event' is not defined
>>>

So on it seams that someting is not correct or i have made an mistake

Here are the SocketServer.py
[SocketServer.zip](https://github.com/SoCo/SoCo/files/73128/SocketServer.zip)

Here are the BaseHTTPServer.py
[BaseHTTPServer.zip](https://github.com/SoCo/SoCo/files/73136/BaseHTTPServer.zip)

The other Soco Code runs all right

from soco import SoCo
SonosSoCo = SoCo('192.168.0.84')
SonosSoCo.player_name
'Wohnzimmer'
SonosSoCo.get_current_track_info()
{u'album': 'Sehnsucht', u'artist': 'Rammstein', u'title': 'Eifersucht', u'uri': 'x-sonos-spotify:spotify%3atrack%3
.
.
.
</upnp:albumArtURI><dc:title>Eifersucht</dc:title><upnp:class>object.item.audioItem.musicTrack</upnp:class><dc:creator>Rammstein</dc:creator><upnp:album>Sehnsucht</upnp:album></item></DIDL-Lite>'}

This code works fine and i can read the current track informations

Regards

**Comment by DPH** [comment]
Mmmm,
beyond me to analyse - sorry. Some one else with deeper knowledge of the DIDLMetadataError needs to chip in. 

You could try subscribing to the rendering event to see if that works - that would eliminate anything on your side. 

```
from __future__ import print_function
try:
    from queue import Empty
except:  # Py2.7
    from Queue import Empty

import soco
from pprint import pprint
from soco.events import event_listener

device = soco.SoCo('192.168.0.84')
print (device.player_name)
            
sub = device.renderingControl.subscribe()
            
while True:
    try:
        event = sub.events.get(timeout=0.5)
        pprint (event.variables)

    except Empty:
        pass

    except KeyboardInterrupt:
        sub.unsubscribe()
        event_listener.stop()
        break
```

Cheers David

**Comment by Reborn2** [comment]
Hello

Here ist the Log with sub = device.renderingControl.subscribe()

>>> from __future__ import print_function
>>> from Queue import Empty
>>> import soco
>>> from pprint import pprint
>>> from soco.events import event_listener
>>> device = soco.SoCo('192.168.0.84')
>>> print (device.player_name)
Wohnzimmer
>>> sub = device.renderingControl.subscribe()
>>> event = sub.events.get(timeout=0.5)
>>> pprint (event.variables)
{u'bass': '0',
 u'headphone_connected': '0',
 u'loudness': {'Master': '0'},
 u'mute': {'LF': '0', 'Master': '0', 'RF': '0'},
 u'output_fixed': '0',
 u'preset_name_list': 'FactoryDefaults',
 u'sonar_calibration_available': '0',
 u'sonar_enabled': '0',
 u'speaker_size': '-1',
 u'sub_crossover': '0',
 u'sub_enabled': '1',
 u'sub_gain': '0',
 u'sub_polarity': '0',
 u'treble': '0',
 u'volume': {'LF': '100', 'Master': '100', 'RF': '100'}}
>>>

So back to start

Can Somebody help me getting informations about the next track

Regards

**Comment by DPH** [comment]
Great - so subscription works for you - just the avTransport subscription fails. 
It works for me on Windows
Anyone else any ideas why this isn't working for Reborn2

**Comment by robwebset** [comment]
Getting the "Next Track" changed a few Sonos firmwares ago.

Now the "Track Queue" is in order of what will be played, so you can just read the next item off of the queue and that will be the next track played.

Rob

**Comment by Reborn2** [comment]
Hello

mean you SonosSoCo.get_queue() ? Because i dont know how to get only the next track out of the queue to display it.

>>> SonosSoCo.get_queue()
Queue(items=[<DidlMusicTrack 'Hells Bells' at 0xb62232f0L>, <DidlMusicTrack 'Shoot To Thrill' at 0xb6223070L>, <DidlMusicTrack 'What Do You Do For Money Honey' at 0xb6223910L>, <DidlMusicTrack 'Given The Dog A Bone' at 0xb61b6f70L>, <DidlMusicTrack 'Let Me Put My Love Into You' at 0xb61b6f50L>, <DidlMusicTrack 'Back in Black' at 0xb61b6e50L>, <DidlMusicTrack 'You Shook Me All Night Long' at 0xb61b6d10L>, <DidlMusicTrack 'Have A Drink On Me' at 0xb61b6cd0L>, <DidlMusicTrack 'Shake A Leg' at 0xb61b6cf0L>, <DidlMusicTrack 'Rock And Roll Ain't Noise Pollution' at 0xb61b6bf0L>])
>>>

How can i get from this list whats the next Song if the current is What Do You Do For Money Honey

>>> SonosSoCo.get_current_track_info()
{u'album': 'Back in Black', u'artist': 'AC/DC', u'title': 'What Do You Do For Money Honey', u'uri': 'x-file-cifs://192.168.0.100/Harddisk/music/ACDC/Back%20in%20Black/03%20What%20do%20you%20do%20for%20money%20honey.MP3', u'playlist_position': '3', u'duration': '0:03:35', u'position': '0:00:44', u'album_art': u'http://192.168.0.84:1400/getaa?u=x-file-cifs%3a%2f%2f192.168.0.100%2fHarddisk%2fmusic%2fACDC%2fBack%2520in%2520Black%2f03%2520What%2520do%2520you%2520do%2520for%2520money%2520honey.MP3&v=4', u'metadata': '<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="-1" parentID="-1" restricted="true"><res protocolInfo="x-file-cifs:*:audio/mpeg:*" duration="0:03:35">x-file-cifs://192.168.0.100/Harddisk/music/ACDC/Back%20in%20Black/03%20What%20do%20you%20do%20for%20money%20honey.MP3</res><r:streamContent></r:streamContent><upnp:albumArtURI>/getaa?u=x-file-cifs%3a%2f%2f192.168.0.100%2fHarddisk%2fmusic%2fACDC%2fBack%2520in%2520Black%2f03%2520What%2520do%2520you%2520do%2520for%2520money%2520honey.MP3&amp;v=4</upnp:albumArtURI><dc:title>What Do You Do For Money Honey</dc:title><upnp:class>object.item.audioItem.musicTrack</upnp:class><dc:creator>AC/DC</dc:creator><upnp:album>Back in Black</upnp:album><upnp:originalTrackNumber>3</upnp:originalTrackNumber><r:albumArtist>AC/DC</r:albumArtist></item></DIDL-Lite>'}
>>>

self.LsTagTitle = Code_utf8(self.SonosTrack.get("playlist_position",""))

>>> SonosSoCo.get_queue(3)
Queue(items=[<DidlMusicTrack 'Given The Dog A Bone' at 0xb620ee90L>, <DidlMusicTrack 'Let Me Put My Love Into You' at 0xb620ef30L>, <DidlMusicTrack 'Back in Black' at 0xb61b68f0L>, <DidlMusicTrack 'You Shook Me All Night Long' at 0xb61b6e50L>, <DidlMusicTrack 'Have A Drink On Me' at 0xb61b6f70L>, <DidlMusicTrack 'Shake A Leg' at 0xb61b6450L>, <DidlMusicTrack 'Rock And Roll Ain't Noise Pollution' at 0xb61b6fd0L>])
>>>

Okay Given The Dog A Bone is the next Track, my problem still is to read it out of the queue, how can i get it to a variable

or is there another command like SonosSoCo.get_queue()

Regards

**Comment by Reborn2** [comment]
Hello

Have somebody aidea to help me with my problem ?

**Comment by ghcs27** [comment]
You can get an object for the Nth track in the queue via
```python
SoCo.get_queue()[N]
```

**Comment by ghcs27** [comment]
Is this still an issue?

**Comment by DPH** [comment]
@Reborn2  - not heard back for some time so closing this issue. 
If still a problem please re-open issue.
Cheers David
