### ISSUE TITLE
soco.plugins.spotify seems unable to add tracks or albums to queue

### ISSUE THREAD

**Issue by relevitt** [SoCo/SoCo#381]
The following code (imports excluded):
```
device = list(soco.discover())[0].group.coordinator
spotify.Spotify(device).add_album_to_queue(spotify.SpotifyAlbum('spotify:album:44F4vywhlpAhLoar8Jrd9k'))
```

generates the following error:
```
Traceback (most recent call last):
  File "soco_test.py", line 14, in <module>
    spotify.Spotify(device).add_album_to_queue(spotify.SpotifyAlbum('spotify:album:44F4vywhlpAhLoar8Jrd9k'))
  File "/usr/local/lib/python2.7/dist-packages/soco/plugins/spotify.py", line 235, in add_album_to_queue
    return self.soco.add_to_queue(spotify_album)
  File "/usr/local/lib/python2.7/dist-packages/soco/core.py", line 95, in inner_function
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/soco/core.py", line 1586, in add_to_queue
    metadata = to_didl_string(queueable_item)
  File "/usr/local/lib/python2.7/dist-packages/soco/data_structures.py", line 55, in to_didl_string
    didl.append(arg.to_element())
AttributeError: 'SpotifyAlbum' object has no attribute 'to_element'
```

There's a corresponding error when you try to add a track.

**Comment by millzee2000** [comment]
Was the error resolved because I'm having the same issue

**Comment by relevitt** [comment]
No, it wasn't resolved, but I found a gist with a temporary solution, and I think there was also something on Github suggesting the problem might be fixed in the next version of soco. I'll email you the link to the gist when I'm at my PC. I've been using it successfully for loading tracks (one at a time), but I haven't succeeded in loading containers, like albums or spotify radio stations.

 
 
  On Mon, 21 Dec, 2015 at 13:28, millzee2000<notifications@github.com> wrote:   
Was the error resolved because I'm having the same issue

**Comment by relevitt** [comment]
This is the gist ... A quick demo showing how to add a music service track to the queue
|   |
|   |  |   |   |   |   |   |
| A quick demo showing how to add a music service track to...A quick demo showing how to add a music service track to the queue |
|  |
| View on gist.github.com | Preview by Yahoo |
|  |
|   |

**Comment by millzee2000** [comment]
Thanks a lot :+1: it works... well yeah, hopefully there is a fix

**Comment by relevitt** [comment]
Here's a gist for adding a spotify album ... https://gist.github.com/relevitt/21dd577e96bcbd8696e2
