### ISSUE TITLE
get_current_track_info doest not handle same track playing in different zone

### ISSUE THREAD

**Issue by jeantristan** [SoCo/SoCo#389]
I woud like to get current track info in the different zones.

Using the following code:
```
# -*- coding: utf-8 -*-

import soco

zone_list = list(soco.discover())
for zone in zone_list:
    print zone.player_name
    current_track = zone.get_current_track_info()
    print current_track
```

I am currently playing the same track in the 3 different zones (Cuisine, Chambre, Salon) but i have the following output:
````
Cuisine
{u'album': u'', u'artist': u'', u'title': u'', u'uri': 'x-rincon:RINCON_B8E9378A15D801400', u'playlist_position': '1', u'duration': 'NOT_IMPLEMENTED', u'position': 'NOT_IMPLEMENTED', u'album_art': u'', u'metadata': 'NOT_IMPLEMENTED'}
Salon
{u'album': u'', u'artist': u'', u'title': u'', u'uri': 'x-rincon:RINCON_B8E9378A15D801400', u'playlist_position': '1', u'duration': 'NOT_IMPLEMENTED', u'position': 'NOT_IMPLEMENTED', u'album_art': u'', u'metadata': 'NOT_IMPLEMENTED'}
Chambre
{u'album': '...And Then There Was Timo', u'artist': u'Timo R\xe4is\xe4nen', u'title': "Didn't We Almost Have It All", u'uri': 'x-sonos-spotify:spotify%3atrack%3a4PpR9vuebCKehtxLc6VCiT?sid=9&flags=8224&sn=7', u'playlist_position': '3', u'duration': '0:05:41', u'position': '0:02:15', u'album_art': u'http://192.168.1.72:1400/getaa?s=1&u=x-sonos-spotify%3aspotify%253atrack%253a4PpR9vuebCKehtxLc6VCiT%3fsid%3d9%26flags%3d8224%26sn%3d7', u'metadata': u'<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="-1" parentID="-1" restricted="true"><res protocolInfo="sonos.com-spotify:*:audio/x-spotify:*" duration="0:05:41">x-sonos-spotify:spotify%3atrack%3a4PpR9vuebCKehtxLc6VCiT?sid=9&amp;flags=8224&amp;sn=7</res><r:streamContent></r:streamContent><upnp:albumArtURI>/getaa?s=1&amp;u=x-sonos-spotify%3aspotify%253atrack%253a4PpR9vuebCKehtxLc6VCiT%3fsid%3d9%26flags%3d8224%26sn%3d7</upnp:albumArtURI><dc:title>Didn&apos;t We Almost Have It All</dc:title><upnp:class>object.item.audioItem.musicTrack</upnp:class><dc:creator>Timo R\xe4is\xe4nen</dc:creator><upnp:album>...And Then There Was Timo</upnp:album></item></DIDL-Lite>'}
[Finished in 0.318s]
```

Is this the right behavior?
Do I misunderstand some things ?

**Comment by DPH** [comment]
Hi @jeantristan,
your results show that you have the Cuisine and Solon group with another zone - I guess the Chambre.
The uri shows the first 2 zones are playing the same as the sonos Zone with a mac address of B8E9378A15D80 - I guess thats Chambre.

In other words Chambre is a master / coordinator and the other two are slaves.
Only masters have details of what is playing.
Slaves just refer to a master.

You can test if a zone is a co-ordinator with zone.is_coordinator() returns true or false.

Hope this helps,
Shout if you want more help

Cheers Daivd

**Comment by jeantristan** [comment]
Thanks for answer. That was the case.
Is there a method to lookup from slave to master and get the "track info" from the master ?

I would like to get current track info on a regular basis (let's say each 1 minute) on all my zones and backup it. Then, i want to do some prediction based on this data and other data.

**Comment by jeantristan** [comment]
Ok i got it!
```
:attr:`soco.SoCo.group` retrieves the :class:`soco.groups.ZoneGroup` to which the speaker belongs (#132). The group itself has a :attr:`soco.groups.ZoneGroup.member` attribute returning all of its members. Iterating directly over the group is possible as well.
```

**Comment by KennethNielsen** [comment]
@jeantristan Yes, as maybe you found (I can't really tell from you previous post) the group has a "coordinator" property, which return the master zone.

**Comment by KennethNielsen** [comment]
Even though it is closed, this issue got the thinking. We have the "only_on_master" decorator, which should raise an exceptions for methods that should only be called on the master. This is meant to take care more obscure errors, bad or ill-defined output. I wonder if  `get_current_track_info` should get this decorator. It does return information (probably what the slaves were playing before being added to the group) but should we regard this as bad information and prevent it? @DPH ?

**Comment by DPH** [comment]
Hi @KennethNielsen 
it is useful to be able to ```get_current_track_info``` even on slaves as the uri shows it is a slave and what master it is grouped to. I know that info is available in other ways, but other than the URI I think it shows what was previously playing on that zone, which could be a queue you would want to switch to....

The ideal would be to leave it there but to give a warning if it is a slave. Not sure if that is possible. 

Cheers David

**Comment by KennethNielsen** [comment]
@DPH That could be done, but on second thought those warnings should be used lightly. I think maybe a note in the docstring for now.

**Comment by KennethNielsen** [comment]
I have made a small PR for this #390

**Comment by DPH** [comment]
Good approach.
