### ISSUE TITLE
Google Play Music request fails with 'Invalid credentials in request'

### ISSUE THREAD

**Issue by zeppomedio** [SoCo/SoCo#396]
When trying to query through the MusicService class, I'm hitting this when issuing a request:

`MusicServiceException: ('Invalid credentials in request.', 'soap:Client')`

Other, non-authenticated calls to the Play Music backend work, for example `._get_search_prefix_map()`. But calls like `search` and `get_last_update` and `get_metadata` all fail with that error. Looking inside the MusicService object, it does have an `oa_device_id` set, but something in the request to Google Play is failing.

Play Music is configured correctly and works when I'm in the Sonos controller app. Any ideas on how to debug? Since it's an HTTPS call, I can't see what's going on in the SOAP call to the Play backend, so I can't figure out what a "real" call is supposed to look like or what authorization is missing in the call. Thanks in advance.

**Comment by lawrenceakka** [comment]
@zeppomedio 

1) What query are you trying?

2) Does this work:
```python
>>> google=MusicService('Google Play Music')
>>> google.search('tracks')
```

I am aware of some problems currently with passing some of the auth credentials to google, which I am trying to fix

**Comment by zeppomedio** [comment]
thanks for the response @lawrenceakka.

I've narrowed it down to two cases; if the User-Agent is:
```"Linux UPnP/1.0 Sonos/32.10-28251-DaftPunk (MDCR_x86_64_MacBookPro12,1)"```
then I get:
```MusicServiceException: ('Unable to authorize Google Play Music. Please contact Sonos Customer Care.', 'soap:Client')```

If I use:
```"'Linux UPnP/1.0 Sonos/32.10-28251-DaftPunk (MDCR_x86_64_MacBookPro12,1)'"```
(note the inner single-tick quote)

Then the ```getLastUpdate``` and ```search``` calls work, but ```getMetadata``` and ```getMediaURI``` throw:
```MusicServiceException: ('Please update your controller to use Google Play Music.', 'soap:Client')```

Note that for all of these, I'm setting ```oa_device_id``` with an auth token that I got from ```getDeviceAuthToken``` (starts with ```ya29.```), which seems to make the update and search calls work but not the other ones. Any ideas on other things to try? Thanks!

**Comment by zeppomedio** [comment]
And one more detail...if I change the user agent to ```"Linux UPnP/1.0 Sonos/26.10-28251-DaftPunk (ZP120)"``` (downgrading the version to 26) the ```getMetadata``` calls now work! So something must have changed in the protocol above that version?

**Comment by lawrenceakka** [comment]
Google Play is quite sensitive about the UA string - I have come across this before. I'm not sure why the default would not work, which is set in music_services.py to be '"Linux UPnP/1.0 Sonos/99 (ZPS3)"' (again, note the quotes).

And you should not need to set oa_device_id manually - it is all done for you.

This should "just work" (and give you some debugging info)!:
```python
>>> import logging
>>> logging.basicConfig(level=logging.DEBUG)
>>> from soco.music_services import MusicService
>>> google=MusicService("Google Play Music")
>>> google.search('tracks')
```

However, I can see that `get_metadata` and `get_media_uri` are not working, but I'm not sure why. Some experimentation is called for. ...

**Comment by zeppomedio** [comment]
thx @lawrenceakka.

With the inner quotes, I don't think it's getting parsed at all on Google's end; try doing '"test"' as the user-agent and the search and get last update calls still work. Without the inner quotes, it does parse the string on their end, you can see because if you set it to 26. it'll work, but 27. or higher will break.

**Comment by lawrenceakka** [comment]
I agree, the firmware version number has to be 26 to get `get_metadata` to work, and the extra quotes need to be removed.

Even then, `get_media_uri` does not work. I am not too worried about that, however, since there is never any real need to call that method directly – it is designed to be called by the players only, not the controller (see the comments in the SoCo source code for `get_media_uri`. It would not surprise me if there is some form of additional encryption (such as the use of https client certificates) on this method to ensure that only real Sonos devices can access the stream URI.

**Comment by zeppomedio** [comment]
@lawrenceakka agreed, no need for the get media URI call to go through. Using the above I'm able to navigate my library and play all my Google Play content--thanks for the help. Sonos 26 is a somewhat old version so hopefully the integration doesn't break too soon, but I'll close this out in the meantime.
