### ISSUE TITLE
music_services module not installing (0.11.1)

### ISSUE THREAD

**Issue by moochtm** [SoCo/SoCo#400]
In version 0.11.1, the music_services module is not installing.

I think it's just because setup.py doesn't have soco.music_services listed in PACKAGES, but I'm not sure if this is intentional or not.

Best,
Matt

**Comment by lawrenceakka** [comment]
Oops. Thanks - now fixed.

**Comment by moochtm** [comment]
Thanks - fixed for me using pip to install from newly downloaded ZIP.
