### ISSUE TITLE
Spotify Metadata API now end-of-life (0.11.1)

### ISSUE THREAD

**Issue by moochtm** [SoCo/SoCo#401]
The Spotify Metadata API has gone end-of-life, breaking the lookups in the current plugins.spotify module. 

Here's the API URL currently used that's been deprecated by Spotify (line 190, plugins.spotify.py):

`api_lookup_url = 'http://ws.spotify.com/lookup/1/.json'`

...and here's a webpage from Spotify on migrating to the new API... https://developer.spotify.com/web-api/migration-guide/

I'm going to have a go at fixing it, but others will likely be able to do it a whole load faster that me!

Best,
Matt

**Comment by moochtm** [comment]
Well I think I've made some progress, but I'm now hitting an error that I assume must have been lurking in there already:

>   File "/Users/home/GIT/SoCo/soco/data_structures.py", line 66, in to_didl_string
>     didl.append(arg.to_element())
> AttributeError: 'SpotifyTrack' object has no attribute 'to_element'

Any tips would be much appreciated!

Best,
Matt

**Comment by moochtm** [comment]
I see the problem I described in my second comment is the same as already reported in #381. Resolving the original problem can be done purely in plugins.spotify.py, the subsequent problem seems a lot harder to fix.

Here are two gists that provide a workaround in the meantime:

add a track: https://gist.github.com/lawrenceakka/2d21dca590b4fa7e3af2
add an album: https://gist.github.com/lawrenceakka/2d21dca590b4fa7e3af2

Best,
Matt

**Comment by lawrenceakka** [comment]
@moochtm 

I have done a little more investigation about this today. My gist at https://gist.github.com/lawrenceakka/2d21dca590b4fa7e3af2 is now updated to show how to add any track or album from any of the music services (not just Spotify) to the queue, given its id.

I am not very surprised that you have received errors when trying to use the Spotify plugin. I don't think we have looked at it for a while, and much of the new music services code has overtaken it

**Comment by KennethNielsen** [comment]
Given that the new music services code seems to work al right with Spotify, I think we should make a hard deprecation of the old module now. By hard deprecation I mean to substitute all code in the module with raising an exception that explains how to migrate to the new code and that the Spotify specific code plugin will be removed completely in 2 releases. What do you think @lawrenceakka @moochtm ?

Besides from unifying the API it also closes (by deletion of code :P) quite a few bugs.

**Comment by DPH** [comment]
Fully agree

**Comment by stefankoegl** [comment]
+1

Is this also the reason why the test ``test_sonos_uri_from_id`` is currently failing?

**Comment by lawrenceakka** [comment]
Yes, I agree (and have fixed the failing test, which was my fault (as usual))

**Comment by KennethNielsen** [comment]
I'll make the PR. I can also deprecate the Wimp plugin ... and then the old music service data structures (which I think is only used by Wimp) while I am at it.
