### ISSUE TITLE
Get sonos favourites 

### ISSUE THREAD

**Issue by ghcs27** [SoCo/SoCo#402]
I like this project especially because it allows you to use almost every feature of Sonos.
Recently I realized that accessing the sonos favourites is not yet possible with SoCo and found [this](https://groups.google.com/forum/#!topic/python-soco/TILyrsXghbg) workaround on Google Groups.

Integrating this functionality into SoCo shouldn't be a big deal:
- In the music_library.py, the SEARCH_TRANSLATION dict should be extended by the pair
  'sonos_favourites': 'FV:2'
- get_sonos_favourites() should be added as a convenience method for
  get_music_library_information('sonos_favourites')
- this change should be documented in the wiki

Is there some issue I am missing? Otherwise, I will start working on this in a fork.

**Comment by DPH** [comment]
Makes sense to me. I experimented  with the in the past, but never created a pull request.
Look forward to having this functionality.

Cheers Daivd

**Comment by lawrenceakka** [comment]
@ghcs27 There is already a pull request for this at https://github.com/SoCo/SoCo/pull/383 Is that the same thing? If it is, do you think it is complete?

Lawrence

**Comment by ghcs27** [comment]
Sadly, there's a catch: Sonos favorites have their own DIDL class (object.itemobject.item.sonos_favorite) for which there is no corresponding data structure / soco class.
So when from_didl_string() encounters a sonos favorite and wants to determine its class by looking up 'object.itemobject.item.sonos_favorite' in the _DIDL_CLASS_TO_CLASS dict, there's an error.
Apparently a new data structure has to be created for the sonos favorites.

Is someone willing to assist me with this task? I'm new here, but I really want to get this functionality to SoCo.

**Comment by ghcs27** [comment]
Sadly, there's a catch: Sonos favorites have their own DIDL class (object.itemobject.item.sonos_favorite) for which there is no corresponding data structure / soco class.
So when from_didl_string() encounters a sonos favorite and wants to determine its class by looking up 'object.itemobject.item.sonos_favorite' in the _DIDL_CLASS_TO_CLASS dict, there's an error.
Apparently a new data structure has to be created for the sonos favorites.

Is someone willing to assist me with this task? I'm new here, but I really want to get this functionality to SoCo.

**Comment by ghcs27** [comment]
@lawrenceakka Oops, didn't see your comment. It is indeed the same thing, so I'll have a look at it.

**Comment by ghcs27** [comment]
#383 seems to work properly. Some things that I noticed:
- SoCo.get_sonos_favorites() returns a dict, just as SoCo.get_favorite_radio_stations() and
  ...radio_shows() already do. This is opposed to the SoCo.music_library.get_... methods returning a
  SearchResult instance. I would consider this inconsistent. What do you think?
- get_sonos_playlists() is not mentioned in the Methods section of the documentaries and should be
  added

**Comment by DPH** [comment]
What do we need to do to move this forward?
Can we create the required DIDL class? 
Cheers David

**Comment by ghcs27** [comment]
It seems like someone already tried to create this class, but Sonos makes it more difficult than it would have to be: see [data_structures.py](https://github.com/SoCo/SoCo/blob/9bb5f0c3461e877d4252fd0009fd7e972ded0781/soco/data_structures.py#L725-L764).
My suggestion is to merge #383 first (it integrates well with the SoCo.get_favorite_radio_... methods and apparently there is a reason for them to be different from the music library methods) and then work on solving the problem described in the comment linked above.

**Comment by DPH** [comment]
That makes good sense.
Any other thoughts ?

**Comment by ghcs27** [comment]
There is a PR at #328 which adds DIDL classes for radio. Any class for favorites should have a similar structure to them

**Comment by KennethNielsen** [comment]
@ghcs27 moving forward, slowly, but still forward. #383 was merged (but using dicts as output, just to get the new functionality in). I think I will put some focus on #328 now, to finally get that in, which should hopefully get this resolved.

**Comment by ghcs27** [comment]
I have dug a bit further into the favorite metadata and found out that we really can create the required Didl class: see https://github.com/ghcs27/SoCo/tree/favorite_data_structure.

**Comment by ghcs27** [comment]
I have done the required changes, but I require your advice for code style:
In the metadata for a Sonos favorite, there is a `<resMD>` tag which contains the metadata of the item to which the favorite refers. To make its contents accessible to the user, there are two possible implementations:

1. When the DidlFavorite object is created, parse the resMD metadata and make the referenced object available via an attribute which can be accessed and modified. When the favorite it is converted back to XML, call `to_didl_string()` on the referenced object to get the metadata back.
This can be archieved by adding a resource_meta_data property - see https://github.com/ghcs27/SoCo/tree/favorite_data_structure.
2. Keep the resMD metadata in its own attribute. Make it accessible by adding a `reference` property which parses the metadata on read. For this, see https://github.com/ghcs27/SoCo/tree/favorite_data_structure_alt.

Which implementation do you prefer?

**Comment by ghcs27** [comment]
PR for this is here: #478

**Comment by ghcs27** [comment]
PR was merged.
