### ISSUE TITLE
how to ungroup/unjon all Zones

### ISSUE THREAD

**Issue by pixelecho** [SoCo/SoCo#404]
Hey

how is it possible to unjoin/ungroup all Zones. I mean the opposite of party_mode(). when i iterate over all zones and say unjoin() afterwards when i try to play in one zone sometimes i get the error that 

`The method or property "play_from_queue" can only be called/used on the coordinator in a group`

**Comment by DPH** [comment]
Hi, 
have tried to get your error and can't.

If you start with something in the queue in one zone (in my case Office) and group them all together in party mode. 

Then run this code it successfully un-groups them all and plays the first track on the Office zone. 

````
import soco

zones = list(soco.discover())
office = None

for z in zones:
    z.unjoin()

    if z.player_name == "Office":
        office = z


office.play_from_queue(0)
````
Let me see you code to test

Cheers Daivd

**Comment by KennethNielsen** [comment]
@pixelecho did @DPH's answer help you?

**Comment by ghcs27** [comment]
This is quite old and should be closed IMO.

**Comment by KennethNielsen** [comment]
@ghcs27 Agreed. @pixelecho feel free to re-open if this is an issue.
