### ISSUE TITLE
Working on data structures for the music services

### ISSUE THREAD

**Issue by KennethNielsen** [SoCo/SoCo#408]
This is just a heads up, to avoid double work. I am working on a suggestion for data structures for the music services and have made some decent progress on it.

**Comment by stefankoegl** [comment]
Awesome, looking forward to it!

**Comment by KennethNielsen** [comment]
Added the first track and album \o/ (thanks to all the ground work by @lawrenceakka) now polish and then a round of feedback.

**Comment by KennethNielsen** [comment]
There is now a RFC PR in #412

**Comment by KennethNielsen** [comment]
Done long ago
