### ISSUE TITLE
Unknown UPnP class

### ISSUE THREAD

**Issue by codedwrench** [SoCo/SoCo#410]
When subscribed to avTransport and you play a mix from deezer, you get this exception:
soco.exceptions.DIDLMetadataError: Unknown UPnP class: object.item.audioItem.audioBroadcast.#DEFAULT

this is the full error:

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/site-packages/soco/data_structures.py", line 90, in from_didl_string
>     cls = _DIDL_CLASS_TO_CLASS[item_class]
> KeyError: 'object.item.audioItem.audioBroadcast.#DEFAULT'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 628, in process_request_thread
>     self.finish_request(request, client_address)
>   File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 357, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 684, in __init__
>     self.handle()
>   File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/server.py", line 415, in handle
>     self.handle_one_request()
>   File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/server.py", line 403, in handle_one_request
>     method()
>   File "/usr/local/lib/python3.5/site-packages/soco/events.py", line 227, in do_NOTIFY
>     variables = parse_event_xml(content)
>   File "/usr/local/lib/python3.5/site-packages/soco/events.py", line 130, in parse_event_xml
>     value = from_didl_string(value)[0]
>   File "/usr/local/lib/python3.5/site-packages/soco/data_structures.py", line 92, in from_didl_string
>     raise DIDLMetadataError("Unknown UPnP class: %s" % item_class)
> soco.exceptions.DIDLMetadataError: Unknown UPnP class: object.item.audioItem.audioBroadcast.#DEFAULT

nvm I saw the same issue here: https://github.com/SoCo/SoCo/issues/388

**Comment by KennethNielsen** [comment]
Hallo @codedwrench 

Thanks for the bug report.

Yes, this is a known issue. After working on something else, I'll look into the fix mentioned.

Regards Kenneth
