### ISSUE TITLE
snapshot all, then partymode, then restore all

### ISSUE THREAD

**Issue by rudyvan** [SoCo/SoCo#414]
A single zone snapshot/restoring works fine.

I have not found the code or example to snapshot the whole sonos system, use partymode and uriplay a tts sound for all and then restore everything (groups, queues, playstate, ..), just as it was?

Is there a technical reason why this is not foreseen?
Could it be build and work?

**Comment by DPH** [comment]
Hi, I have code that does this, all you do is iterate over each Sonos zone
and snapshot each. Can share example code when I get home after the
weekend. Cheers David

**Comment by rudyvan** [comment]
below is the code that i am currently using:

zones=list(soco.discover()); 
resume={}; 
zone_c=None;
volume=50
try:
  for zone in zones:	
	resume[zone.ip_address]=snapshot.Snapshot(zone); 
        zone.volume=volume
	if zone.ip_address=="192.168.15.96": zone_c=zone # the zone i am using as controller
	zone=zone_c if zone_c is not None else zones[0] # take a zone
	zone.unjoin(); # make sure it can become a partyzone
        zone.partymode(); 
        time.sleep(3)
	zone.volume=volume
	zone.play_uri('http://{}:{}/{}'.format(pi.pi_now.ip,pi.cfg_int(pi.cfg_home,"TTS","sonos_server_port"),"{:}.wav".format(tts_item)))
	time.sleep(2)
        # restore the zone, ?? and the groups??
	for zone in zones: zone.unjoin(); resume[zone.ip_address].restore(fade=0)
except: cfg_pr_stat(["err_sonos",zone.player_name,zone.ip_address]); pass

i also get the following error at the first restore:
  File "/home/pi/PI_Objects.py", line 913, in play
    for zone in zones: zone.unjoin(); resume[zone.ip_address].restore(fade=0)
  File "/usr/local/lib/python3.4/dist-packages/soco/snapshot.py", line 180, in restore
    self.device.bass = self.bass
  File "/usr/local/lib/python3.4/dist-packages/soco/core.py", line 625, in bass
    bass = int(bass)
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by DPH** [comment]
Hi @rudyvan, sorry for delay - was away for the weekend. 

Have looked at your code and you appear to instantiate the snapshot object, but don't create a snapshot. Hence all the values are none. Maybe the names are a bit confusing! 
You need to do:
```
 variable = snapshot.Snapshot(zone)  # instantiate object (camera)
 variable.snapshot() # take the snapshot (push the button!)
```
Have modified your code below to include taking the snapshot, and included a print out of what is captured. Have also changed the import to try and make it clear, but that is only for clarity.
```
import soco
from soco.snapshot import Snapshot as Camera
import time
from pprint import pprint

zones = list(soco.discover())
resume = {}
zone_c = None
volume = 50
try:
    # make a system snapshot
    for zone in zones:
        resume[zone.ip_address] = Camera(zone)
        resume[zone.ip_address].snapshot()

    #     zone.volume = volume
    # if zone.ip_address == "192.168.15.96": zone_c = zone
    # # select coordinating zon, make it unjoin so that it can partymode
    # zone = zone_c if zone_c is not None else zones[0]
    # zone.unjoin();
    # # partymode and play the wav uri
    # zone.partymode();
    # time.sleep(3)  # wait for the partymode to establish
    # zone.volume = volume
    # zone.play_uri('http://{}:{}/{}'.format(x, y, {:}.wav.format(tts_item)))
    # time.sleep(2)  # wait for the uri to play
    # # restore as before, including groups, volumes, playlists, play_state, etc..
    # for zone in zones:
    #     zone.unjoin();  # they were joined by the partymode
    #     resume[zone.ip_address].restore(fade=0)
except: print("err_sonos", zone.player_name, zone.ip_address);

time.sleep(0.5)
print('show results')

for k, v in resume.items():
    print(k, '--------------------------')
    pprint(vars(v))
```
My current code (below) is very similar to yours, except it doesn't group the zones into party mode as it was taking too long! I am working on speeding that up. i use this as my doorbell. I have also recently added a Sonos sound bar, and it has trouble recovering if the soundbar is the master - need to investigate, at present I just skip it.

```
import time
import soco
from soco.snapshot import Snapshot

class SonosInterface(object):
    def __init__(self):
        self.zones = None
        while not self.zones:
            self.zones = soco.discover(timeout=3)

    def doorbell(self):
        for zone in self.zones:
            zone.snap = Snapshot(zone)
            zone.snap.snapshot()
            print('found zone')
            print(zone.snap.volume, zone.is_coordinator, zone.is_playing_tv,  zone.player_name)

        coordinators = [zone for zone in self.zones if zone.is_coordinator and not zone.is_playing_tv]

        print coordinators

        for zone_c in coordinators:
            trans_state = zone_c.get_current_transport_info()
            print(zone_c.player_name, trans_state)
            if trans_state['current_transport_state'] == 'PLAYING':
                zone_c.pause()

        for zone in self.zones:
            if zone.is_playing_tv:
                zone.volume = 0
            else:
                zone.volume = 40

        for zone_c in coordinators:
            print('Play doorbell', zone_c.player_name)
            zone_c.play_uri('x-file-cifs://DoorPi/DoorPiPublic/doorbell/sounds/Tbell.mp3')

        time.sleep(14)
        for zone in self.zones:
            if zone.is_playing_tv:
                pass
            else:
                print('restoring {}'.format(zone))
                zone.snap.restore(fade=True)
```

Hope this helps.  Shout if you have any more problems.
What are you using yours for?
Regards Daivd

**Comment by rudyvan** [comment]
I adapted my code with your example and it works now!

To answer your question, I play sonos messages as someone rings the doorbell but also when the irrigation start/completes, homecoming of one of the member through bluetooth low energy beacons or when some event requires attention such as incoming post, rain water level beyond high, etc..

I have 9 zones in the house and i considered party mode as the sound then is  synchronised, now there is echo.  I also have a soundbar and i copied your is_playing_tv exception.
Thanks, very nice work!
Rudy
