### ISSUE TITLE
Universal attribute for is_playing_...

### ISSUE THREAD

**Issue by ghcs27** [SoCo/SoCo#415]
Having seperate methods for checking from which source music comes from seems redundant to me. In [this gist](https://gist.github.com/ghcs27/6096244f1eb6afae9beba157bb16f1be) I have written a possible alternative, which is one attribute that gives a string denoting the current music source.
Are there any possible inputs I am missing? Should I return None (of type NoneType) or "NONE" (of type String) if there is no music? Feedback is appreciated.
Another option would be incorporating this into the get_current_track_info() method - what do you think?

**Comment by KennethNielsen** [comment]
I would be in favor of adding such a property, but I fear that removing the old ones will break too much code to be justified. So if we do add it, let's make it an extra one.

**Comment by mountainsandcode** [comment]
We could add information about whether Sonos is currently playing from Airplay2 or not as well in this property!
