### ISSUE TITLE
Mute() results in error - TypeError: 'bool' object is not callable

### ISSUE THREAD

**Issue by cstanding** [SoCo/SoCo#416]
>>> from soco import SoCo
>>> sonos=SoCo('192.168.0.110')
>>> sonos.mute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'bool' object is not callable

Should return 0 or 1 for the current mute state.

**Comment by DPH** [comment]
Hi,
mute is a property you therefore need to set it:
sonos.mute = True 
(or False)

Cheers David

**Comment by cstanding** [comment]
Thanks!  That works.
Docs on main page are wrong :)

**Comment by DPH** [comment]
You should have a close issue button below where you type text to comment.
Only you can close it....
Cheers Daivd

**Comment by KennethNielsen** [comment]
I fixed the doc. Thanks for reporting this.
