### ISSUE TITLE
SoCo can still find my unplugged speaker

### ISSUE THREAD

**Issue by chaocharleswang** [SoCo/SoCo#426]
Hi,

I have multiple speakers. I just unplugged one of them.
Then I use SoCo to discover my speakers again.
The unplugged speaker is still in the result list.

I checked the source code. I think SoCo use "ZoneGroupTopology" service to discover the speakers.
Is it possible to update the service to remove the unplugged speaker from the result list?

Thanks a lot!

**Comment by KennethNielsen** [comment]
Hi @chaocharleswang 

Which method are you using?

**Comment by chaocharleswang** [comment]
discover() -> GetZoneGroupState

**Comment by KennethNielsen** [comment]
I'm unsure what you mean. Can you post example code?

**Comment by KennethNielsen** [comment]
Closing due to missing feedback.

@chaocharleswang fell free to re-open and add the missing information.
