### ISSUE TITLE
Time for a release?

### ISSUE THREAD

**Issue by DamienCassou** [SoCo/SoCo#429]
Hi,

the latest release is quite old (0.11.1 from June 2015). What about releasing a new version? This is useful for packaging in a linux distribution (what I'm doing right now).

Thanks

**Comment by KennethNielsen** [comment]
Hi @DamienCassou 

Thanks for your interest in SoCo. We are planning a release very soon. See the discussion at #315.

I'll close this as a sort of duplicate, but feel free to chime in on that issue.

Regards Kenneth
