### ISSUE TITLE
Play mp3 livestream

### ISSUE THREAD

**Issue by Sabbertran** [SoCo/SoCo#434]
I'd like to play a mp3 livestream like
http://mp3.radiobielefeld.c.nmdn.net/ps-radiobielefeld/livestream.mp3
or http://edge.live.mp3.mdn.newmedia.nacamar.net/radiobielefeld/livestream.mp3
but when using play_uri I get no error and the sonos controller says that the track is not encoded right.

I hope that someone can help me.

Greetings,
Sabbertran

**Comment by KennethNielsen** [comment]
Hallo @Sabbertran 

Can you please provide a complete minimal code example of the failure?

**Comment by Sabbertran** [comment]
Hey,
this is the code which gave me the error in the sonos controller:

`#!/usr/bin/env python

from soco import SoCo
import soco

speaker = SoCo('192.168.178.38')
speaker.play_uri("http://mp3.radiobielefeld.c.nmdn.net/ps-radiobielefeld/livestream.mp3")`

**Comment by Sabbertran** [comment]
Also, just to clarify, by sonos controller I mean the windows application that comes for any sonos speaker, not SoCo

**Comment by KennethNielsen** [comment]
Ahh. So what you are talking about is that setting a uri like that, produces an error in the Sonos controller. But does is play? Also full text of the error from the controller would be helpful.

**Comment by Sabbertran** [comment]
No, it doesn't play.
The error message say "Wiedergabe von 'livestream.mp3' nicht möglich - Titel ist nicht korrekt codiert."
which translates to "Playback of 'livestream.mp3' not possible - title is not encoded correctly.".

**Comment by KennethNielsen** [comment]
Hmm, that sounds wierd. Can you try and actually provide it with a title, like so:
```python
speaker.play_uri("http://mp3.radiobielefeld.c.nmdn.net/ps-radiobielefeld/livestream.mp3", title="testtitle")
```

**Comment by Sabbertran** [comment]
Still the same error when providing it with a title

**Comment by macpit** [comment]
I have the same issue.

`import soco
device = soco.discovery.any_soco()
zone = device.group.coordinator
zone.play_uri('http://rundfunk.ice.infomaniak.ch/rundfunk-192.mp3', title='Rundfunk FM')`

**Comment by KennethNielsen** [comment]
I can confirm this issue and it has also been raise in the SoCo google group (https://groups.google.com/forum/#!topic/python-soco/cktqjwY_8_Q). @DPH has agreed to look into it, so we will see what he comes up with.

**Comment by DPH** [comment]
have discovered Sonos calls radio stations using a prefix of 'x-rincon-mp3radio://'
So it works if you change http:// to the above.

example:
````
speaker.play_uri("x-rincon-mp3radio://mp3.radiobielefeld.c.nmdn.net/ps-radiobielefeld/livestream.mp3", title="testtitle")
````

Cheers Daivd

**Comment by DPH** [comment]
@KennethNielsen any thoughts is we can do the 'http//:' switch to 'x-rincon-mp3radio://' in SoCo or if it is more complex than that. I can see lots of people hitting this issue so would be nice to automate it as Sonos does when you add a radio station. If not sensible to change automatically then maybe include in documentation. Welcome your thoughts

Cheers David

**Comment by KennethNielsen** [comment]
@DPH No, I think we should do the conversion in the play_uri method. This method has always sort of been a "work around" to provide a more direct route to get to play a uri than to add it first, so I think it should continue to do that i.e. actually playing a uri.

Extra info. After I saw that you solved it in the google group, I also tested it in a m3u type from a secure uri (https) and that works as well. Since it would not be unreasonable to think that maybe a secure uri would be handled differently. But that works as well \o/.

Do you want to make a PR out of it or should I?

Regards Kenneth

**Comment by DPH** [comment]
@KennethNielsen maybe we need a play_stream which does the conversion and then calls play_uri. 
I use play_uri to call local files and would not want that converted eg:
```
play_uri('x-file-cifs://server/sounds/MyNiceRing.mp3')
```
also the snapshot class in SoCo uses play_uri to restore whatever uri was playing before.

Maybe play_uri is the raw 'play what it is given', and there are other methods that call play_uri and do appropriate conversion? (e.g. play_stream, play_file etc. Thoughts.

Happy you do a PR as I still have trouble with GitHub but am slowly learning!
Cheers David

**Comment by KennethNielsen** [comment]
@DPH: I actually already implemented a play_stream in a PR, but for a different purpose. In any case, I don't think we need it here. I would simply only convert the URI if it is a http(s) variety, maybe even with a keyword arg to optionally disable the conversion altogether. Something along the lines of:

```python
    def play_uri(self, uri, title='', meta='', convert_internet_uris=True):
        ...
        for prefix in ('http://', 'https://'):
            if uri.startswith(prefix) and convert_internet_uris:
                uri = uri.replace(prefix, 'x-rincon-mp3radio://', count=1)
        ...
```

What do you think?

BTW. I'd be happy to "tutor" you with regards to making the PR, if you are interested.

PS: The prefix specifically mentions mp3. Has anyone tried this approach with one of the other file formats that Sonos support (AAC or WMA)?

**Comment by DPH** [comment]
@KennethNielsen: your approach makes good sense. 

Looked for AAC / WMA streams to test but hard to find. most seem to use mp3 / m3u.
Also Tune-in which is the main source for Sonos only supports mp3 across all platforms but AAC on its mobile apps! See [http://help.tunein.com/customer/portal/articles/944944-what-are-the-preferred-streaming-formats-on-tunein-](url)

I think we are safe to go with this and see if anyone raises problems with other streams. 

Thank you for the tutor offer. Would like to do that, but think we should get this one in quickly. What do you think? Will email you separately so I can get my set up right for next one.

Regards David

**Comment by Sabbertran** [comment]
Thanks for figuring this out, guys.
Looking forward to the update in the new release.
