### ISSUE TITLE
Release notes for 0.13

### ISSUE THREAD

**Issue by KennethNielsen** [SoCo/SoCo#440]
For every change that goes into the 0.13 release. Please make a small description here, link to the PR (any issues) and mention whether it is a bug fix or not.

**Comment by bjarniivarsson** [comment]
https://github.com/SoCo/SoCo/pull/437
- Fixes an issue where restarting an application that had subscribed to events sometimes causes an error when the events are delivered to the new instance.
- Fixes an issue where multiple threads trying to subscribe to events in parallel would sometimes cause SoCo to attempt to create multiple event listener servers and fail on socket.bind().

**Comment by bjarniivarsson** [comment]
https://github.com/SoCo/SoCo/pull/438
- Fixes an issue where SoCo would not recognize object.container.playlistContainer.sonos-favorite when receiving events.

**Comment by KennethNielsen** [comment]
#443 
 * Fixes a bug in play_uri where it would not play a http og https prefixed radio stream due to a change in the Sonos API (issue #434). This change fixes it by replacing the two http type prefixes with Sonos' x-rincon-mp3radio:// prefix.

**Comment by KennethNielsen** [comment]
1ee005a8931e6c18d803ab4d589e6f45544ddb1c
 * Fixes an exception being raised on Windows with discover. The error was caused by socket.getsockname raising an exception on Windows with and unconnected unbound socket. Fixed by now simply logging the sockets.

**Comment by lawrenceakka** [comment]
#444 The IP address used by the events listener can be configured

**Comment by christiandt** [comment]
- #421 Add support for night mode on devices supporting the feature.
- #422 Add support for dialog mode on devices supporting the feature.
- Add NotSupportedException when mode is not supported by the device.

**Comment by KennethNielsen** [comment]
* #455 Add queue-able data structures for the music service items (see #455 for details)

**Comment by ghcs27** [comment]
- #470 Add a method for queueing multiple items with a single request.

**Comment by KennethNielsen** [comment]
* #481 Added a FAQ section to the docs with play_uri and play local files answers

**Comment by KennethNielsen** [comment]
* #484 A few queue related micro examples was added to the examples page in the docs

**Comment by ghcs27** [comment]
- #471 Enhance `add_to_queue()` to with optional position argument

**Comment by KennethNielsen** [comment]
* #487 Added by_name function to discovery to be able to get a device by player_name

**Comment by DPH** [comment]
- #489 Snapshot: added documentation about using only once and fixed Python 3 potential issue

**Comment by DPH** [comment]
- #493 Added FAQ, documentation and two examples to explain using SoCo's Snapshot  function.

**Comment by DPH** [comment]
- #491 allow choice of how to play streams in play_uri (over-ride Sonos default with force_radio=True).

**Comment by ghcs27** [comment]
- #506 Added ramp_to_volume() method to smoothly change the volume

**Comment by DPH** [comment]
- #529  Change to use SoCo method to determine coordinator in Snapshot (this is consistent and should prevent odd errors #519)

**Comment by DPH** [comment]
#530 Prevent error when queue started from Alexa and using snapshot. Currently there is no was to restart a cloud queue from SoCo, this PR just prevents Snapshot causing an error. (#521)
