### ISSUE TITLE
soco.seek('hh:mm:ss') crash

### ISSUE THREAD

**Issue by firecold100** [SoCo/SoCo#441]
Hi!

I've been using your controller for this amazing speakers and is quite good! 

I don't know if this is an Issue or is merely something that is not implemented yet
Anyway, when I play a local archive with the script provided in:
/examples/play_local_files/play_local_files.py 

It gives me an error saying:

> Unable to play '<mp3_name>.mp3' - the song is not encoded correctly.

Of course, that error is from the android application and not from your controller.

So... I wonder If there's a way to seek on local files with this controller.

**Comment by DPH** [comment]
Hi @firecold100,
I have not tried the script you point to, but you can play and seek on a local file with the basic SoCo. 
```
import soco
zone = soco.SoCo('192.168.0.68')

zone.play_uri('x-file-cifs://server/sounds/MyNiceTune.mp3', start=False)
zone.seek('00:00:03')
zone.play()
```
Not clear if this answers your question or it is more specific to the script by @KennethNielsen 

Cheers Daivd

**Comment by KennethNielsen** [comment]
Hi @firecold100 and thanks for reporting.

@DPH I think there is a little confusion as to the term "local". You are referring files on the local network, but @firecold100 is talking about files on the local machine (not shared on the network). The example is basically a hack around that, which just opens up a local web server that serves the files on the network (probably a horrible idea by the way, but people kept asking for it, so it is there to show just a proof on concept).

I suspect that something has changed in the metadata passed between the controllers and the devices, and the it may be related to #434 as well and therefore I think it may be worth it to save this one to after #434.

**Comment by KennethNielsen** [comment]
Just checked with the example. It tries to add the files with a http prefix, so this is almost certainly related to #434, but of course I did not include a fix for this in the PR that fixes #434, although it should be possible to fix with the exact same kind of fix. I will look at it soon, hopefully over the weekend.

**Comment by ghcs27** [comment]
This is old and can probably be closed.

**Comment by ghcs27** [comment]
Please reopen if it hasn't been resolved.
