### ISSUE TITLE
SoCo on Windows - discovery does not work

### ISSUE THREAD

**Issue by jrathert** [SoCo/SoCo#445]
Hi,

maybe I am the only one using SoCo on Windows (7/10), but I cannot really believe that ;-). I use Linux as well as Windows - and on my machines (being Windows 7 or Windows 10, both 64bit versions) the `soco.discover()` call fails:

```
C:\Dev\Python35-2>python.exe
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import soco
>>> print(soco.discover())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Dev\Python\Python35-32\lib\site-packages\soco\discovery.py", line 123, in discover
    list(s.getsockname()[0] for s in _sockets))
  File "C:\Dev\Python\Python35-32\lib\site-packages\soco\discovery.py", line 123, in <genexpr>
    list(s.getsockname()[0] for s in _sockets))
OSError: [WinError 10022] An invalid argument was supplied
>>>
```

Funny enough, it is just a `_LOG` call that fails, so if you remove / comment out line 122+123 in `discovery.py`, everything works (although discovery is quite unstable with Windows - sometimes it works, sometimes not, but that is another story). I could not find a better way as removing the call yet.

BTW: I would love to participate in discussions in the SoCo Google Group, but someone needs to accept my request to join the group. Who can do that?

Thanks

  Jonas

**Comment by KennethNielsen** [comment]
Hi @jrathert 

From what I could gather from the log, that line was added fairly recently, so it is possible that you are just the first one who has tried it in Windows. Which version of SoCo are you using (soco.__version__)?

I guess the argument for the log could be simply be created with a try except, but I don't quite understand why it fails.

Regarding the SoCo Google Group I wasn't actually aware that someone need to accept a request. @stefankoegl @petteraas @DPH do you know who owns it?

**Comment by KennethNielsen** [comment]
Ah, this thread (https://bugs.python.org/issue1049) seems to explain the error message.

**Comment by DPH** [comment]
I looked at Google groups for SoCo and found:
```
Access:
Anyone can view content.
Anyone can apply to join.
Only members can post.
Only members can view the list of members.
```
on this page [
https://groups.google.com/forum/#!aboutgroup/python-soco
](url) it has a link to contact the owner. 

I am not aware I ever did but I guess I must have. 
Every one is welcome to join and comment.  The more help we have the better.

Regards David

**Comment by KennethNielsen** [comment]
@DPH thank. I found it on the members list https://groups.google.com/forum/#!members/python-soco. It is Stefan that is the owner. @stefankoegl can you upgrade a few of us to admins?

**Comment by jrathert** [comment]
Hi,

@KennethNielsen : I use version 0.12 and also tried by direct pulling via git. Adding a `try...except` for a call to `_LOG` to me seemed a bit too much, so I simply made a comment out of the lines to use it on Windows. I tried to find better approaches, but failed, as all of this is not too system-independent...

@DPH : Of course, google groups have a simple "subscribe to this group" link once you enter the page which I klicked and which is now gone, as I am waiting to get approved. So I guess the owner is already informed to give me access. But who is the owner?

**Comment by jrathert** [comment]
Thanks. I think we can close this issue, correct? (If someone just reviews/changes the lines I mentioned - once I get used to github, I hope to fix such things myself ;-).

**Comment by KennethNielsen** [comment]
@jrathert Agreed that a try except seems a bit excessive. I think we should keep the issue open until it is fixed.

**Comment by KennethNielsen** [comment]
Fixed in master. Thanks for reporting it.
