### ISSUE TITLE
UPnP Error 806 on Google Play Music

### ISSUE THREAD

**Issue by samsullivan** [SoCo/SoCo#446]
I get this `soco.exceptions.SoCoUPnPException` every time I try to `get_metadata()` or `search()` using the Google Play Music service. Previously, I was getting an invalid credentials error so I know that my `get_google_play_music_account()` logic is working.

Here's what I'm trying:

```
from soco.music_services.accounts import Account
from soco.music_services.music_service import MusicService


def get_google_play_music_account():
    for key, account in Account.get_accounts().iteritems():
        if account.service_type == '13575':
            return account
    raise Exception

google = MusicService('Google Play Music', get_google_play_music_account())
google.get_metadata()
```

And here's the traceback:

```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    google.get_metadata()
  File "/usr/local/lib/python2.7/dist-packages/soco/music_services/music_service.py", line 682, in get_metadata
    ('recursive', 1 if recursive else 0)]
  File "/usr/local/lib/python2.7/dist-packages/soco/music_services/music_service.py", line 146, in call
    soap_header=self.get_soap_header(),
  File "/usr/local/lib/python2.7/dist-packages/soco/music_services/music_service.py", line 111, in get_soap_header
    ('Username', music_service.account.username)
  File "/usr/local/lib/python2.7/dist-packages/soco/services.py", line 181, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/soco/services.py", line 408, in send_command
    self.handle_upnp_error(response.text)
  File "/usr/local/lib/python2.7/dist-packages/soco/services.py", line 469, in handle_upnp_error
    error_xml=xml_error
soco.exceptions.SoCoUPnPException: UPnP Error 806 received:  from 192.168.1.107
```

**Comment by samsullivan** [comment]
I decided to do a couple things of testing, to no avail:

1. use the master branch
2. use Python 3 (this fixed some occasional SNI errors I was having)
3. wipe Sonos Music Services, just add Google Play, and loop through all accounts.

Here's some basic results:

```
No account: MusicServiceException -- ('Invalid credentials in request.', 'soap:Client')
Service Type 65031: SoCoUPnPException -- UPnP Error 806 received:  from 192.168.1.41
Service Type 38663: MusicServiceException -- ('Invalid credentials in request.', 'soap:Client')
```

I find it weird that, after resetting my Sonos Music Services, the `service_type` seems to have changed...

**Comment by KennethNielsen** [comment]
Hallo @samsullivan and thanks for reporting this.

It seems that there has been some fundamental change in how authentication with music services take place, that is affecting all music services that use a certain kind of authentication.

A guess (but purely a guess) at why the service_type has changed is that the first error that describe lets the client know, that it needs to change authentication type and the second error is because that authentication type has not been properly implemented SoCo.

Do you know how to use the Wireshark tool to capture network traffic?

**Comment by samsullivan** [comment]
@KennethNielsen thanks for confirming I'm not crazy. I'm excited to get Google Home <-> Sonos integration setup whenever we can get this resolved.

I have not used Wireshark before, but I have no doubt I'd be able to get it up and running some time this week and take a look at what my Sonos script is doing and where/how it fails.

What should I be looking for and reporting back?

**Comment by KennethNielsen** [comment]
Thanks. I (or someone else) will get back to you if it becomes necessary.

**Comment by KennethNielsen** [comment]
Closing this issue in favor of #557 to gather information in one place.
