### ISSUE TITLE
UPnP Error 701 received

### ISSUE THREAD

**Issue by ZyberSE** [SoCo/SoCo#454]
Hi,

I'm using SoCo in Home-Assistant and have been seeing some errors in the log lately.

Python release (python3 --version): 3.4.2
Version of SoCo is unclear, how do I check that? The installation is about 2 weeks old so the library should be resent.

- UPnP Error 701 received: Transition not available
- Error doing job: Future exception was never retrieved

Here are the logs:

```bash
soco.exceptions.SoCoUPnPException: UPnP Error 701 received: Transition not available from 40.0.0.47
16-12-08 08:13:15 soco.services: UPnP Error 701 received: Transition not available from 40.0.0.48
Traceback (most recent call last):
  File "/home/hass/.homeassistant/deps/soco/services.py", line 408, in send_command
    self.handle_upnp_error(response.text)
  File "/home/hass/.homeassistant/deps/soco/services.py", line 469, in handle_upnp_error
    error_xml=xml_error
soco.exceptions.SoCoUPnPException: UPnP Error 701 received: Transition not available from 40.0.0.48
16-12-08 08:19:30 homeassistant.core: Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/core.py", line 1045, in execute_service
    service_handler.func(service_call)
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/components/media_player/__init__.py", line 324, in media_player_service_handler
    getattr(player, method)()
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/components/media_player/sonos.py", line 830, in turn_off
    self.media_pause()
  File "/srv/hass/hass_venv/lib/python3.4/site-packages/homeassistant/components/media_player/sonos.py", line 844, in media_pause
    self._player.pause()
  File "/home/hass/.homeassistant/deps/soco/core.py", line 104, in inner_function
    return function(self, *args, **kwargs)
  File "/home/hass/.homeassistant/deps/soco/core.py", line 501, in pause
    ('Speed', 1)
  File "/home/hass/.homeassistant/deps/soco/services.py", line 181, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/home/hass/.homeassistant/deps/soco/services.py", line 408, in send_command
    self.handle_upnp_error(response.text)
  File "/home/hass/.homeassistant/deps/soco/services.py", line 469, in handle_upnp_error
    error_xml=xml_error
```

**Additional info:**

**Comment by ghcs27** [comment]
Error 701 is thrown if in the current state, pausing the player is not possible (e.g. if there is no music). It is returned by the Sonos speakers themselves, SoCo just converts it into a Python exception.
The solutions for your problem might be observing what state the player is in and prohibiting execution of pause() if there is nothing to pause, or just silently handling the exception (it probably does no harm to ignore it).

**Comment by KennethNielsen** [comment]
@ZyberSE you can find the soco version by doing:

```python
import soco
soco.__version__
```
Are you satisfied with the answer you git from @ghcs27 regarding the origin of the exception?

@ghcs27 I can see in the source code that it is documented that e.g. play and pause may raise SoCoUPnPException, but it does not mention anything about the error code. It may be useful to add a little something to the docstrings about the most common sources of failures and about more acceptable sources of failures, such as this one. What do you think.

**Comment by ghcs27** [comment]
I would support adding UPnP error codes and their meaning to the docs. The basic meaning of the error codes can be found on page 89 of the [UPnP specs](http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.1.pdf), but some codes probably have a Sonos specific meaning.

**Comment by KennethNielsen** [comment]
@ghcs27 It might be that we should add some sort of list (probably not exhaustive though, but with links) somewhere in the docs, but my question was more whether it would be a good idea to explain one or 2 particularly relevant error codes in the doc string for methods like e.g. pause. Thoughts?

**Comment by mediaguycouk** [comment]
I had this error on a snapshot restore(). I mention this as your comment suggests that I should be checking if the Sonos is in a state to be played, but I don't think I have that option with a snapshot.

```snap = Snapshot(deviceco)
snap.snapshot()
deviceco.play_uri(alert_uri)
time.sleep(10)
snap.restore()
```

**Comment by DPH** [comment]
Hi @mediaguycouk,
am pretty sure as has been said you are tying to pause() when there is nothing to pause. 
Interestingly is you use stop() this doesn't throw an error.

If you want to know what commands you can use then the following code will tell you. 
```
import soco
s = soco.SoCo('192.168.1.68')
print(s.avTransport.GetCurrentTransportActions([('InstanceID', 0)]))
```
However you can probably catch it by seeing if it was playing before you pause() it.
```get_current_transport_info()['current_transport_state']``` tells you if it was playing - if not no need to stop / pause it.

Hope this helps,
Cheers David

**Comment by ghcs27** [comment]
Closing this in favor of #584 and #585.
