### ISSUE TITLE
The readme example is not working for me

### ISSUE THREAD

**Issue by ersiko** [SoCo/SoCo#457]
I'm following the example but after I follow the steps, my speaker doesn't play anything
```
Python 3.5.2+ (default, Sep 22 2016, 12:18:14) 
[GCC 6.2.0 20160927] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import soco
>>> speakers = soco.discover()
>>> speaker = speakers.pop()
>>> speaker
SoCo("10.10.11.104")
>>> speaker.play_uri('http://archive.org/download/TenD2005-07-16.flac16/TenD2005-07-16t10Wonderboy_64kb.mp3')
>>> track = speaker.get_current_track_info()
>>> track['duration']
'0:00:00'
>>> track
{'duration': '0:00:00', 'uri': 'http://archive.org/download/TenD2005-07-16.flac16/TenD2005-07-16t10Wonderboy_64kb.mp3', 'album': '', 'artist': '', 'position': '0:00:00', 'metadata': '<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="-1" parentID="-1" restricted="true"><res protocolInfo="http-get:*:application/octet-stream:*">http://archive.org/download/TenD2005-07-16.flac16/TenD2005-07-16t10Wonderboy_64kb.mp3</res><r:streamContent></r:streamContent><dc:title>TenD2005-07-16t10Wonderboy_64kb.mp3</dc:title><upnp:class>object.item</upnp:class></item></DIDL-Lite>', 'title': 'TenD2005-07-16t10Wonderboy_64kb.mp3', 'album_art': '', 'playlist_position': '1'}
>>> 

```

It says "duration: 0". And when I try to play on the mobile app it says "Unable to play 'TenD2005-07-16.flac16/TenD2005-07-16t10Wonderboy_64kb.mp3', the file can not be found".

The file is available, I can play it on my browser... Am I doing something wrong?

**Comment by ghcs27** [comment]
The problem seems to be that `http://archive.org/download/TenD2005-07-16.flac16/TenD2005-07-16t10Wonderboy_64kb.mp3` redirects to `http://ia801402.us.archive.org/20/items/TenD2005-07-16.flac16/TenD2005-07-16t10Wonderboy.mp3`. If you do it with this URL, playing the mp3 works as it should.
The readme example might have to be updated.

**Comment by DPH** [comment]
Hi @ersiko
Have tried to test this today and get the same error. Not had long to thoroughly check but will try over next few days. I don't think you are doing anything wrong - this may be a problem with a change we made in #434 / #443 or the example may need updating. @KennethNielsen: any ideas?

Cheers David

**Comment by ersiko** [comment]
Thanks @ghcs27 @DPH , the error was exactly the redirect. If I use the other link, it works.
I created a PR to update the readme with the new one:
https://github.com/SoCo/SoCo/pull/459

Thanks for your help :)

**Comment by DPH** [comment]
@KennethNielsen do we need to enhance #443 ?

This example, shown in the SoCo documentation, uses an http:// file which is an mp3 track. However, #443 will turn this into a radio stream. The consequence is that the Sonos display interprets this as a radio station rather than using the mp3 tags in the file for Artist and track. No big issue, but not correct!
```
                                   Sonos display

With #443 (no title supplied):     Radio - TenD2005-07-16t10Wonderboy.mp3      

With #443 (title supplied):        Radio - Supplied Title

Without #443 (no title supplied):  Wonderboy - TenacioausD2005

Without #443 (title supplied):     Wonderboy - TenacioausD2005
```
Ideally we need to decode if an http(s)://  is an mp3 file or radio stream - however I can't see how to do that. 
We could:
a)  include the 'convert_internet_uris (bool)' which is there but not used, or
b) we could introduce new methods: play_radio, play_file  which would call play_uri - (we already have play_from_queue and switch_to_linein) or
c) include a file type in the play_uri (eg type='radio' or type='file' the default)

Option b makes it simple and clear particularly for new comers, and would be fully backwards compatible, but does add 2 helper methods. 
Thoughts?

Cheers Daivd

**Comment by ersiko** [comment]
Not only that, there are some differences on how the speaker deals with it...

 If it's a file, you can "seek" through it (advance to any moment on the song), while that option is not available if it's a radio. Also, with http://, when it gets to the end of the file, it stops, but with "rincon", it starts over in a loop.

I'd vote for option c), but I'm an actual newcomer so I may not have all the context to make an informed decision. Option b) works for me, too.

**Comment by KennethNielsen** [comment]
I tend to lean towards options (c). It is simpler and both are represented as uri's. The only problem we have is that the http prefix doesn't work anymore, so we will need to figure out what to instead.

**Comment by KennethNielsen** [comment]
I can certainly make the changes, but I will someone to make some research with regards to the workable prefixes, as I'm very short on time currently.

**Comment by DPH** [comment]
I will research the prefixes and post for comment - option c seems the winner so far.
Cheers David

**Comment by ghcs27** [comment]
There is also the option to try using the http(s): prefix and if that does not work, catch the speaker error and try again with x-rincon-mp3radio:

**Comment by DPH** [comment]
Hi @ghcs27 - it works but just gives the wrong behavior. We should fix it properly.
I will do the necessary research over the next couple of days.
Cheers Daivd

**Comment by DPH** [comment]
**URI prefix research for comment** (hard to get all the details - but this should be enough!)

It appears Sonos has four display modes:
     1) Line In              Controls shown: none - no stop, pause, play, or seek
     2) TV In                 Controls shown: none - no stop, pause, play, or seek
     3) Track                 Controls shown: pause, play, seek         Display: Song / Artist/ Album
     4) Radio/Stream   Controls shown: stop, play - no seek     Display: Station / On Now / Information

In SoCo we have functions:
-   switch_to_line_in  and switch_to_tv for 1 and 2. 
-   Track 3 can be set by using play_from_queue.
-   Track 3 and Radio / Stream 4 are both set using play_uri.
	
So for play_uri we need to have the optional ability to say if the uri should be
played as a stream (radio) or as a track.
From testing the following prefixes (URI schemes) deafult to:

	default to Radio / Stream mode:
		x-sonosapi-stream:
		x-rincon-mp3radio:
		hls-radio:
		
	default to Track mode:
		aac:
		http:
		https:
		x-file-cifs:
		
The following also exist for radio but can't find a working example with Sonos: 	mms:  rtsp:
	
Sonos also has a range of prefixes for Tracks specific to each service eg:
	x-sonos-spotify:          (Spotify)
	x-sonosapi-hls-static:  (Amazon Prime)
	x-sonos-http:		    (Google Play & Napster)
	
I belive only prefixes that can be either track or stream are:
		aac:
		http:
		https:
	so we need to give the user the option to force these to Stream / Radio mode.
	This can simply be done by substiuting the prefix with 'x-rincon-mp3radio:'
        However 'hls-radio:' also benefits from using the 'x-rincon-mp3radio:' prefix.
	
**Proposal:** the prefered option appeared to be (c) retain play_uri and add a parameter to it.
As it appears we only ever need to force the choice to a Stream / Radio I would propose adding an optional parameter force-stream=False or similar:
	**def play_uri(self, uri='', meta='', title='', start=True, force-stream=False):**
         If True any prefix is substituted with 'x-rincon-mp3radio:' else the supplied uri is used as is.

Alternatively to make it more future proof we could have the parameter called 
        play_as='', or play_as='radio'

Welcome thoughts on this approach. 
Below is some very basic code that demonstrates playing different URIs with and without translation. 
Regards Daivd
```
import soco
import time
from soco.exceptions import SoCoException, UnknownSoCoException

player = soco.SoCo('192.168.1.68')
print(player.player_name)
delay = 8                 # increase delay if internet speed slow

uri = [
    'aac://icy-e-bz-04-cr.sharp-stream.com/magic1054.aac?amsparams=playerid:BMUK_tunein;skey:1483570441&awparams=loggedin:false',
    'hls-radio://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_high/llnw/bbc_6music.m3u8',
    'http://icy-e-bz-09-boh.sharp-stream.com/magicmellow.mp3.m3u',     # will fail to play without x-rincon-mp3radio:
    'http://ia801402.us.archive.org/20/items/TenD2005-07-16.flac16/TenD2005-07-16t10Wonderboy.mp3',
    'x-rincon-mp3radio://media-the.musicradio.com:80/CapitalMP3',
    'x-sonosapi-stream:s2846?sid=254&amp;flags=32'                     # will error with x-rincon-mp3radio
    # 'x-file-cifs://LocalPi/media/Magic.mp3',                                    # local so excluded
    # 'x-sonos-spotify:spotify%3atrack%3a2Jb4nEP0w6EtFhfRp2aiDg?sid=9&flags=8224&sn=7' #requires account
    ]

def play_it(uri):
    try:
        player.play_uri(uri, title='Test')
        time.sleep(delay)
    except SoCoException as e:
        print(e.message)
    except:
        print('>>>error')

for u in uri:
    print(u)

    print('   ---direct - no uri translation')
    play_it(u)
    time.sleep(delay)

    print('   ---with uri prefix forced to x-rincon-mp3radio:')
    colon = u.find(':')
    if colon > 0:
        u = 'x-rincon-mp3radio' + u[colon:]
    play_it(u)
    time.sleep(delay)


```

**Comment by KennethNielsen** [comment]
Hi @DPH. I never saw that you got back on this one with (extensive) research. I will digest it and comment.

**Comment by KennethNielsen** [comment]
@DPH Thanks for the thorough research on this. I ran the examples and quite enjoyed it. I think I prefer:

 * Your suggested solution of playing the URI as is per default unless a parameters is set
 * I actually tend to think that the force_stream=False is the nicer way to go.

I also think that we should include some of all this research on prefixes in the docstring, since it seems that people tend to use the play_uri method a lot.

Do you want to write it up?

**Comment by DPH** [comment]
Yes happy to. 
Regards Daivd

**Comment by KennethNielsen** [comment]
@DPH I lost track, but wasn't this one resolved with #491?

**Comment by adamgotterer** [comment]
Is #491 released in the latest package? I'm still have trouble playing streams...

**Comment by DPH** [comment]
Hi @adamgotterer,
#491 should fix this and is merged into the latest development version of SoCo downloadable at https://github.com/SoCo/SoCo (will be in the next official release).  
Remember to use the force_radio=True option for certain streams. 

If you are still having problems please confirm you are using the latest development release and post the code that's not working for you so we can help. If this fixes it please post here so we can close this issue.

Cheers David

**Comment by DPH** [comment]
@KennethNielsen yes #491 should close this - lets check @adamgotterer OK before closing it. 
Cheers David

**Comment by KennethNielsen** [comment]
@adamgotterer do you have the option to check the development version?

**Comment by adamgotterer** [comment]
Hey guys - sorry don't have access to the Sonos player for a little while.

**Comment by jeeftor** [comment]
Guys that sample is really helpful - i feel like it should be in the documents

**Comment by KennethNielsen** [comment]
@jeeftor which sample?

**Comment by jeeftor** [comment]
The playing different streams different ways.

**Comment by KennethNielsen** [comment]
@jeeftor ah yes, that's not a bad idea.

**Comment by DPH** [comment]
+1 I will do that

**Comment by ghcs27** [comment]
Probably resolved, please make a new issue if there are still problems.
