### ISSUE TITLE
Surround Sound Mode

### ISSUE THREAD

**Issue by wharzhee** [SoCo/SoCo#461]
I have a playbar with a connect:amp configured as surround rear speakers.

[surround setup: https://sonos.custhelp.com/app/answers/detail/a_id/2248]
[as you can see from the link, it's quite tedious to configure them as surround rear speakers, and when I'm not watching any movies, to set them back as normal separate speakers.

I was wondering if it is possible to toggle surround sound mode?

**Comment by DPH** [comment]
Hi, very interesting to find this surround sound set up. I didn't know it existed. Are your sonos units Ethernet wired? I tried it on mine (but without the Ethernet wire) and it works but no sound from the surround speakers.  Will have to run a cable to try it with Ethernet.

To your question - as the set up is a web form post this should be easy be replicated in code. I am not yet clear if there are any consequences of switching it on and off. 

Another question is why do you need to switch or is it the connect:amp is too quite? 

Cheers David

**Comment by wharzhee** [comment]
yes my playbar and connect:amp are hardwired. [I believe you need it hardwired]

the reason why I asked, is because I set the connect:amp as surround rear when I watch movie (5.1 channels). 

but when I play music in the whole house, I would like to use my connect:amp separately (not together with the playbar)

**Comment by ghcs27** [comment]
I'd suggest you use Wireshark to capture the command packets:
Complete the setup procedure while Wireshark is running and examine the packets exchanged with the player. See also [this wiki page](https://github.com/SoCo/SoCo/wiki/Use-Wireshark-for-protocol-research)
With this information, you might be able to write a program which sends the command for joining/unjoining.
Note that this is a complicated process and you will have to figure out a lot of stuff by yourself, even though I can give you some hints.

**Comment by ghcs27** [comment]
If anyone has a surround setup to test with and can capture the packets, please post the results here.

**Comment by ghcs27** [comment]
PR for this is now at #646.
@wharzhee, can you please test if it works for you?

**Comment by rytilahti** [comment]
Separating the speakers from the surround setup is more complicated than simply toggling whether they are used or not (as done in the linked PR). Here are the commands for creating a group and then disbanding it:
```
Endpoint: /DeviceProperties/Control

<s:Body>
<u:AddHTSatellite
    xmlns:u="urn:schemas-upnp-org:service:DeviceProperties:1">
    <HTSatChanMapSet>
        RINCON_<play1 left>:LF,RF;RINCON_<play right>:RR;RINCON_<beam>:LR
        </HTSatChanMapSet>
    </u:AddHTSatellite>
</s:Body>

<s:Body>
<u:RemoveHTSatellite
    xmlns:u="urn:schemas-upnp-org:service:DeviceProperties:1">
    <SatRoomUUID>
        RINCON_<beam>
        </SatRoomUUID>
    </u:RemoveHTSatellite>
</s:Body>
```
When doing this with the app, you will need to manually confirm the location of one of the speakers, it may be possible to go around that limitation by directly using the `HTSatChanMapSet` but I never tested it.

**Comment by danieledge** [comment]
Does this capability work ? Looking to be able to remove and reinstate surrounds

**Comment by pwt** [comment]
> Does this capability work ? Looking to be able to remove and reinstate surrounds

Not at the moment. There's a couple of PRs targeting this feature (#646 and #780), but neither is complete.

**Comment by rytilahti** [comment]
The first PR adds controls only for the "Music Playback" option seen at https://support.sonos.com/s/article/4804?language=en_US . The latter PR extends to cover all other options (besides reset) listed on that page, including toggling surround on/off like you can do in the app.

Neither do allow real grouping/ungrouping of devices, the payloads I posted above could be used to do that.
