### ISSUE TITLE
Didl class for Sonos favorites - code style

### ISSUE THREAD

**Issue by ghcs27** [SoCo/SoCo#469]
To make browsing Sonos favorites possible with the existing music library methods, a data structure for the `object.itemobject.item.sonos_favorite` Didl class is required.

I have created this class, but I require your advice for code style:
In the metadata for a Sonos favorite, there is a `<resMD>` tag which contains the metadata of the item to which the favorite refers. To make its contents accessible to the user, there are two possible implementations:

1. When the DidlFavorite object is created, parse the resMD metadata and make the referenced object available via an attribute which can be accessed and modified. When the favorite it is converted back to XML, call `to_didl_string()` on the referenced object to get the metadata back.
This can be archieved by adding a `resource_meta_data` property - see [`ghcs27:favorite_data_structure`](https://github.com/ghcs27/SoCo/tree/favorite_data_structure.)
2. Keep the resMD metadata in its own attribute. Make it accessible by adding a `reference` property which parses the metadata on read. For this, see [`ghcs27:favorite_data_structure_alt`](https://github.com/ghcs27/SoCo/tree/favorite_data_structure_alt.)

Which implementation do you prefer?

**Comment by ghcs27** [comment]
Please tell me for which implementation I should open a PR.

**Comment by KennethNielsen** [comment]
Hi @ghcs27 

I'm sorry about never getting back to you on this. I unsure if I consider it a coding style issue as such. But the first version sounds somewhat more involved and so until someone asks for the ability to edit it I think the second option is better.

Regards Kenneth
