### ISSUE TITLE
Clearing Queue with Home Assistant??

### ISSUE THREAD

**Issue by jer78** [SoCo/SoCo#483]
I am using SoCo with Home Assistant and there's not currently a service to clear the queue (within Home Assistant). I asked this question in the Home Assistant forum but did not receive a reply.

Is there a way I can use a command line script to SoCo to clear the Queue?

**Comment by KennethNielsen** [comment]
Hi @jer78 

Yes, the queue can the cleared with a Python script. Please see the documentation (http://docs.python-soco.com/en/latest/) in particular getting started (http://docs.python-soco.com/en/latest/getting_started.html) and the micro examples page ()

**Comment by KennethNielsen** [comment]
Let me know if this answers your question.

**Comment by jer78** [comment]
Hi Kenneth, thanks for your reply. I'm guessing the easiest way would be to copy and paste the above into a python script file and then use a command line component within Home Assistant to call the script?

**Comment by KennethNielsen** [comment]
@jer78 yes, provided that Home Asistant makes that possible, then that would be the way to go. I would recommend learning a little bit of Python before starting to make and execute scripts.

I'll close this and consider it answered. If not, feel free to re-open.
