### ISSUE TITLE
add_multiple_to_queue fails with too many items (>16)

### ISSUE THREAD

**Issue by KennethNielsen** [SoCo/SoCo#485]
While answering #223 I was playing around with the new add_multiple_to_queue method and I noticed that it kept failing after trying a few times to add a queue to the queue. After a little bit of investigation it appears to be related (somehow) to the number of items added.

To reproduce run the follow:

```python
import soco

for device in soco.discover():
    if device.player_name == "Stue":
        break

device.clear_queue()
print(device)

for n in range(1, 100):
    print(n)
    device.clear_queue()
    sandman = device.music_library.get_tracks(search_term="Enter Sandman")[0]
    items = [sandman] * n
    device.add_multiple_to_queue(items)
```
(while changing the zone and track name to something that works at your place).

On my system it fails when n hits 17. My initial thought was that the metadata got too big to be contained in whatever data type the Sonos strings has, so I printed out the size of the uris and metadata strings while testing:

```text
<SoCo object at ip 192.168.1.18>
1
Metadata 917 uris 93
2
Metadata 1835 uris 187
3
Metadata 2753 uris 281
4
Metadata 3671 uris 375
5
Metadata 4589 uris 469
6
Metadata 5507 uris 563
7
Metadata 6425 uris 657
8
Metadata 7343 uris 751
9
Metadata 8261 uris 845
10
Metadata 9179 uris 939
11
Metadata 10097 uris 1033
12
Metadata 11015 uris 1127
13
Metadata 11933 uris 1221
14
Metadata 12851 uris 1315
15
Metadata 13769 uris 1409
16
Metadata 14687 uris 1503
17
Metadata 15605 uris 1597
Traceback (most recent call last):
  File "test_multiple.py", line 15, in <module>
    device.add_multiple_to_queue(items)
  File "/home/kenni/venv/soco/SoCo/soco/core.py", line 1401, in add_multiple_to_queue
    ('EnqueueAsNext', 0)
  File "/home/kenni/venv/soco/SoCo/soco/services.py", line 181, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/home/kenni/venv/soco/SoCo/soco/services.py", line 408, in send_command
    self.handle_upnp_error(response.text)
  File "/home/kenni/venv/soco/SoCo/soco/services.py", line 469, in handle_upnp_error
    error_xml=xml_error
soco.exceptions.SoCoUPnPException: UPnP Error 402 received: Invalid Args from 192.168.1.18
```

however, when looking at that output I don't see any obvious data type limitation (15605 is close to 2**14, but first of all I have never heard of a string being limited in length to 14 bits, second it doesn't actually cross it when it fails).

Another possible idea is that the total request sent gets too big, but I haven't had a chance to look into that yet.

**Comment by KennethNielsen** [comment]
@ghcs27 FYI.

**Comment by KennethNielsen** [comment]
In the other hand, googling a bit around and looking at other implementations e.g. https://gowalker.org/github.com/ianr0bkny/go-sonos/upnp#AVTransport_AddMultipleURIsToQueue they mention requirements on the container_uri, so that may be worth looking into.

**Comment by ghcs27** [comment]
I can reproduce the problem - on my system it fails when n hits 17 as well.
Supplying a valid container does not help in any way, so I doubt that the conotainer is the problem.

**Comment by ghcs27** [comment]
I had to pull out Wireshark to figure out what Sonos does - and it splits up the items into multiple request with a maximum of 16 items each.
This means that I should split the items into chunks of 16, too. I'll make a fix PR soon.

**Comment by KennethNielsen** [comment]
Great work \o/ I was contemplating whether some kind of batching was
involved, but didn't an idea handy of how to test it. I look forward to the
PR.

2017-03-20 11:58 GMT+01:00 ghcs27 <notifications@github.com>:

**Comment by ghcs27** [comment]
#488 here it is

**Comment by ghcs27** [comment]
The bugfix merged, so this can probably be closed now.

**Comment by KennethNielsen** [comment]
@ghcs27 Agreed.

BTW, small tip if you weren't aware of it, there is this github feature, where you can automatically close isues by refernceing them in the commit message of the commit that fixes them. It's quite neat: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by ghcs27** [comment]
Thanks for the tip!
