### ISSUE TITLE
Adding "+" to the version in development

### ISSUE THREAD

**Issue by KennethNielsen** [SoCo/SoCo#486]
I want to add a new convention to our development process. I think we should denote the version in the development archive with whatever version was released last with a "+" suffixed.

That will make it easier to deduce from the version string alone, what kind of installation a user that reports an issue has.

I already changed the string the __init__.py file and unless someone objects wildly I will update the "how to do a release" section of the docs.

**Comment by stefankoegl** [comment]
I have followed this practice now with the release of 0.14 (#538), so we're now at version `0.14+`.

**Comment by KennethNielsen** [comment]
I have added the information to the release howto: https://github.com/SoCo/SoCo/commit/bca231fadd457ac80a1490c6dd43b7b45a86f61e.
