### ISSUE TITLE
DPH joins the team of maintainers

### ISSUE THREAD

**Issue by KennethNielsen** [SoCo/SoCo#490]
Hello everyone

Please help me in welcoming DPH to the maintainers team of SoCo/SoCo.

@DPH has been involved with the SoCo projects for a long while now and has contributed in many different areas. Especially, he has been very active with issues; reproducing, testing patches, asking for clarification and doing research on possible solutions. All these contributions have consistently been of high quality and has helped push forward.

Furthermore, @DPH is friendly, objective and on-point with the communication, which makes him a good fit for open source development.

Welcome to the team!

**Comment by stefankoegl** [comment]
Welcome! 🎉
