### ISSUE TITLE
Could I use play_uri to play internet radio?

### ISSUE THREAD

**Issue by squallee** [SoCo/SoCo#494]
I tried your code in README. It works perfect. Now I am trying to play music from the internet radio. 
When I use 
sonos.play_uri('http://uk6.internet-radio.com:8465/')
it shows SoCoUPnPException:
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    sonos.play_uri('http://radiopanther.webnode.gr/')
  File "/home/owner/.local/lib/python2.7/site-packages/soco/core.py", line 104, in inner_function
    return function(self, *args, **kwargs)
  File "/home/owner/.local/lib/python2.7/site-packages/soco/core.py", line 483, in play_uri
    ('CurrentURIMetaData', meta)
  File "/home/owner/.local/lib/python2.7/site-packages/soco/services.py", line 181, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/home/owner/.local/lib/python2.7/site-packages/soco/services.py", line 408, in send_command
    self.handle_upnp_error(response.text)
  File "/home/owner/.local/lib/python2.7/site-packages/soco/services.py", line 469, in handle_upnp_error
    error_xml=xml_error
soco.exceptions.SoCoUPnPException: UPnP Error 714 received: Illegal MIME-Type from 192.168.128.181
How could I use play_uri to play internet stations? Thank you!

**Comment by muammar** [comment]
@DPH  I have started adding Sonos support to an application I did for chromecast using soco https://github.com/muammar/mkchromecast/pull/60, and adding `x-rincon-mp3radio` worked for me. What if the codec used is, let's say, `wav`, will `x-rincon-mp3radio` make the sonos play it as `wav`?

**Comment by DPH** [comment]
Hi @muammar. when you play a uri, Sonos will treat it as a file / track or a stream based on its prefix. Prefixes `http & https` default to file / track. Often you may want these to be a stream / radio so switching the prefix to ` x-rincon-mp3radio` Sonos will treat it as a stream. We have updated SoCo to allow this choice in #443 and #491 there is also documentation in the later - these will be in the next release. 

This should apply to all formats Sonos support. This page shows supported formats: [https://sonos.custhelp.com/app/answers/detail/a_id/80/~/supported-audio-formats](url)

I have been unable to find a `.wav` stream to test this on - if you have one please let me try it.
Hope this helps
Cheers Daivd

**Comment by muammar** [comment]
I have tried it, and it only plays with `mp3` containers. Does it have to be something like `x-rincon-wavradio` for wav? You can try with my application if you have the time... For mp3 is working fine :), but I would like to give support to other containers too. https://github.com/muammar/mkchromecast/pull/60

**Comment by DPH** [comment]
Hi again @muammar. I am not aware of a  `x-rincon-wavradio` prefix. Had a quick look at your code but can't find an example .wav stream.  (Looks like an interesting develoment). 

Does the .wav play from Sonos directly (ie just with the Sonos controller)? If so we can make it work with SoCo. Can you post the .wav stream you are trying to play or email it over the weekend, and I will look at it early next week.
Cheers Daivd

**Comment by muammar** [comment]
hi @DPH, 

>Hi again @muammar. I am not aware of a x-rincon-wavradio prefix. Had a quick look at your code but can't find an example .wav stream. (Looks like an interesting develoment).

Thanks for confirming this. 

>Does the .wav play from Sonos directly (ie just with the Sonos controller)? If so we can make it work with SoCo. Can you post the .wav stream you are trying to play or email it over the weekend, and I will look at it early next week.

The `.wav` stream is created by mkchromecast. What I do is to redirect computer's audio to `ffmpeg` and then pipe it to a local webserver to cast to sonos and chromecast. I have to add that I tried with `ogg` that is supported by sonos, but it didn't work either. But with `mp3` it works fine. Here you can find a `ogg` stream, I didn't try it yet.

http://192.99.131.205:8000/pvfm1.ogg

I forgot to write what error message was displayed on my Sonos Android app when trying both `wav` and `ogg` streams created by mkchromecast. I will report it later.

**Comment by muammar** [comment]
Trying to play the URL I pasted above give this error:

```
>>> sonos.play_uri('x-rincon-mp3radio://192.99.131.205:8000/;pvfm1.ogg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/soco/core.py", line 104, in inner_function
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/soco/core.py", line 483, in play_uri
    ('CurrentURIMetaData', meta)
  File "/usr/local/lib/python3.5/site-packages/soco/services.py", line 181, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/soco/services.py", line 408, in send_command
    self.handle_upnp_error(response.text)
  File "/usr/local/lib/python3.5/site-packages/soco/services.py", line 469, in handle_upnp_error
    error_xml=xml_error
soco.exceptions.SoCoUPnPException: UPnP Error 800 received:  from 192.168.1.182
```

Regarding the `wav` stream, the sonos speaker connects and disconnects in a loop and does not plays anything. I don't know how to play a stream different from `mp3`. With Chromecast it works though. By the way, how can I specify the Mime-Type in Sonos?.

**Comment by DPH** [comment]
Hi @muammar,
have tried out the ogg stream you provided and it does not work. Have experimented with different approaches but no luck. Have searched forums and the web and it appears Sonos does not support ogg radio streams.  From the Sonos page: `Supported Internet radio audio formats:
MP3
AAC
WMA`


I think the Mime type can be specified in the meta data but as Sonos doesn't support ogg radio streams I don't think that will help. 

You can add radio streams directly in Sonos (Manage / Add Radio Station). I tried it and it does not work there either which tens to confirm Sonos don't support his format of stream. 

There have been lots of requests over the last 10 years to Sonos to support ogg streams, you could make a request directly to Sonos to be able to add an ogg radio station. If it worked in their system we can make it work in SoCo.  But for now I can't help you with this - others may have ideas. 
Cheers David

**Comment by muammar** [comment]
Thanks for your reply. 

> have tried out the ogg stream you provided and it does not work. Have experimented with different approaches but no luck. Have searched forums and the web and it appears Sonos does not support ogg radio streams. From the Sonos page: Supported Internet radio audio formats: MP3 AAC WMA

I think I also tried with AAC audio format but that didn't work either. I will confirm this later.

**Comment by muammar** [comment]
@DPH with AAC it works. It turned out to be the mime-type.  I was passing it as `audio/mp4` instead of `audio/aac`.

**Comment by squallee** [comment]
Sorry I haven’t got back to you sooner. I was working on other things these days. I have tested your method. It works perfectly! Thanks for getting back to me.

**Comment by DPH** [comment]
Great - pleased this works for you all.
I think we can close this issue ?

Cheers Daivd

**Comment by squallee** [comment]
Sure, thank you for your help.
