### ISSUE TITLE
Trying to play local file but getting UPnP Error

### ISSUE THREAD

**Issue by aasha08** [SoCo/SoCo#508]
I am using Python 2.7  and Soco 0.12 version. I am using play_local_files.py program in my Raspberry pi. But I am getting UPnP exceptions " UPnP Error 711 received: Illegal seek target from 192.168.0.100".

I have tried to print the play_from_queue() function but I am getting "None" intsead of "False" or "True" 

The same script was working in the same Raspberry Pi. But now It is Not working at all.

The Error code:
Traceback (most recent call last):
  File "play_local_files.py", line 106, in <module>
    main()
  File "play_local_files.py", line 99, in main
    add_random_file_from_present_folder(machine_ip, port, zone_name)
  File "play_local_files.py", line 82, in add_random_file_from_present_folder
    zone.play_from_queue(number_in_queue)
  File "/usr/local/lib/python2.7/dist-packages/soco/core.py", line 104, in inner_function
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/soco/core.py", line 424, in play_from_queue
    ('Target', index + 1)
  File "/usr/local/lib/python2.7/dist-packages/soco/services.py", line 181, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/soco/services.py", line 408, in send_command
    self.handle_upnp_error(response.text)
  File "/usr/local/lib/python2.7/dist-packages/soco/services.py", line 469, in handle_upnp_error
    error_xml=xml_error
soco.exceptions.SoCoUPnPException: UPnP Error 711 received: Illegal seek target from 192.168.0.100

Can anyone help me on this?

**Comment by DPH** [comment]
Hi @aasha08,
can you post your code and I will look tomorrow
Cheers Daivd

**Comment by aasha08** [comment]
Hi @DPH,
I have attached my code here. please have a look into it.
Thanks,
Aasha

**Comment by aasha08** [comment]
HI @DPH,

This is the code I am using. PLease have a look into it. Thanks in advance.

from __future__ import print_function, unicode_literals

import os
import time
from threading import Thread
from random import choice
try:
    # Python 3
    from urllib.parse import quote
    from http.server import SimpleHTTPRequestHandler
    from socketserver import TCPServer
    print('Running as python 3')
except ImportError:
    # Python 2
    from urllib import quote
    from SimpleHTTPServer import SimpleHTTPRequestHandler
    from SocketServer import TCPServer
    print('Running as python 2')

import soco


class HttpServer(Thread):
    """A simple HTTP Server in its own thread"""

    def __init__(self, port):
        super(HttpServer, self).__init__()
        self.daemon = True
        handler = SimpleHTTPRequestHandler
        self.httpd = TCPServer(("", port), handler)

    def run(self):
        """Start the server"""
        print('Start HTTP server')
        self.httpd.serve_forever()

    def stop(self):
        """Stop the server"""
        print('Stop HTTP server')
        self.httpd.socket.close()


def add_random_file_from_present_folder(machine_ip, port, zone_name):
    """Add a random non-py file from this folder and subfolders to soco"""
    # Make a list of music files, right now it is done by collection all files
    # below the current folder whose extension does not start with .py
    # This will probably need to be modded for other pusposes.
    music_files = []
    print('Looking for music files')
    for path, dirs, files in os.walk('.'):
        for file_ in files:
            if not os.path.splitext(file_)[1].startswith('.py'):
                music_files.append(os.path.relpath(os.path.join(path, file_)))
                print('Found:', music_files[-1])

    random_file = choice(music_files)
    # urlencode all the path parts (but not the /'s)
    random_file = os.path.join(
        *[quote(part) for part in os.path.split(random_file)]
    )
    print('\nPlaying random file:', random_file)
    netpath = 'http://{}:{}/{}'.format(machine_ip, port, random_file)

    for zone in soco.discover():
        if zone.player_name == zone_name:
            break

    number_in_queue = zone.add_uri_to_queue(netpath)    
    zone.play_from_queue(number_in_queue)


def main():
    # Settings
    machine_ip = '192.168.0.100'
    port = 8000
    zone_name = 'Stue'  # Danish for living room
    # Setup and start the http server
    server = HttpServer(port)
    server.start()

    # When the http server is setup you can really add your files in
    # any way that is desired. The source code for
    # add_random_file_from_present_folder is just an example, but it may be
    # helpful in figuring out how to format the urls
    try:
        add_random_file_from_present_folder(machine_ip, port, zone_name)
        # Remember the http server runs in its own daemonized thread, so it is
        # necessary to keep the main thread alive. So sleep for 3 years.
        time.sleep(10**8)
    except KeyboardInterrupt:
        server.stop()
    
main()

**Comment by ghcs27** [comment]
Ok, that's exactly the `play_local_files` example from this repository.
The error occurs in these two lines:
```python
number_in_queue = zone.add_uri_to_queue(netpath)    
zone.play_from_queue(number_in_queue)
```
I suspect that `add_uri_to_queue` returns a 1-based index, while `play_from_queue()` expects a 0-based index. This means that if the item is enqueued as the last item, `number_in_queue` will not be a valid 0-based index, leading to the "Illegal seek target" UPnP error.

**Comment by DPH** [comment]
Good spot @ghcs27 
Maybe we should make the queue reference consistent in SoCo (all zero based?)
Thoughts

Cheers David

**Comment by ghcs27** [comment]
I agree that the indices should be consistently 0-based.
We should keep in mind that modifying the code to use consistent indices could be a breaking change.

**Comment by DPH** [comment]
Have raised issue #510 to discuss making queue track reference consistent. 

@aasha08 let us know if the above solves your current issue - and if we can close this.

Cheers David

**Comment by aasha08** [comment]
I have used  get_current_track_info()['playlist_position] . But I am getting the following error 

Traceback (most recent call last):
  File "play_music.py", line 109, in <module>
    main()
  File "play_music.py", line 100, in main
    add_random_file_from_present_folder(machine_ip, port, zone_name)
  File "play_music.py", line 83, in add_random_file_from_present_folder
    zone.play_from_queue(number_in_queue_1)
  File "/usr/local/lib/python2.7/dist-packages/soco/core.py", line 104, in inner_function
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/soco/core.py", line 424, in play_from_queue
    ('Target', index + 1)
TypeError: cannot concatenate 'str' and 'int' objects

**Comment by ghcs27** [comment]
The  '  in front of the index looks strange.

**Comment by aasha08** [comment]
Sorry there was a error in my change . I resolved  that. Now I dont get any error.
But the mp3 file is not playing in SONOS. I have connected  SONOS with my Android. While the script trying to play the mp3 file I could see some error that the "Unable to connect with IP 192.168.0.100:8000"

**Comment by KennethNielsen** [comment]
@aasha08 You need to change the values in the settings section:

```python
# Settings
machine_ip = '192.168.0.100'
port = 8000
zone_name = 'Stue' # Danish for living room
```

Specifically machine_ip needs to be the IP address of your machine, but you also need to change zone_name (unless you are Danish), which kind of makes me wonder if the pasted code is what you are running.

**Comment by PatrikFehrenbach** [comment]
Hey @KennethNielsen 

I am having the same issues @aasha08 

I have the file ```localfiles.py``` and ```TenD2005-07-16t10Wonderboy.mp3``` both sitting in ```/tmp/music``` 

I have used the the code from [https://github.com/SoCo/SoCo/blob/master/examples/play_local_files/play_local_files.py](url) and adjusted the settings to:

```
    machine_ip = '192.168.0.194'
    port = 8000
    zone_name = 'Musikzimmer'  
    server = HttpServer(port)
    server.start()
```

Musikzimmer is german for Music Room :-)

I have confirmed the correct zone name with: 

```
import soco
for zone in soco.discover():
	print zone.player_name
```

However when i try to run the script i get the following error: 
```
Running as python 2
Start HTTP serverLooking for music files

Found: TenD2005-07-16t10Wonderboy.mp3

Playing random file: TenD2005-07-16t10Wonderboy.mp3
Traceback (most recent call last):
  File "/private/tmp/music/localfiles.py", line 106, in <module>
    main()
  File "/private/tmp/music/localfiles.py", line 99, in main
    add_random_file_from_present_folder(machine_ip, port, zone_name)
  File "/private/tmp/music/localfiles.py", line 82, in add_random_file_from_present_folder
    zone.play_from_queue(number_in_queue)
  File "/usr/local/lib/python2.7/site-packages/soco/core.py", line 104, in inner_function
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/soco/core.py", line 424, in play_from_queue
    ('Target', index + 1)
  File "/usr/local/lib/python2.7/site-packages/soco/services.py", line 181, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/soco/services.py", line 408, in send_command
    self.handle_upnp_error(response.text)
  File "/usr/local/lib/python2.7/site-packages/soco/services.py", line 469, in handle_upnp_error
    error_xml=xml_error
soco.exceptions.SoCoUPnPException: UPnP Error 711 received: Illegal seek target from 192.168.0.80
```

I have installed SoCo using ```pip install soco```

Thank you in advance 

Patrik

**Comment by simonravel** [comment]
Same issue here. Can you leave the port to 8000, or is this also a specific setting of your sonos setup?

**Comment by KennethNielsen** [comment]
@simonravel the port can be any port in the range of high numbered ports that aren't restricted (like 22 and 80). I'm considering revising the example to include more trouble shooting information.

**Comment by KennethNielsen** [comment]
@aasha08, @PatrikFehrenbach, @simonravel indeed as @ghcs27 mentioned, the `play_from_queue` index should 0-based whereas that returned by `add_uri_to_queue` is 1 based. Therefore, the quick fix to get you people going again is to change the line:
```python
    zone.play_from_queue(number_in_queue)
```
to 
```python
    zone.play_from_queue(number_in_queue - 1)
```

I have a branch with this fix, and I have revised the script to e.g. autodetect the IP address and output more trouble shooting information, which should hopefully help make it more robust. It also now accepts settings on the command line in stead of having to edit it, which should be an improvement. I will post the PR here when it is done.

**Comment by KennethNielsen** [comment]
PR is #570
