### ISSUE TITLE
Add mkchromecast to list of external projects

### ISSUE THREAD

**Issue by KennethNielsen** [SoCo/SoCo#512]

**Comment by KennethNielsen** [comment]
https://github.com/muammar/mkchromecast/

**Comment by ghcs27** [comment]
Like [this](https://github.com/SoCo/SoCo/wiki/SoCoProjects)?

**Comment by KennethNielsen** [comment]
Ah crap. It was there already. I didn't remember at the time where we kept list, so I just created the issue so that I would remember to check. Closing.

**Comment by ghcs27** [comment]
It was not there until I added it today!

**Comment by KennethNielsen** [comment]
Awesome. Thanks.
