### ISSUE TITLE
get_favorite_radio_stations() returns invalid uri on some tunein stations

### ISSUE THREAD

**Issue by paicolman** [SoCo/SoCo#517]
Hi there,

The get_favorite_radio_stations() method seems to return strange uri in some stations of TuneIn. Maybe it's the station's data wrong or protected?

TO Reproduce:
`import soco
zone = soco.discover().pop()
zone.play_uri('x-rincon-mp3radio://http://live2.rcnmundo.com/lamegacartagena.mp3')`
(This is a radio station from colombia, just as example)

`zone.get_favorite_radio_stations()` returns for this station:
`{u'uri': 'x-sonosapi-stream:s139893?sid=254&flags=8224&sn=0', u'title': 'La Mega (Cartagena) 94.5 (Latino-Pop)'}`

For other stations I get the real url:
`{u'uri': 'x-rincon-mp3radio://http://www.radioswissjazz.ch/live/aacp.m3u', u'title': 'Radio Swiss Jazz'}`

**Comment by DPH** [comment]
Hi @paicolman.
Sonos supports several different types of radio streams.

**Comment by DPH** [comment]
Hi @paicolman 
did this answer your question?
Can we close this issue or do you need more info?
Cheers David

**Comment by DPH** [comment]
Hi @paicolman, assume this all OK so will close issue,
Please re-open if still a problem.
Cheers Daivd

**Comment by paicolman** [comment]
Sorry, yes, please close this...
