### ISSUE TITLE
snapshot throwing an error

### ISSUE THREAD

**Issue by rudyvan** [SoCo/SoCo#519]
Hello,

i have a large sonos setup with a TV soundbar.
Sometimes (once every 50 calls) i get a snapshot() error.
The documentation states that snapshot should return True when the zone is a coordinator.
Why an error then returns that the cross_fade can only be called on a coordinator?
I am using the latest build.
See the error message below:

```python
2017/10/03 14:37:12 Crash of PI-Deploy
Traceback (most recent call last):
  File "/home/pi/PI_Voice.py", line 125, in sonos_thread
    if resume[zone.ip_address].snapshot(): # it returns True when the snapshot zone is a coordinator
  File "/usr/local/lib/python3.5/dist-packages/soco/snapshot.py", line 101, in snapshot
    self.cross_fade = self.device.cross_fade
  File "/usr/local/lib/python3.5/dist-packages/soco/core.py", line 103, in inner_function
    raise SoCoSlaveException(message)
soco.exceptions.SoCoSlaveException: The method or property "cross_fade" can only be called/used on the coordinator in a group'
```
Thanks for the help.
Kind Regards,
Rudy

**Comment by DPH** [comment]
Hi Rudy,
does this occur on the sound bar when it is playing TV?
If so cross fade is not valid on TV input!

We would need to tweak the snapshot code to exclude setting this when TV in use. 
Cheers David

**Comment by rudyvan** [comment]
Indeed it probably is the case.
Is it possible to modify the code and bypass cross fade when the device does not support it or would trow an error?
Kind Regards,
Rudy

**Comment by DPH** [comment]
Hi @rudyvan ,
have looked at this and it is on getting the cross fade status that it errors. 
Are you re-initialising snapshot every time, or is the function reused. 
The current set up requires you reinitialise each time, otherwise some variables are not set correctly.
I think this is what is causing the problem. 

Check   that
```resume[zone.ip_address] = Snapshot(zone) ```
occurs every time before 
```if resume[zone.ip_address].snapshot():```

let me know if this fixes it, or if this is not the problem and I will dig deeper. 
Cheers David

**Comment by rudyvan** [comment]
Hello David,

i called SoCoCam() each time before calling snapshot().
```python
resume[zone.ip_address]=SoCoCam(zone);
```
i will now replace with your suggestion to call Snapshot(zone) instead and report back if it is not solved.

Thanks for your help!
Kind Regards,
Rudy

**Comment by rudyvan** [comment]
Apologies David,

i now saw that i did:
```python3
from soco.snapshot import Snapshot as SoCoCam;
for zone in zones:
	resume[zone.ip_address]=SoCoCam(zone)
	if resume[zone.ip_address].snapshot(): # it returns True when the snapshot zone is a coordinator
...
```
so indeed i was calling Snapshot(zone) before each call to snapshot

**Comment by DPH** [comment]
Hi Rudy, no problem. 
I am confused (but thats not hard!). Assume this has been happening for some time - not connected to the latest Sonos release or their voice commands?
Can you post a short chunk of code that fails for you so I can try it. 
I have 7 zones including a sound bar. Also let me know how they are grouped and what source is in play.  
Cheers David

**Comment by rudyvan** [comment]
Dear David,

i  have a 9 zone configuration, and all the upgrades to the latest sonos version happened.
The issue is that the error comes intermittendly, only a few times a day and on some days not at all.
Most sonos speakers are wired to the network, only 2 speakers are connected through wifi.
There is one sonos amp and one sonos connect.
if you point me how to do logging of the upnp messages, i could try to figure out what this is.

below is the code (not pep8 formatted), but i don't think it will make you any wiser..

Kind Regards,
Rudy

```python
				try: # discover the zones and then have 2 logic's, one for all the sonos devices and one for just one room
					coordinators, memberships, volumes, resume, zone_c, zones = [],{}, {}, {}, None, list(soco.discover())
					if room is None: # we have to play in all the rooms
						cfg_pr_stat(["msg_sonos",tts_item.replace("\n",""),len(self.tts_dict[tts_item]["text"]),time_speach],True)
						#1. snapshot the zones, pause and set the volume of the zones playing and determine the coordinator
						for zone in zones:
							resume[zone.ip_address]=SoCoCam(zone)
							if resume[zone.ip_address].snapshot(): # it returns True when the snapshot zone is a coordinator
								coordinators.append(zone); volumes[zone.ip_address]=zone.volume
								trans_state=zone.get_current_transport_info()
								if trans_state["current_transport_state"]=="PLAYING" and not zone.is_playing_tv: zone.pause() # can not pause TV
								if not zone.is_playing_tv: zone.volume=volume # change the volume if the TV is not playing
								if not self.sonos_playbar(zone.ip_address) or zone_c is None: zone_c = zone # ensure the new zone coordinator is preferably not a playbar, that seems to give bad sound
							else: memberships[zone.ip_address]=zone.group.coordinator
						if not len(coordinators) or zone_c is None: raise ValueError("??no sonos coordinators found") # should not happen
						# now join the zones that does not contain a playbar
						if party_mode: 
							for zone in zones:
								if zone==zone_c or zone.group.coordinator==zone_c: continue
								if not zone.is_playing_tv: zone.join(zone_c)
						#2. play the wav file with the coordinators
						while True:	 # run this message, then look for other messages and run them too until the queue is empty...
							while times > 0: # and repeat if needed
								for zone in [zone_c] if party_mode else coordinators: 
									if zone.is_playing_tv and len(coordinators)>1: pass # skip the playing television if there are more coordinators
									else: zone.play_uri(self.link_tts(tts_item))
								time.sleep(time_speach); times-=1; cfg_pr_stat(["msg_tts_played",tts_item])
							ret_val=pop_queue()
							if ret_val is None: break
							tts_item,dummy1,times,dummy2=ret_val  # ignore room and partymode 
						#3. unjoin and restore the groups which were destroyed by the party mode
						if party_mode:
							for zone in zones: 
								if not zone.is_playing_tv: zone.unjoin() # skip the tv players..
							for zone in zones: 
								if zone.ip_address in memberships: zone.join(memberships[zone.ip_address]) # time.sleep(1) 
					else: # just play the zone in the "room"
						# make the room_grp lower case except the first character
						player_room="{:}{:}".format(pi.rooms[room].room_grp[0],pi.rooms[room].room_grp[1:].lower()); zone=None
						cfg_pr_stat(["msg_sonos_room",room,player_room,tts_item.replace("\n",""),len(self.tts_dict[tts_item]["text"]),time_speach])
						for zone_s in zones: # save the volumes and store the coordinator in "zone"
							volumes[zone_s.ip_address]=zone_s.volume
							if zone_s.player_name==player_room: zone=zone_s.group.coordinator; # the coordinator is what we need next
						if zone is None: cfg_pr_stat(["war_tts_room",player_room,",".join(zone_scan.player_name for zone_scan in zones)]); continue #bye
						resume[zone.ip_address]=SoCoCam(zone); resume[zone.ip_address].snapshot(); zone.volume=volume; 
						coordinators=[zone] if zone.is_coordinator else []
						while times > 0: zone.play_uri(self.link_tts(tts_item)); time.sleep(time_speach); times-=1
					# Finally : restore the earlier coordinator snapshots...
					for zone in zones:
						if zone.is_playing_tv: 
							if zone.volume!=volumes[zone.ip_address]: zone.volume=volumes[zone.ip_address] # cannot restore a TV, but restore the volume
						elif zone.is_coordinator and zone.ip_address in resume: resume[zone.ip_address].restore(fade=False)
				except: pi.log_prg.log_crash_pr_stat(["err_sonos"],sys.exc_info())
```

**Comment by DPH** [comment]
Hi Rudy,
I can't see anything you are doing wrong in your code. 
What version of Python are you running and on what operating system? 

It looks like snapshot determines if it is a coordinator in a different way to core (internal to SoCo).
I don't understand why they would return different results but clearly they do in some instances.

Could you add one line to the snapshot code so that it tests for coordinator in the same way as core, and see if that resolves the problem. Immediately before the comment on line 90 in snapshot.py 

```
       # Save the volume, mute and other sound settings
```
add the following to set the internal is_coordinator value

```
        self.is_coordinator = self.device.is_coordinator

        # Save the volume, mute and other sound settings
```
If you have any problems doing this let me know.
Once done see if this removes the problem and let us know.

Cheers David

**Comment by rudyvan** [comment]
Dear David,

i am running on raspberry Stretch (the lastest raspbian) with python 3.5
i did previously the following command to ensure i have the latest soco version:
```bash
sudo pip3 install soco --upgrade
```
i made the change in 
```bash
/usr/local/lib/python3.5/dist-packages/soco/snapshot.py
```
I will let you know how it goes!
Kind Regards,
Rudy

**Comment by DPH** [comment]
Hi @rudyvan,
did that one line change fix the problem?
Looking to put it into the next release, and we can then close this issue.

Cheers David

**Comment by rudyvan** [comment]
Dear David, 
I haven’t seen the error yet after making that change.  
Thanks Rudy
