### ISSUE TITLE
October update for Alexa breaks everything

### ISSUE THREAD

**Issue by tagdara** [SoCo/SoCo#520]
I did some monkey patches to get back online, but they have added some DIDL sections to events that were killing the xml parsing.  

The following changes were made for expediency, but I did not spend a lot of time analyzing whether they were the best choices:

There is a new section under av_transport_uri_meta_data that has a DIDL-Lite container but does not contain most of the required fields.  I'm currently filtering any processing on those tags

events.py starting at line 129:
`
if value.startswith('<DIDL-Lite'):
     log.debug('didl string: %s = %s' % (tag,value))
		if tag=='av_transport_uri_meta_data':
			log.debug('New data format breaks, skipping from_didl_string')
		else:
			value = from_didl_string(value)[0]
`

The 'restricted' tag does not appear on data containers where it possibly should and causes exceptions which I am now ignoring:

data_structures.py starting at 513 commented out

`
        restricted = element.get('restricted', None)
	#if restricted is None:
		#raise DIDLMetadataError("Missing restricted attribute")
	restricted = True if restricted in [1, 'true', 'True'] else False
`

The 'protocolInfo' tag does not appear on data containers where it possibly should and causes exceptions which I am now ignoring:

`
        if content['protocol_info'] is None:
		#raise Exception('Could not create Resource from Element: '
		#               	'protocolInfo not found (required).')
`

**Comment by DPH** [comment]
Hi, pleased you are back working. 

With every Sonos release we are bound to find things we need to change in SoCo, and the voice release is a big change doe Sonos (and very useful so worth some pain!)

Is it only the voice commands that cause problems?
Details of the situations that cause problems would help.

Cheers David

**Comment by tagdara** [comment]
It's a great update, but definitely a lot of changes in the data.   

It seems that most of what was breaking me is in event subscriptions.  The same data format is returned regardless of whether I queue via app or with Alexa, so it does not appear to only be applied to voice requests.

When you receive the LastChange event, it contains multiple <Item> xml objects.  Previously all of these objects had a "restricted" value, but this no longer seems to be the case.  CurrentTrackMetaData now only gets <item id="-1" parentID="-1">.

The only one with a "restricted" value is the new one, in the "val" for r:EnqueuedTransportURIMetaData.

protocolInfo, which used to be a required field, no longer seems to appear anywhere in my log captures.

So in my mind there are 3 changes that immediately affect AVtransport subscriptions and may be further reaching:

- Restricted is being used in different cases now.
- protocolInfo has been supplanted by something new
- There are things in av_transport_uri_meta_data that I'm currently discarding

Here's one captured LastChange event from an Alexa requested song I just played:

`
<e:propertyset xmlns:e="urn:schemas-upnp-org:event-1-0"><e:property><LastChange>&lt;Event xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/AVT/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;&lt;InstanceID val=&quot;0&quot;&gt;&lt;TransportState val=&quot;PLAYING&quot;/&gt;&lt;CurrentPlayMode val=&quot;NORMAL&quot;/&gt;&lt;CurrentCrossfadeMode val=&quot;0&quot;/&gt;&lt;NumberOfTracks val=&quot;1&quot;/&gt;&lt;CurrentTrack val=&quot;1&quot;/&gt;&lt;CurrentSection val=&quot;0&quot;/&gt;&lt;CurrentTrackURI val=&quot;https://d29r7idq0wxsiz.cloudfront.net/DigitalMusicDeliveryService/HPS.m3u8?m=m&amp;amp;dmid=255568843&amp;amp;c=cf&amp;amp;f=ts&amp;amp;t=10&amp;amp;bl=256k&amp;amp;s=true&amp;amp;e1=1507309200000&amp;amp;e2=1507310100000&amp;amp;v=V2&amp;amp;h=30d9ff185871c09065bf2260d5e25a27b9311f3db0f3ae5a4936b738bd9ad74f&quot;/&gt;&lt;CurrentTrackDuration val=&quot;0:02:07&quot;/&gt;&lt;CurrentTrackMetaData val=&quot;&amp;lt;DIDL-Lite xmlns:dc=&amp;quot;http://purl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;urn:schemas-upnp-org:metadata-1-0/upnp/&amp;quot; xmlns:r=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot; xmlns=&amp;quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp;lt;item id=&amp;quot;-1&amp;quot; parentID=&amp;quot;-1&amp;quot;&amp;gt;&amp;lt;res duration=&amp;quot;0:02:07&amp;quot;&amp;gt;https://d29r7idq0wxsiz.cloudfront.net/DigitalMusicDeliveryService/HPS.m3u8?m=m&amp;amp;amp;dmid=255568843&amp;amp;amp;c=cf&amp;amp;amp;f=ts&amp;amp;amp;t=10&amp;amp;amp;bl=256k&amp;amp;amp;s=true&amp;amp;amp;e1=1507309200000&amp;amp;amp;e2=1507310100000&amp;amp;amp;v=V2&amp;amp;amp;h=30d9ff185871c09065bf2260d5e25a27b9311f3db0f3ae5a4936b738bd9ad74f&amp;lt;/res&amp;gt;&amp;lt;upnp:albumArtURI&amp;gt;https://images-na.ssl-images-amazon.com/images/I/81kgn7PiV7L._SS500_.jpg&amp;lt;/upnp:albumArtURI&amp;gt;&amp;lt;upnp:class&amp;gt;object.item.audioItem.musicTrack&amp;lt;/upnp:class&amp;gt;&amp;lt;dc:title&amp;gt;Day 25&amp;lt;/dc:title&amp;gt;&amp;lt;dc:creator&amp;gt;Ta-ku&amp;lt;/dc:creator&amp;gt;&amp;lt;upnp:album&amp;gt;50 Days For Dilla Vol. 1&amp;lt;/upnp:album&amp;gt;&amp;lt;r:tiid&amp;gt;77227c71-52d8-4f31-ab0c-0f5b3462e46f&amp;lt;/r:tiid&amp;gt;&amp;lt;r:contentService id=&amp;quot;201&amp;quot; imageUrl=&amp;quot;https://s3.amazonaws.com/music-provider-logos/AmazonMusic.svg&amp;quot; name=&amp;quot;Amazon Music&amp;quot;/&amp;gt;&amp;lt;r:policies mask=&amp;quot;0x80120000&amp;quot; flags=&amp;quot;0x80120000&amp;quot;/&amp;gt;&amp;lt;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&quot;/&gt;&lt;r:NextTrackURI val=&quot;&quot;/&gt;&lt;r:NextTrackMetaData val=&quot;&quot;/&gt;&lt;r:EnqueuedTransportURI val=&quot;https://d29r7idq0wxsiz.cloudfront.net/DigitalMusicDeliveryService/HPS.m3u8?m=m&amp;amp;dmid=255568843&amp;amp;c=cf&amp;amp;f=ts&amp;amp;t=10&amp;amp;bl=256k&amp;amp;s=true&amp;amp;e1=1507309200000&amp;amp;e2=1507310100000&amp;amp;v=V2&amp;amp;h=30d9ff185871c09065bf2260d5e25a27b9311f3db0f3ae5a4936b738bd9ad74f&quot;/&gt;&lt;r:EnqueuedTransportURIMetaData val=&quot;&amp;lt;DIDL-Lite xmlns:dc=&amp;quot;http://purl.org/dc/elements/1.1/&amp;quot; xmlns:upnp=&amp;quot;urn:schemas-upnp-org:metadata-1-0/upnp/&amp;quot; xmlns:r=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot; xmlns=&amp;quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&amp;quot;&amp;gt;&amp;lt;item id=&amp;quot;-1&amp;quot; parentID=&amp;quot;-1&amp;quot; restricted=&amp;quot;true&amp;quot;&amp;gt;&amp;lt;dc:title&amp;gt;Alexa&amp;lt;/dc:title&amp;gt;&amp;lt;upnp:class&amp;gt;object.container.playlistContainer&amp;lt;/upnp:class&amp;gt;&amp;lt;desc id=&amp;quot;cdudn&amp;quot; nameSpace=&amp;quot;urn:schemas-rinconnetworks-com:metadata-1-0/&amp;quot;&amp;gt;&amp;lt;/desc&amp;gt;&amp;lt;upnp:albumArtURI&amp;gt;&amp;lt;/upnp:albumArtURI&amp;gt;&amp;lt;r:contentService id=&amp;quot;201&amp;quot; imageUrl=&amp;quot;https://s3.amazonaws.com/music-provider-logos/AmazonMusic.svg&amp;quot; name=&amp;quot;Amazon Music&amp;quot;&amp;gt;&amp;lt;/r:contentService&amp;gt;&amp;lt;/item&amp;gt;&amp;lt;/DIDL-Lite&amp;gt;&quot;/&gt;&lt;/InstanceID&gt;&lt;/Event&gt;</LastChange></e:property></e:propertyset>
`

**Comment by nlagaros** [comment]
Have you noticed missing title element when using Alexa to launch music?

**Comment by ghcs27** [comment]
@tagdara does #546 fix this for you?

**Comment by ghcs27** [comment]
Please reopen if this is still an issue.
