### ISSUE TITLE
Queue items have changed

### ISSUE THREAD

**Issue by slzatz** [SoCo/SoCo#535]
I recently updated to the latest version github version of SoCo and ran into this problem when trying to get information on items in the queue.

So using: `queue = master.get_queue()`
Previously the items in the the queue had properties that included album (=album title), title (=track title), and creator (=artist).  (note that version 0.11.1 supports this behavior.)

With the current version, there is a metadata property of the items in the queue but it appears to only contain the track title.

So my question is:  with whatever changes in data structures were made, is it possible to iterate through the items in the queue and get the album title, track title and artist?

Note that the items in the queue are coming from tracks stored in my amazon music account (not prime but tracks I own).

Thanks.

**Comment by slzatz** [comment]
Just checking since there has been no reply and would be helpful to know if:

1) the problem can't be confirmed
2) the change  in what is returned by `get_queue`  is not perceived to be a problem
3) the change is in the Sonos API and not the SoCo API
4) Something else

With some information, am happy to close the issue if there is nothing to be done.

Thanks,

Steve

**Comment by ghcs27** [comment]
Sorry for not answering. You are probably using a music service? If so, the problem is known, but fixing it while preserving new functionality is difficult. To get the old behavior back, you can use PR #559 (fork and pull, or just download from [relevitt:from_didl_string](https://github.com/relevitt/SoCo/tree/from_didl_string))

**Comment by KennethNielsen** [comment]
I have made an alternative fix in #589.

**Comment by slzatz** [comment]
Thanks for the responses- good to know there are a couple of options to fix the issue.
