### ISSUE TITLE
Art for favorites

### ISSUE THREAD

**Issue by maddox** [SoCo/SoCo#550]
I looked a bit, but couldn't find any info about this. 

It would be really nice to have the URIs of the art for the favorites/playlists. This would help in creating richer experiences with SoCo. Showing a thumbnail list of Favorites would feel way better than presenting just a list of strings.

**Comment by KennethNielsen** [comment]
I'm not sure if this is what you mean, but I think it is available:

```python
from soco.discovery import by_name

zone = by_name('Stue')

for favorite in zone.music_library.get_sonos_favorites():
    print(favorite.title)
    album_art_uri = favorite.album_art_uri

    # album_art_uri's for music library items, comes out as a realtive url, so we need to attach it to a speaker.
    if not album_art_uri.startswith('http'):
        album_art_uri = zone.music_library._build_album_art_full_uri(
            album_art_uri
        )
    print(album_art_uri)
    print()
```

Note, however, that the _build_album_art_full_uri is in the process of being made public, i.e. the leading underscore will disappear.

Does this cover your need?

**Comment by ghcs27** [comment]
Please reopen if this doesn't answer your question.
