### ISSUE TITLE
ghcs27 joins the team of maintainers

### ISSUE THREAD

**Issue by KennethNielsen** [SoCo/SoCo#560]
Hello everyone

Please help me in welcoming @ghcs27 to the maintainers team of SoCo/SoCo.

@ghcs27 has entered the SoCo project with enthusiasm and a high activity level. He has proposed and implemented enhancements as well as fixes and the changes he has proposed, has consistent been of good quality. Furthermore, he has shown an eagerness in getting to know the SoCo project and the tool-chain we use.

Furthermore, @ghcs27 is friendly and with good communication skills, which is a good quality for open source development.

Welcome to the team!

**Comment by DPH** [comment]
Welcome @ghcs27 - good to have you on board
Cheers David

**Comment by lawrenceakka** [comment]
Hi @ghcs27 👋

**Comment by stefankoegl** [comment]
Welcome!
