### ISSUE TITLE
How to add other music services with MusicService?

### ISSUE THREAD

**Issue by Flightkick** [SoCo/SoCo#564]
`print(MusicService.get_all_music_services_names())` returns only `['TuneIn']`

This device was able to play Spotify tracks with the stock Sonos app. But it is not listed with above command. Is it possible to add the Spotify music service and authenticate to Spotify with SoCo?
Could not find anything in the documentation.

**Comment by KennethNielsen** [comment]
Currently a lot of music services are unavailable for SoCo due to a change in the wat authentication with the music services is done by Sonos. We just (right after you opened this) added a section to the readme https://github.com/SoCo/SoCo/blob/master/README.rst that describes it.
