### ISSUE TITLE
404 on Album Art URI  

### ISSUE THREAD

**Issue by jeantristan** [SoCo/SoCo#571]
I can't manage to display Album Art using the URI from my music library (not a music service)

I use the following process:
`albums = device.music_library.get_music_library_information('albums',search_term="passant")
`
I get the first album of the list : 
`album = albums[0]`

Then I get the album art URI using 
`aa_uri = album.album_art_uri`

Then I use 
`device.music_library._build_album_art_full_uri(aa_uri)`

I have the following URI as a result:
`http://192.168.1.22:1400/getaa?u=x-file-cifs%3a%2f%2fbelle%2fdownloads%2fmusic%2fJean%2520Jacques%2520Goldman%2f12%2520-%2520En%2520passant%2520(1997)%2f01%2520-%2520Sache%2520que%2520je.mp3&v=503
`
Then I got a 404 page.

**Comment by ghcs27** [comment]
That's strange, your process works on my system, and the URI is similar.

**Comment by jeantristan** [comment]
I have several Sonos devices.
All the Sonos IP should be working ? Or I need to setup / initialize something ?

**Comment by ghcs27** [comment]
For me, all of them work.
Could you try if you can access `http://192.168.1.22:1400/status`?

**Comment by jeantristan** [comment]
Yeah. It's working. I can check the different items.
Mmm. Could it an encoding/escaping problem?

**Comment by jeantristan** [comment]
For information, if I browse http://192.168.1.22:1400/getaa, I have a 404 error.
Do you have the same behaviour?

**Comment by ghcs27** [comment]
Yes, that's a 404 for me too.

**Comment by jeantristan** [comment]
Hmm. And is it regular that "space" are encoded with %2520 and not only %20 ?
Do you have an example for your Sonos system please?

**Comment by ghcs27** [comment]
I have `http://192.168.123.7:1400/getaa?u=x-file-cifs%3a%2f%2fdigitus%2fsimone%2fVangelis%2f1492%2520-%2520Conquest%2520Of%2520Paradise%2f01-Vangelis%2520-%2520Opening.mp3&v=187`

**Comment by jeantristan** [comment]
Mmmm really strange, that it don't work for me. It seems the same pattern.

**Comment by jeantristan** [comment]
Ok I got it...
I was to used to Spotify, and that all album art are filled...
So... for your information, when there is no album art, you'll get a 404, and not a generic image.

Sorry :-(
