### ISSUE TITLE
MusicService('Spotify') not working for me

### ISSUE THREAD

**Issue by BerraKode** [SoCo/SoCo#572]
Actually I'm not getting response from any MusicService at all when I use:

print(MusicService.get_subscribed_services_names())

When I try to connect to spotify with: ----> play = MusicService("Spotify") <---- I get the following: 

Traceback (most recent call last):
  File "spotifyTest.py", line 10, in <module>
    play = MusicService("Spotify")
  File "/home/pi/Applications/Sonos/SoCo/soco/music_services/music_service.py", line 351, in __init__
    "No account found for service: '%s'" % service_name)
soco.exceptions.MusicServiceException: No account found for service: 'Spotify'

Is this a known issue or am I doing something wrong perhaps? Spotify works on my sonos system except here.

Thanks in advance!

-BerraKode

**Comment by ghcs27** [comment]
Please see the readme:

> WARNING
>
> Sonos has changed the way music service account information is available. This means that currently a group of music service will give authentication issues and cannot be used at all. Known members of this group are: Google Play Music, Apple Music, Amazon Music, Spotify and Napster.
>
> Issue #557 is a meta issue for this problem and you can use that to track progress on solving the issues, but please refrain from posting "me too" comments in there.

If I misunderstood your question, please reopen.

**Comment by BerraKode** [comment]
I misunderstood when I read that sorry. Thanks for all the good work!

**Comment by KennethNielsen** [comment]
No problem and thanks.
