### ISSUE TITLE
Release 0.15 (Feature freeze 29/4, final release 13/5)

### ISSUE THREAD

**Issue by stefankoegl** [SoCo/SoCo#579]
Summary
* Release notes: #578.
* Milestone: [0.15](https://github.com/SoCo/SoCo/milestone/11)
* Feature Freeze: evening of April 29 (see #581)
* Release date: May 12/13.

**Comment by stefankoegl** [comment]
I just realized that we're already past the feature freeze, and will be releasing in one week from now. Please make sure to get any bug fixes merged in time.

**Comment by DPH** [comment]
There is nothing stopping the merge of
 #602 In events module: allow choice in how the event server is implemented (v2) 
 @relevitt has done a lot of work on this.  Can we merge this?

Cheers David

**Comment by ghcs27** [comment]
@DPH I'm not sure, but I suppose that would be against the idea of the feature freeze.

**Comment by relevitt** [comment]
I'm confused. Is there anything I failed to do in time? I added this months ago to the thread of 0.15 features. What else do I need to do to get this included?

**Comment by DPH** [comment]
This was all tested and approved some time ago, so we should get it in!
The feature has been around for a long time, and has been ready - not a new feature.
I say we include if we can
Cheers David

**Comment by ghcs27** [comment]
@stefankoegl @KennethNielsen Can you please clarify if the feature freeze (#581) applies in this situation? I read it as no merge of feature PRs, regardless of approval.

@relevitt No, you did everything alright. It's just that we aren't as active as we'd have to be to review and merge PRs within one update cycle. I apologize that your PR is affected like this.

**Comment by stefankoegl** [comment]
#602 is a quite substantial change. I'd be hesitant to include it just days before the release. I'm not sure what @KennethNielsen thinks about this, but I'd prefer postponing it to the next one, even though if it means delaying a valuable contribution.

**Comment by stefankoegl** [comment]
I'll start to create the release now.

**Comment by stefankoegl** [comment]
SoCo 0.15 has been released 🎉

* [PyPI package](https://pypi.org/project/soco/0.15/)
* [GitHub release](https://github.com/SoCo/SoCo/releases/tag/v0.15)
* [Release notes](http://docs.python-soco.com/en/v0.15/releases/0.15.html)
* [Commit log](https://github.com/SoCo/SoCo/compare/v0.14...v0.15)

This release had 57 commits by 7 authors.

Thanks to @hugovk, @philippkeller, @ghcs27, @KennethNielsen and @amelchio for the contributions!

**Comment by stefankoegl** [comment]
@ghcs27 sorry, I missed that. if necessary I can prepare a 0.15.1 in the next couple of days. Do you think that makes sense?

**Comment by ghcs27** [comment]
It might be for the best we didn't do a merge seconds before the release.

0.15.1 sounds like a good idea – but IMHO we should try to include some more of the PRs from [my list above](https://github.com/SoCo/SoCo/issues/579#issuecomment-386867385).

**Comment by hugovk** [comment]
By the way, the Release Procedures say to follow semver, so new features would warrant a minor version bump to 0.16.

https://github.com/SoCo/SoCo/blob/master/doc/development/release-howto.rst
