### ISSUE TITLE
Status light not possible to change?

### ISSUE THREAD

**Issue by BerraKode** [SoCo/SoCo#603]
I read that you should be able to manually change the status of the led light on top of the speakers.
But all I can do is get the status of the light, not change it. Has this function been removed or am I missing something? 

Best regz

BerraKode

**Comment by KennethNielsen** [comment]
How did you try to change it?

**Comment by BerraKode** [comment]
I can get the status with "status_light" but status_light(True) generate an error. I have seen this should be possible in the documentation from some older version

**Comment by DPH** [comment]
Hi @BerraKode ,
status_light is a property so use
```
import soco
s = soco.SoCo('192.168.1.23')
s.status_light = True
```
Cheers David

**Comment by BerraKode** [comment]
Ahh thanks!
