### ISSUE TITLE
"Error in workflow hu.fns.soco_alfred"

### ISSUE THREAD

**Issue by LETRA** [SoCo/SoCo#608]
Good night. I don't know what's wrong here and Google doesn't find anything. Any help?

**Comment by ghcs27** [comment]
Is there any traceback? What code do you use to call SoCo?
This message seems to come from another part of your program, so it is of no use to us.

**Comment by LETRA** [comment]
It's a call from the Sonos workflow for Alfred. The message appears when I enter the scs command.

**Comment by ghcs27** [comment]
I'm sorry, you'll have to ask the maintainers of "Sonos workflow for Alfred". We have no information about their code.

If they can't help you, try installing an older version of SoCo, probably 0.12 has the best chance of working.
