### ISSUE TITLE
Create stereo pair

### ISSUE THREAD

**Issue by lwis** [SoCo/SoCo#612]
Apparently SonoSequencr is able to create a stereo pair from any two speakers (despite the Sonos app not allowing it). Does SoCo expose any stereo pairing functionality, or surround setup functionality today?

**Comment by DPH** [comment]
Hi @lwis ,
at present SoCo doesn't expose this functionality. 
There appears to be UPnP calls for it in the Sonos devices, but have not looked at how that would work, or what parameters are required. If you wanted to try and work it out it could be added.
Cheers David

**Comment by ghcs27** [comment]
There are
```
DeviceProperties:CreateStereoPair(ChannelMapSet: str)
DeviceProperties:SeparateStereoPair(ChannelMapSet: str)
```
methods exposed by the Sonos API. However, we don't know how to fill the ChannelMapSet parameter.
