### ISSUE TITLE
discover() randomly fails

### ISSUE THREAD

**Issue by Evla03** [SoCo/SoCo#615]
soco just works for me sometimes, my sonos controller on my pc detects the devices but not soco. soco.discover() returns None

**Comment by ghcs27** [comment]
Thank you for the report. 
This seems like another instance of issue #384, which is known but of unclear origin. 
How is your network set up? Are you using a VPN?

**Comment by Evla03** [comment]
I’m not using a VPN, but 2 access points are connected to the network, I have 4 PLAY:1 and one bridge (where one play is connected to Ethernet and the bridge is also connected to Ethernet, all other speakers are connected to WiFi) The pc i’m using soco on is connected to Ethernet

**Comment by Evla03** [comment]
I fixed the problem temporaly by inactivating and activating my network card. After about 10 minutes it didn't work again.

**Comment by ghcs27** [comment]
Hm, that's strange.
Do you have Wireshark?

**Comment by Evla03** [comment]
Yes I have

**Comment by ghcs27** [comment]
Another question: Do you happen to have more than one network adapter?

**Comment by ghcs27** [comment]
VMware... That's interesting! For me, discover() only works reliably if I deactivate my VirtualBox network adapter. You should definitely try out deactivating your VMware adapter.

**Comment by Evla03** [comment]
![2018-05-18_21-51-55](https://user-images.githubusercontent.com/29502264/40254960-ba48ab9a-5ae5-11e8-8013-bfdab7396668.png)
(i had 7 network adapters...)

**Comment by Evla03** [comment]
Here is the results:
[capture.txt](https://github.com/SoCo/SoCo/files/2018428/capture.txt)

**Comment by Evla03** [comment]
Disabling the network adapters made it work i think

**Comment by Evla03** [comment]
Now the sonos controller says it cannot connect to spotify when i tried to play a song but my script worked

**Comment by Evla03** [comment]
tried using soundcloud, error 701when trying to play..
one of our access points are a bit glitched right now, i think that has to do with that, not with soco.

**Comment by Evla03** [comment]
i'll close the issue, i think that disabling the network adapters made soco work, now i'll just try to fix my local network. Thank you for the help!
