### ISSUE TITLE
Is there a way to use a music service with soco if I have the username and password?

### ISSUE THREAD

**Issue by airsquared** [SoCo/SoCo#617]
I'm aiming to search for and play songs from Apple Music.

**Comment by ghcs27** [comment]
IIRC, we currently don't support this, but we aim to make this possible in the near future.

**Comment by airsquared** [comment]
@ghcs27 Have you implemented this feature?

**Comment by ghcs27** [comment]
Sorry, progress on the music service issue is slow. The main discussion is at #557, but just working out a concept of how to tackle the problem, regardless of whether we know the password, seems to be a long way to go.
