### ISSUE TITLE
Can I use SoCo to change input on my Sonos Connect?

### ISSUE THREAD

**Issue by mlindgren80** [SoCo/SoCo#620]
I was scanning through the documentation, and I didn't see a section for specifying the input on a Sonos connect device, or Play:5 for that matter.  I often use the Sonos Connect Line-In to stream Chromecast Audio to Sonos and an easy way of setting the input would be much appreciated!

**Comment by DPH** [comment]
Hi @mlindgren80,
I used this some time ago - it is device.switch_to_line_in()

The link to documentation is: http://docs.python-soco.com/en/stable/api/soco.core.html?highlight=switch_to_line_in#soco.core.SoCo.switch_to_line_in

Give it a try and let us know if OK.
Cheers David

**Comment by mlindgren80** [comment]
Yes it works, thanks 👍 

What I hadn't anticipated was that in doing so, the connect leaves the main group of speakers, so I have to get the rest of the speakers to join the connect which is playing from the line-in.

**Comment by DPH** [comment]
You can in theory use device.switch_to_line_in() and specify which devices line-in. 
The reason I suggest this is if you change the master (co-ordinator)  of the group to play the line in of whatever devices line in you want then it shouldn't leave the group. 
A player leaves a group if it is a slave and you give it a new source, so it becomes its own master (co-ordinator). 
By changing the source of the current coordinator I expect it will not change the groupings. 

Any device can give you the co-ordinator of the group it is in: device.group.coordinator returns a soco instance. You could then change that device to play the line in from another device. For example: ```device.group.coordinator.switch_to_line_in(Soco instance of devices line in required)```

Let us know if this works and is useful
Cheers David
