### ISSUE TITLE
Unkown Attribute Error when listing queue from some music services

### ISSUE THREAD

**Issue by c-nixon** [SoCo/SoCo#622]
get_queue in core.py often fails with an Attribute error when a track from soundcloud is on the playlist.

Replacing
```python
track.creator,
track.title,
track.album,
```
with 

```python
getattr(track, "creator", ""),
getattr(track, "title", ""),
getattr(track, "album", ""),
```

fixes the problem, but this is a bit messy.

I'm happy to put in a PR for this, but would like suggestions as what people think is the best to fix it.

**Comment by ghcs27** [comment]
Thank you for reporting this bug, seems like we don't handle missing metadata correctly. 
Can you please post the error message here?
In which lines did you apply your substitution?

**Comment by c-nixon** [comment]
Whoops, seems I've reported the error in the wrong repo. I should have reported it on SoCo/socos. Sorry about that, will re-report over there.
