### ISSUE TITLE
Getting Volume Status

### ISSUE THREAD

**Issue by Kenoi** [SoCo/SoCo#623]
Is it possible to get the volume level of a speaker?

**Comment by ghcs27** [comment]
Yes, this is indeed possible. If you already have the SoCo object for your player, you can use `player.volume` to get the volume level. It is a property, which means you can read and assign it like a variable: 
```python
vol = player.volume
player.volume = vol+2
```
Please take a look at the [documentation](https://soco.readthedocs.io/en/latest/api/soco.core.html#soco.core.SoCo.volume) for more information.

**Comment by Kenoi** [comment]
Thank you very much that worked great.
