### ISSUE TITLE
Did events_twisted (#602) make  it into release 0.16?

### ISSUE THREAD

**Issue by nlagaros** [SoCo/SoCo#631]
I do not see the code in there  - or I am missing  something.

**Comment by nlagaros** [comment]
No  - I  guess I pulled it before  you made the changes.  I'm more  interested in why it wasn't included.   I've been hoping for many  months to get this update.

**Comment by stefankoegl** [comment]
I haven't been following the development of #602, but I've asked for a summary of missing steps to get it merged.

**Comment by relevitt** [comment]
I've commented on this in #602 (and sorry for being slow).

**Comment by relevitt** [comment]
#602 should be good to merge now.

**Comment by KennethNielsen** [comment]
@nlagaros it is now finally merged and will be released along with version 0.16 #666
