### ISSUE TITLE
FutureWarning using Python 2.7...

### ISSUE THREAD

**Issue by reneklomp** [SoCo/SoCo#632]
pi@raspberrypi:~ $ python
Python 2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import soco
>>> soco.discover()
/home/pi/.local/lib/python2.7/site-packages/soco/services.py:687: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
  value_list_elt = state.find('{}allowedValueList'.format(ns))\
set([SoCo("192.168.1.197"), SoCo("192.168.1.103"), SoCo("192.168.1.102")])
>>>

**Comment by MarvinSkilla** [comment]
Ya, got the same warning.  Hope, they fix it.

**Comment by ghcs27** [comment]
It seems like this warning can safely be ignored, so I'll close this. If i'm mistaken or if it causes problems, please reopen.
