### ISSUE TITLE
How to lookup audiobook items from sonos-favorites

### ISSUE THREAD

**Issue by Nibbler73** [SoCo/SoCo#634]
I'm building a RPI based sonos controller with RFID card interfaces.
To make sonos play a stream I need to send it the stream-uri e.g. `x-sonosapi-stream:s25217?sid=254&flags=8224&sn=0`.

To find out what the sonos uri looks like, I create a favorite with the Sonos App and then list the favorites with their name and resources:

```python
musiclib = device.music_library.get_music_library_information('sonos_favorites')
for fav in musiclib:
  print(fav.title)
  for item in fav.resources:
    print(item)
```

This works for playlists and audio streams like TuneIn or Amazon Audio. But audiobooks from the favorites are not listed there. Specifically I am trying to find the uri of my Audible audiobooks.

An alternative approach was to output whats currently playing on the speaker:

```python
devices = soco.discover()
for player in devices:
  print(player.player_name)
  print(player.get_current_track_info())
```

But this only lists the currently played item (e.g. the current chapter of the audiobook), not the actual book.

Is this supported by SoCo, or is there another way to lookup the stream uri?

**Comment by DPH** [comment]
Yes try:
```
import soco

device = soco.SoCo('192.168.1.23')
print(device.player_name)

# Get information about the currently playing media
media_info = device.avTransport.GetMediaInfo([('InstanceID', 0)])
media_uri = media_info['CurrentURI']


# Extract source from media uri - below some media URI value examples:
#  'x-rincon-queue:RINCON_000E5859E49601400#0'
#       - playing a local queue always #0 for local queue)
#
#  'x-rincon-queue:RINCON_000E5859E49601400#6'
#       - playing a cloud queue where #x changes with each queue)
#
#  -'x-rincon:RINCON_000E5859E49601400'
#       - a slave player pointing to coordinator player

print(media_uri)
```
The av_transport_uri tells where the music is coming from (eg a queue, another sonos zone, a radio broadcast or a uri /http one off source), and the track_uri tells what track is currently being played.

This code used in Snapshot in SoCo
Hope this helps

Cheers David

**Comment by Nibbler73** [comment]
Thanks for the response.
This most probably answers my question, at least I am getting some `x-rincon...` response. Need to wait for #557 before I can continue testing.
