### ISSUE TITLE
deviceProperties.Get and Set

### ISSUE THREAD

**Issue by pascal1503** [SoCo/SoCo#642]
Hello what does the query look like for GetAutoplayRoomUUID? And how for SetAutoplayRoomUUID?

For GetAutoplayRoomUUID it works like this:
device.deviceProperties.GetAutoplayRoomUUID ([('InstanceID', 0)])

But I can not change the value with set. Can someone give me a fitting example?

**Comment by ghcs27** [comment]
That's strange - it works for me. What I did was:
```python
device.deviceProperties.SetAutoplayRoomUUID(RoomUUID=device.uid)
```

**Comment by pascal1503** [comment]
Thanks the lower one works.
