### ISSUE TITLE
Flake8 "Line break after binary operator" warning

### ISSUE THREAD

**Issue by ghcs27** [SoCo/SoCo#647]
Flake8 has started complaining about existing code:
```
soco/core.py:1279:37: W504 line break after binary operator
soco/core.py:1765:21: W504 line break after binary operator
soco/core.py:1766:21: W504 line break after binary operator
soco/plugins/spotify.py:32:9: W504 line break after binary operator
```
Line numbers refer to the version in [this tree](https://githubu.com/SoCo/SoCoo/tree/32c4df366396e84c220267cfb909f0cbb22a8ae9).

Example error line:
```python
return (int(times[0]) * 3600 +
        int(times[1]) * 60 +
        int(times[2]))
```
We should probably fix this by moving the operator to the next line (?).

**Comment by KennethNielsen** [comment]
For now fixed by #654 by ignoring the warning. If we ever grow and insane amount of time, we can review pylint disables.
