### ISSUE TITLE
0.17 Release?

### ISSUE THREAD

**Issue by nlagaros** [SoCo/SoCo#652]
Will this be packaged up anytime soon?

**Comment by nlagaros** [comment]
is the project abandoned?

**Comment by btannous** [comment]
:+1: 
I could pull from master but I've been looking for the .17 release to get night mode compatibility on my soundbar.

**Comment by btannous** [comment]
#630 and #629 seem to indicate it should have been released in November.  Wonder whats up?

**Comment by stefankoegl** [comment]
I wouldn't say that the project is abandoned, but I simply didn't have enough time to do a release - it wasn't high enough on my priority list. I'll try to do a review of the currently merged and opened pull request, and see if I can do a release soon.

**Comment by nlagaros** [comment]
I am also looking for the .17 release.  I'm not sure that I can pull it myself.  If you are able to get that released, many here would appreciate it.  Thank you.

**Comment by KennethNielsen** [comment]
@nlagaros no, the project is not abandoned, just got busy with real life. @stefankoegl I will try to coordinate the fall out from the new Sonos release and then we should do a bug fix release thereafter. If you have time, great, otherwise we will have to figure out to get me access to PyPI.

**Comment by nlagaros** [comment]
I appreciate your time on this.  I’m most interested in events_twisted (#602) getting merged into this release.

**Comment by KennethNielsen** [comment]
@nlagaros I think, from a 5 sec glance at it, that #602 uses the two file approach to twisted events, which I think has received about as much feedback as it should. So I will have a look at that as well tonight.

**Comment by KennethNielsen** [comment]
@stefankoegl ok, so I actually got the credentials to make a release on PyPI, so I will make one when we have the necessary fixes for the 10.1 update.

**Comment by KennethNielsen** [comment]
I will try and make a release today.

**Comment by btannous** [comment]
Wooo! Awesome guys!  I completely understand real life though.  Thanks again for the support!

/lgtm

**Comment by KennethNielsen** [comment]
We have had a few releases since this. Closing.
