### ISSUE TITLE
Unknown UPnP class: object.item.audioItem.musicTrack.recentShow

### ISSUE THREAD

**Issue by psjoholm** [SoCo/SoCo#655]
After adding a podcast episode I got problem with 'Unknown UPnP class: object.item.audioItem.musicTrack.recentShow', when doing get_queue()
The raw data looked like this (... means removed part of queue):
```
<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconn
...
<item id="Q:0/45" parentID="Q:0" restricted="true">
<res protocolInfo="sonos.com-rtrecent:*:audio/x-sonos-recent:*" duration="0:37:58">x-sonosapi-rtrecent:t128787601%3ap929112?sid=254&amp;
<upnp:albumArtURI>/getaa?s=1&amp;amp;u=x-sonosapi-rtrecent%3at128787601%253ap929112%3fsid%3d254%26flags%3d8224%26sn%3d0</upnp:albumArtUR
<dc:title>61. Lagos to Maui</dc:title>
<upnp:class>object.item.audioItem.musicTrack.recentShow</upnp:class>
<dc:creator>Hannibal Buress</dc:creator>
<upnp:album>Hannibal Buress: Handsome Rambler</upnp:album>
</item>
</DIDL-Lite>
```

By looking at other code in data_structures.py I created a new class which solved my specific problem, but I am not sure this is the proper way. #616 refers to a property table found at upnp.org. However, I could not find any such table for recentShow.
```
class DidlRecentShow(DidlAudioItem):

    """Class that represents a recent radio show/podcast."""

    # the DIDL Lite class for this object.
    item_class = 'object.item.audioItem.musicTrack.recentShow'
    # name: (ns, tag)
    _translation = DidlAudioItem._translation.copy()
    _translation.update(
        {
            'artist': ('upnp', 'artist'),
            'album': ('upnp', 'album'),
        }
    )
```

**Comment by psjoholm** [comment]
Thanks for fixing this, I didn't really know what I was doing and made a fix by guessing.
No worries about the time, I have been running my private version in the meantime. Exciting to be able to contribute even in a small manner.

I tested this commit and it works fine.

**Comment by psjoholm** [comment]
Sorry about being new to github, am I supposed to close this ticket now?

**Comment by KennethNielsen** [comment]
I'm glad to hear that it works. Don't sweat it about Github, we were all new at some point.

Since this issue is essentially a feature request, it should stay open until either the feature request is implemented or rejected. On a side note, Github knows some magic tricks, so since I wrote in the commit message that the commit closes this issue it will happen automatically when the PR is merged.
