### ISSUE TITLE
Receive Microphone Input

### ISSUE THREAD

**Issue by MitchSteed** [SoCo/SoCo#657]
My Sonos has an inbuilt microphone, is there a way that anyone knows to "listen" to the microphone such that I can basically write my own virtual assistant? Does this library support that functionality already?

**Comment by ghcs27** [comment]
Sonos unfortunately doesn't seem to offer this functionality via the UPnP API.

Here's a list of function calls which the Sonos players accept:
https://github.com/SoCo/SoCo/wiki/Sonos-UPnP-Services-and-Functions
None of them appear to be related to microphone input.

**Comment by MitchSteed** [comment]
Ok, thanks for the link to the wiki! Was curious if anyone had already found a solution to this.
