### ISSUE TITLE
Saving multiple alarms quickly fails

### ISSUE THREAD

**Issue by davidtorosyan** [SoCo/SoCo#659]
I've got two alarms, and if I try to enable them both like so:
```py
import soco
import soco.alarms
alarms = soco.alarms.get_alarms()
for alarm in alarms:
    alarm.enabled = True
    alarm.save()
```
Usually only one of them actually gets updated. If I introduce a short delay in the loop:
```py
import time
time.sleep(0.1)
```
They both get saved successfully.

I'm not sure what the fix for this would be, and the workaround is easy enough. Thought I'd post this here in case others hit the same issue.

**Comment by pwt** [comment]
Thanks for capturing this.

I haven't personally been able to reproduce this in my testing while working on alarms support for [SoCo-CLI](https://github.com/avantrec/soco-cli) recently, so it's possible that Sonos has addressed this in a f/w change. Hence, I'm going to close it for now.
