### ISSUE TITLE
Group broken by Sonos version 10.1

### ISSUE THREAD

**Issue by rleeden** [SoCo/SoCo#660]
I updated my Sonos to version 10.1 today and noticed that some of my scripts that rely on SoCo seem to have broken.

Seems to be a problem with groups. When trying to find coordinator of a group with

**device.group.coordinator.player_name**

I get error:

`Traceback (most recent call last):
  File "./test", line 7, in <module>
    print(device.group.coordinator.player_name)
AttributeError: 'NoneType' object has no attribute 'coordinator'`

and **print(device.group)** just gives output of:

`None`

I'm assuming this is the 10.1 upgrade. Does anybody else see this, and know if it is fixable?

**Comment by pmatos** [comment]
Same here. `soco.discover()` returns the empty set.

**Comment by rleeden** [comment]
It looks like the information is still there. Doing a tcpdump whilst running soco.discover() on my 4 speaker system shows this:

```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <s:Body>
    <u:GetZoneGroupStateResponse xmlns:u="urn:schemas-upnp-org:service:ZoneGroupTopology:1">
      <ZoneGroupState>
        <ZoneGroupState>
          <ZoneGroups>
            <ZoneGroup Coordinator='RINCON_347E5C19199001400' ID='RINCON_B8E93799BB7A01400:3441'>
              <ZoneGroupMember UUID='RINCON_B8E93799BB7A01400' Location='http://192.168.0.66:1400/xml/device_description.xml' ZoneName='Living Room' Icon='x-rincon-roomicon:living' Configuration='1' SoftwareVersion='49.2-63270' MinCompatibleVersion='48.0-00000' LegacyCom
patibleVersion='36.0-00000' BootSeq='152' TVConfigurationError='0' HdmiCecAvailable='0' WirelessMode='1' WirelessLeafOnly='0' HasConfiguredSSID='1' ChannelFreq='2452' BehindWifiExtender='0' WifiEnabled='1' Orientation='0' RoomCalibrationState='4' SecureRegState='3' Voice
ConfigState='0' MicEnabled='0' AirPlayEnabled='0' IdleState='0' MoreInfo=''/>
              <ZoneGroupMember UUID='RINCON_949F3E154D0001400' Location='http://192.168.0.70:1400/xml/device_description.xml' ZoneName='Bathroom' Icon='x-rincon-roomicon:bathroom' Configuration='1' SoftwareVersion='49.2-63270' MinCompatibleVersion='48.0-00000' LegacyComp
atibleVersion='36.0-00000' BootSeq='131' TVConfigurationError='0' HdmiCecAvailable='0' WirelessMode='1' WirelessLeafOnly='0' HasConfiguredSSID='1' ChannelFreq='2452' BehindWifiExtender='0' WifiEnabled='1' Orientation='0' RoomCalibrationState='1' SecureRegState='3' VoiceC
onfigState='0' MicEnabled='0' AirPlayEnabled='0' IdleState='0' MoreInfo=''/>
              <ZoneGroupMember UUID='RINCON_5CAAFD432E9401400' Location='http://192.168.0.69:1400/xml/device_description.xml' ZoneName='Bedroom' Icon='x-rincon-roomicon:bedroom' Configuration='1' SoftwareVersion='49.2-63270' MinCompatibleVersion='48.0-00000' LegacyCompat
ibleVersion='36.0-00000' BootSeq='197' TVConfigurationError='0' HdmiCecAvailable='0' WirelessMode='1' WirelessLeafOnly='0' HasConfiguredSSID='1' ChannelFreq='2452' BehindWifiExtender='0' WifiEnabled='1' Orientation='0' RoomCalibrationState='1' SecureRegState='3' VoiceCon
figState='0' MicEnabled='0' AirPlayEnabled='0' IdleState='0' MoreInfo=''/>
              <ZoneGroupMember UUID='RINCON_347E5C19199001400' Location='http://192.168.0.71:1400/xml/device_description.xml' ZoneName='Kitchen' Icon='x-rincon-roomicon:kitchen' Configuration='1' SoftwareVersion='49.2-63270' MinCompatibleVersion='48.0-00000' LegacyCompat
ibleVersion='36.0-00000' BootSeq='24' TVConfigurationError='0' HdmiCecAvailable='0' WirelessMode='1' WirelessLeafOnly='0' HasConfiguredSSID='1' ChannelFreq='2452' BehindWifiExtender='0' WifiEnabled='1' Orientation='0' RoomCalibrationState='4' SecureRegState='3' VoiceConf
igState='0' MicEnabled='0' AirPlayEnabled='0' IdleState='0' MoreInfo=''/>
            </ZoneGroup>
          </ZoneGroups>
          <VanishedDevices></VanishedDevices>
        </ZoneGroupState>
      </ZoneGroupState>
    </u:GetZoneGroupStateResponse>
  </s:Body>
</s:Envelope>
```

I'm guessing the format has changed? Unfortunately my python coding is very poor so looking at the code is not helping me figure this out.

**Comment by clovenguth** [comment]
I work in the home automation industry and can tell you 10.1 broke all 3rd party control of Sonos as of yesterday's 10.1 update who weren't ready for it. All the big control companies are scrambling to make a fix. Sonos had been warning this API overhaul for awhile.

**Comment by jnth** [comment]
I found a fix that work in my small network sonos system.

    --- soco/core.py	(revision 671937e07d7973b78c0cbee153d4f3ad68ec48c6)
    +++ soco/core.py	(date 1554404884029)
    @@ -949,7 +949,7 @@
             self._all_zones.clear()
             self._visible_zones.clear()
             # Loop over each ZoneGroup Element
    -        for group_element in tree.findall('ZoneGroup'):
    +        for group_element in tree.find('ZoneGroups').findall('ZoneGroup'):
                 coordinator_uid = group_element.attrib['Coordinator']
                 group_uid = group_element.attrib['ID']
                 group_coordinator = None

I'm not sure if the `ZoneGroups` is not multiple.

**Comment by DrKeks** [comment]
Same problem here. Very disappointed enduser of "RFID - Raspberry PI - SoCo" controller (my 3,5 year old daughter). Will there be a fix for this in the near future?

Right now only setting the volume works, but even start and stop playing is not possible using a call by SoCo('ip-of-speaker').

@jnth : can you please explain that fix, is it a part of the soco files that contains this code?

**Comment by eduhh94** [comment]
I have the same problem. Unfornately this was my first time using it and it's broken.

**Comment by clovenguth** [comment]
@jnth bravo!

Editing this line worked for me as well.

**Comment by rleeden** [comment]
@jnth - great, your fix works for me - thanks

@DrKeks - yes, this is part of the soco files. Find where your installation is. Mine is in /usr/lib/python3.6/site-packages/soco, but yours might vary depending on python version and general set-up. You are specifically looking for a file called core.py. Copy the patch code from @jnth's post above and paste it in a file called **patch.txt** in the directory you've just found. Then run:

 **patch < patch.txt**

**Comment by rudyvan** [comment]
fix does not work if you are using a sonos boost, with https://github.com/home-assistant/netdisco  the sonos discovery only returns the sonos boost not the sonos devices behind them.
I think this issue is more serious than we assume now to fix.

**Comment by nlagaros** [comment]
I’m not sure this is a function of the recent change in 10.1, but looking through code, there is no provision for the Boost that I see.

**Comment by peyronson** [comment]
Fix worked for mee too, thanks alot @jnth!

**Comment by jeffehobbs** [comment]
@jnth's fix worked for me, nice work!

**Comment by alavela** [comment]
@jnth's fix worked for me as well! Any plan to have 0.17 release including compatibility with new Sonos API?

**Comment by jasontaylor190** [comment]
@jnth is a life-saver! I use this python module for a script I run every night to setup specific playlists for my girls at bed time with sleep timers pre-set. This fixed me up with 10.1!!! Thx @jnth!!!

**Comment by Renfield63** [comment]
@jnth Wins The Internet.  
I've been wondering how long it would take before Sonos broke SoCo.  Thanks to @jnth my sorrow was short-lived!  Great fix and thanks to @rleeden for the directions!

**Comment by gdinkanata** [comment]
Fixed worked on my system, and I running a Boost

**Comment by rudyvan** [comment]
Fixed worked here also, even though i have a boost.
Apologies for my previous message saying didn't work.

**Comment by ve7gel** [comment]
Worked for me too using the Sonos nodeserver on Universal Devices' polyglot.

**Comment by mrusme** [comment]
Anyone an idea when this will make it into a PyPi release? Asking for a friend.

**Comment by amb5l** [comment]
@jnth's fix worked for me: large system of 2016 Sonos hardware controlled from complex, threaded script (Python 3.7 64 bit on Windows 10)

**Comment by KennethNielsen** [comment]
I merged the fix as applied in #662. I will see about doing a release fast.

**Comment by KennethNielsen** [comment]
If anyone is still having issues with master at point https://github.com/SoCo/SoCo/commit/149c6b505f992564cfe0432c40c03f9952ac82c1 or above, please file separate issues.

**Comment by realwakils** [comment]
@jnth tysm i've been pulling my hair trying to figure out why soco.discover() returned None. thaanks!

**Comment by ItsDario7** [comment]
@realwakils Hello, I am alsow trying to fix this, but i just cant get the patch.txt file runing...
Can you show me how it is done?

**Comment by pwt** [comment]
As well as switching the input to Line In, make sure you're also instructing the device to play().

**Comment by ItsDario7** [comment]
@pwt Thank you for the fast help. But it still won't work for some reason...

My Code:
```
from soco.discovery import by_name
device = by_name("ItsDario")
device.volume = 85
device.switch_to_line_in()
device.play()

```

**Comment by pwt** [comment]
Your code looks fine to me; not sure why it's not working nor why you're seeing the source name difference. I'm not seeing that behaviour.

**Comment by ItsDario7** [comment]
@pwt Thanks for the help anyways (: Have a great day! I will hopefully find a solution somewhere.

**Comment by pwt** [comment]
You could install my SoCo CLI library instead, just to test if the behaviour is the same:

```
> pip install soco-cli
> sonos ItsDario vol 85 : ItsDario line_in on : ItsDario play
```

**Comment by ItsDario7** [comment]
When I try to run that it says: **Speaker 'ItsDario' not found**

**Comment by pwt** [comment]
Could you run `sonos-discover` and supply the output, please? Thanks.

**Comment by ItsDario7** [comment]
![image](https://user-images.githubusercontent.com/72466771/95252421-433bd300-081d-11eb-9dbe-f302fbad0d27.png)

**Comment by pwt** [comment]
Thanks. To which speaker (left or right) is your Line In device (Dario) attached?

**Comment by ItsDario7** [comment]
![Uploading image.png…]()

**Comment by pwt** [comment]
That's the problem. The SoCo code is assuming Line In is the default (left speaker) input. Try the following, where `$X` is the IP address of your right hand speaker:

`sonos ItsDario vol 85 : ItsDario line_in $X : ItsDario play`

**Comment by ItsDario7** [comment]
That solved my Problem! Thank you very much (: 👍 Have an awsome day!

**Comment by pwt** [comment]
Great. In case it's not obvious, if you want to do it in Python, you need to modify your code as follows:

```
from soco.discovery import by_name
device = by_name("ItsDario")
device.volume = 85
right_speaker = by_name("IP address of right speaker")
device.switch_to_line_in(right_speaker)
device.play()
```

**Comment by ItsDario7** [comment]
I have one more Question. Can i run that when my PC starts? Would be awsome, just couldn't find how to do it, thats why i came back here haha

**Comment by pwt** [comment]
I don't use Windows very often, but I suspect you'd need to use the Windows Task Scheduler, triggering execution on your desired event(s).

**Comment by ItsDario7** [comment]
I am using pyCharm to make the Script. Now i want to use the script without needing to go in to the editor and run the script. How do i run it without the editor?
I have tryed to run the file itself and i have tryed to run the file with the Windows Terminal...

**Comment by pwt** [comment]
From the Windows terminal, use `python <your_program_name.py>`. This assumes that your system Python environment is set up appropriately and contains the required packages (SoCo, etc.).

If it's not, you'll first need to determine which Python installation is being used within PyCharm.

**Comment by ItsDario7** [comment]
![image](https://user-images.githubusercontent.com/72466771/95361747-6cb43780-08cd-11eb-9fed-68821bc33b5a.png)

**Comment by ItsDario7** [comment]
same here 
![image](https://user-images.githubusercontent.com/72466771/95361907-9cfbd600-08cd-11eb-812b-897ab421997a.png)

**Comment by pwt** [comment]
In thet case, Pycharm is probably using a **venv**, which you will need to activate in the Windows terminal before running your program. If you Google `Python Virtualenv`, that should get you on the right track.

Alternatively, in the Windows terminal, you can try `pip install soco`, which will install the SoCo package in your system Python. Then try running your program again.

**Comment by ItsDario7** [comment]
I had to install pip in the normal python terminal and after that i could install soco.
Now i can run the python file. (:  It will alsow run on my computer startup now. 
Thank you soo much for the Help!

**Comment by Phill030** [comment]
any fix for now?
