### ISSUE TITLE
Coordination of fall out from Sonos 10.1

### ISSUE THREAD

**Issue by KennethNielsen** [SoCo/SoCo#664]
Hi everyone

So I'm back and will try and coordinate a new release that fixes the (most urgent) fall out from the Sonos 10.1 release, but I will need some help in getting an overview.

I merged #662 as a fix for #660.

Are there any other issues related to the Sonos 10.1 release. Probably the easiest way to see that it is related, is that  the issue started after the update.

Please post below.

**Comment by amelchio** [comment]
There are no other issues related to that update but #662 will break with pre-10.1 firmware, I don't know if that is a problem.

I fixed it in a backwards compatible way in amelchio/pysonos#13 (though I now see that I made a typo in the comment).

**Comment by maru-sama** [comment]
Hello, can you please also consider adding pull request #589 to the new release, since I tend to really forget to do this changes manually when a new version is released.

**Comment by KennethNielsen** [comment]
@amelchio would you consider making a PR for you backwards compatible approach on top of current master, then I will pull that right away. Remember to put comments in there about what should be removed in the future (say a year from now) when everyone should have upgraded.

**Comment by KennethNielsen** [comment]
@maru-sama I will have a look tonight and see about including it.

**Comment by amelchio** [comment]
Sorry, there actually is another issue: certain favorites started to break `music_library.get_sonos_favorites()`. A traceback [is here](https://github.com/home-assistant/home-assistant/issues/22714#issuecomment-480942373), with steps to reproduce a little bit further down.

I am not making PRs, just wanted to give a heads up since I already handled the 10.1 update in my fork.

**Comment by KennethNielsen** [comment]
Ok. So I have very little time to work on this. I will make time to review and pull PR's but I will not have time to work on fixes. So if anyone wants to work on the issue @amelchio mentioned, fell free to dive in.

@amelchio I didn't quite understand. Is there also a fix for the favorites issue in your fork?

**Comment by KennethNielsen** [comment]
I think, a little bit wiser from previous experience, I will not pull any large functionality additions in for this release, since they should be tested more and this should get out quickly.

**Comment by amelchio** [comment]
This is my fix. I assume just ignoring the entry is not up to your standards and I do not want to spend time on a more complete solution.
```diff
--- a/pysonos/data_structures_entry.py
+++ b/pysonos/data_structures_entry.py
@@ -49,9 +49,12 @@ def from_didl_string(string):
                 cls = _DIDL_CLASS_TO_CLASS[item_class]
             except KeyError:
                 raise DIDLMetadataError("Unknown UPnP class: %s" % item_class)
-            item = cls.from_element(elt)
-            item = attempt_datastructure_upgrade(item)
-            items.append(item)
+            try:
+                item = cls.from_element(elt)
+                item = attempt_datastructure_upgrade(item)
+                items.append(item)
+            except DIDLMetadataError as ex:
+                _LOG.info("Ignored '%s' on %s", ex, XML.tostring(elt))
         else:
             # <desc> elements are allowed as an immediate child of <DIDL-Lite>
             # according to the spec, but I have not seen one there in Sonos, so
```

**Comment by KennethNielsen** [comment]
@amelchio thanks

**Comment by KennethNielsen** [comment]
Ok. I'll be short circuiting the process a little bit to get things fixed in a hurry. There seem to be more things broken, I will update them directly in master and keep everyone informed about what was broken here, so that you can test and review the changes.

At least so far it seems that also player_info is broken.

**Comment by KennethNielsen** [comment]
Ok. So I got all unit tests to pass and did some corrections to make the integration tests pass, because if I'm going to work on the sonos favorites thing, it would be nice to do it by adding an integration test for it, and so I neede them to run. I also made a few tweaks to cut the integration test time down from ~113s to ~65s, which improves the test time of the entire suite.

**Comment by maru-sama** [comment]
Hi, please do not forget to take a look at #589 for the release as well.

**Comment by KennethNielsen** [comment]
@maru-sama I look a little into it and I would rather not do that. We have once before been burned by integrating features just before release and futher more, this may conflict with some of the work around the alternative events implementation. So I will do a release as soon as I have favorites working. Then integrate as much work as I can (including this) and then do a new release after the testing period. Sorry.

**Comment by KennethNielsen** [comment]
Ok. So I got all unit tests to pass and did some corrections to make the integration tests pass, because if I'm going to work on the sonos favorites thing, it would be nice to do it by adding an integration test for it, and so I neede them to run. I also made a few tweaks to cut the integration test time down from ~113s to ~65s, which improves the test time of the entire suite.

**Comment by KennethNielsen** [comment]
I just committed a fix for the favorites issue. It is known from earlier, that favorites them selves might not have a resource (which is received in a res tag), which is what makes them playable. In order to play them you need to go via their references. So the code accounted for this res tag not being there, but it didn't account for the res tag being there but being empty, which is what apparently happens now.

**Comment by KennethNielsen** [comment]
Since the only things committed recently are bug fixes, I'm about ready to try and do a release and I will in about 30 min or so. If anyone sees this real time and wants to test, that would be great.

**Comment by tksunw** [comment]
soco.discover() works again.

Version 0.16 installed by `pip`:
```
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import soco
>>> soco.__file__
'/usr/local/lib/python3.6/dist-packages/soco/__init__.py'
>>> soco.__version__
'0.16'
>>> soco.discover()
set()
```

Latest version pulled directly from github:
```
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import soco
>>> soco.__file__
'/home/tim/GIT-STUFF/SoCo/soco/__init__.py'
>>> soco.__version__
'0.16'
>>> soco.discover()
{SoCo("192.168.1.169"), SoCo("192.168.1.167"), SoCo("192.168.1.179"), SoCo("192.168.1.157"), SoCo("192.168.1.166"), SoCo("192.168.1.121"), SoCo("192.168.1.164"), SoCo("192.168.1.108")}
>>>
```

The latest commit on GitHub has version `0.16` specified in __init__.py.  Not sure if that should be 0.17 yet.

**Comment by KennethNielsen** [comment]
@tksunw thanks for testing. Great that it work for you.

No, I haven't made the release yet, so the release version number just hasn't been updated yet.

**Comment by KennethNielsen** [comment]
@amelchio the favorites issue is now fixed in master as well. Thanks for mentioning it.

Let's hope that was the last of he fall out and close this.
