### ISSUE TITLE
Bug in documentation

### ISSUE THREAD

**Issue by Auerhahn** [SoCo/SoCo#671]
The desciption for method »loudnbess« mentions: »Loudness is a complicated topic. You can find a nice summary about this feature here: http://forums.sonos.com/showthread.php?p=4698#post4698« It would be interesting to learn something avout this complicated topic, but the link leads to nowhere...

**Comment by KennethNielsen** [comment]
Hi @Auerhahn 

Thanks for reporting this. I couldn't find the explanation that it referred to before, so now we just refer to Wikipedia for more information. I hope this is acceptable for you.
