### ISSUE TITLE
Created a SoCo/SoCo room on gitter for development talk and support

### ISSUE THREAD

**Issue by KennethNielsen** [SoCo/SoCo#676]
I like having a chat channel available for online projects such as this one, which is why a while ago I created a IRC channel. But alas, times change and it seems IRC doesn't have a much pull as it used to. Since I was already on gitter for a few other projects I made a room for SoCo talk there.

https://gitter.im/SoCo/SoCo

Come join me for a chat about SoCo.

PS: I started inviting people until I realized that maybe that was a bit pushy, so apologize to the I spammed with that. What that means however is that only very few people have been invited so spread the work.

**Comment by stefankoegl** [comment]
Great initiative! Once it's established we should also mention it in the documentation and in https://github.com/SoCo/soco.github.io

**Comment by KennethNielsen** [comment]
Added to docs

**Comment by KennethNielsen** [comment]
PR added to io pages: https://github.com/SoCo/soco.github.io/pull/4 closing this issue.
