### ISSUE TITLE
Unknown UPnP class: object.item.audioItem.linein.homeTheater

### ISSUE THREAD

**Issue by sracing** [SoCo/SoCo#701]
I had a SoCoFault whenever using Sonos Playbase LineIn (Toslink) through my TV.  I am using SoCo with a third party plugin for SmarthomeNG. The warning message was: 

WARNING  plugins.sonos.soco.events_base Event contains illegal metadatafor 'av_transport_uri_meta_data'.
Error message: 'Unknown UPnP class: object.item.audioItem.linein.homeTheater'
The result will be a SoCoFault.

I was able to fix this by adding the following new class definition to \soco\data_structures.py starting at line 755:

`class DidlLineInHomeTheater(DidlAudioItem):`

    """Class that represents LineIn from a playbase through Toslink."""

    # the DIDL Lite class for this object.
    item_class = 'object.item.audioItem.linein.homeTheater'
    # name: (ns, tag)
    _translation = DidlAudioItem._translation.copy()
    _translation.update(
        {
            'genre': ('upnp', 'genre'),
            'description': ('dc', 'description'),
            'long_description': ('upnp', 'longDescription'),
            'publisher': ('dc', 'publisher'),
            'language': ('dc', 'language'),
            'relation': ('dc', 'relation'),
            'rights': ('dc', 'rights'),
        }
    )

The official DIDL specification http://upnp.org/specs/av/UPnP-av-ContentDirectory-v4-Service.pdf does refer to the properties of a audioItem, so I was using this for the audioItem.linein.homeTheater definition.

I am far away from being a expert, but the fix worked for me. Would be great if the real experts could review this and consider for future versions, although it seems the issue only happens by using the Toslink/LineIN of a Sonos Playbase.

**Comment by tagdara** [comment]
There's a ton of these subclasses that get added both as physical input options and weird quirks that the various music services implement with a combination of . and #.  In the past it's been discussed that falling back to the parent class would be far better, instead of dropping a SoCoFault, especially since the fault (in most cases) crashes the entire stack and loses subscriptions to one or more players.  Alexa support with amazon music caused a huge number of these.  Spotify brings new ones with . subclasses.  Apple Music has # subclasses that cause it.   

A simple fallback to parent would fix nearly all of them, eliminate the crashes, and in most cases deliver the right data.

**Comment by KennethNielsen** [comment]
I will start working on it.

**Comment by KennethNielsen** [comment]
There is now a PR that fixes this #713. Instead of merely falling back to parent, this creates the vendor extended classes on the fly as simple extensions of the parents.

@tagdara would you care to review?

@sracing can you please test if it works for you.

**Comment by sracing** [comment]
I did test the 'autogenerate-wild-DIDL-Lite-classes' Branch and can confirm the former 

`WARNING plugins.sonos.soco.events_base Event contains illegal metadatafor 'av_transport_uri_meta_data'.
Error message: 'Unknown UPnP class: object.item.audioItem.linein.homeTheater'
The result will be a SoCoFault.` 

is gone.

BUT it gives me a new regular (20 minutes) error in the plugin that I am using (using SmarthomeNG with the Sonos Plugin) for my 4 Sonos devices:

`2020-04-26 09:36:13 WARNING plugins.sonos Sonos: : speaker is not initialized.
2020-04-26 09:36:13 WARNING plugins.sonos Sonos: : speaker is not initialized.
2020-04-26 09:36:13 WARNING plugins.sonos Sonos: : speaker is not initialized.
2020-04-26 09:36:13 WARNING plugins.sonos Sonos: : speaker is not initialized.
2020-04-26 09:36:13 ERROR plugins.sonos ''
2020-04-26 09:56:12 WARNING plugins.sonos Sonos: : speaker is not initialized.
2020-04-26 09:56:12 WARNING plugins.sonos Sonos: : speaker is not initialized.
2020-04-26 09:56:12 WARNING plugins.sonos Sonos: : speaker is not initialized.
2020-04-26 09:56:12 WARNING plugins.sonos Sonos: : speaker is not initialized.
2020-04-26 09:56:12 ERROR plugins.sonos ''`

Not sure if that error is more based on a unexpected SoCo behaviour or if it is caused by the plugin itself.

**Comment by KennethNielsen** [comment]
I think that warning is unrelated. I will close this as I expect #713 which is now merged will fix it. It that turns out not to be the case, then fell free to re-open.
