### ISSUE TITLE
Grouping has no result

### ISSUE THREAD

**Issue by Auerhahn** [SoCo/SoCo#703]
May be I don’t understand the group module. I thought, when I add a player to a group, this will have the effect, that the player is member of this group. But if I do so and look then in the app (Android or Windows) there is no change. What did I misunderstand?

**Comment by ghcs27** [comment]
Can you please post a snippet of the code you use to add the player to the group?

The standard way to add a `player` to a `group` is by calling
```python
player.join(group coordinator)
```

**Comment by pwt** [comment]
> May be I don’t understand the group module. I thought, when I add a player to a group, this will have the effect, that the player is member of this group.

Yes, that's how it should work. I use the `join()` and `unjoin()` methods on SoCo objects. For example:
```
>>> import soco
>>> speaker1 = soco.discovery.by_name('Study')
>>> speaker2 = soco.discovery.by_name('Front Reception')
>>> speaker2.join(speaker1)
```
This groups the 'Front Reception' speaker to the 'Study' speaker, with the Study speaker as the group coordinator, and this grouping should be reflected in any Sonos controller apps.

Additional speakers can be added to the group with commands of the form, e.g.:  
```
>>> speaker3 = soco.discovery.by_name('Bedroom')
>>> speaker3.join(speaker1) 
```
Ungrouping a speaker from a group is done using the `unjoin()` method on a SoCo object.
```
speaker2.unjoin()
```
This ungroups the 'Front Reception' speaker from the 'Study' group.

**Comment by CheapB** [comment]
This works well in my environment. Unless OP provides a code snippet to show the problem I suggest to close

**Comment by jcplu** [comment]
It's working between two S2 players, but not between one S2 player and one S1 player.
Is it possible to use join()/unjoin() between S1/S2 players ?

**Comment by pwt** [comment]
> It's working between two S2 players, but not between one S2 player and one S1 player.
> Is it possible to use join()/unjoin() between S1/S2 players ?

This isn't possible -- Sonos treats the S1 and S2 systems as entirely separate.
