### ISSUE TITLE
switch tv mode to playlist mode

### ISSUE THREAD

**Issue by MrZiM0** [SoCo/SoCo#716]
Hello ,

I read Sonos playlists pointing to spotify music with an RFID system but I encounter a problem when the tv mode is activated the playlist does not launch 

How can switch the sonos to play the music queue if it is in TV mode?

Can't find any commands for it. I can switch to TV or LINE-IN mode but playlist/queue mode is not possible?

Thanks

**Comment by DPH** [comment]
Hi MrZiM0,
have you tried: play_from_queue(index, start=True)[source]

Play a track from the queue by index.
The index number is required as an argument, where the first index is 0.
Parameters:	
index (int) – 0-based index of the track to play
start (bool) – If the item that has been set should start playing

Cheers David

**Comment by MrZiM0** [comment]
Hi David,

Thank you for your response, it works perfectly

I used the speaker.play () function instead of the play_from_queue () function

beginner error

Cheers
