### ISSUE TITLE
Music Library get_music_library_information processes 'share' browsing incorrectly

### ISSUE THREAD

**Issue by Sonosy** [SoCo/SoCo#717]
Using
`.get_music_library_information("share", search_term='//nas/my folder')`
sends
`<ObjectID>S::%2F%2Fnas%2Fmy%20folder</ObjectID>`
This fails on 2 counts:
1. The double colon
2. Escaping the /

What should be sent is either
`<ObjectID>S://nas/my%20folder</ObjectID>`
or
`<ObjectID>S://nas/my folder</ObjectID>`
Both work

My working code for get_music_library_information in music_library.py  is
```
from .compat import quote_url
...        
        search = self.SEARCH_TRANSLATION[search_type]
        share_translation = self.SEARCH_TRANSLATION['share']
        # Add sub categories NB sub categories not allowed when searching shares
        if subcategories is not None and search_term != share_translation:
            for category in subcategories:
                search += '/' + url_escape_path(really_unicode(category))
        # Add fuzzy search
        if search_term is not None:
            if search == share_translation:
                # Don't insert ":" and don't escape "/" (so can't use url_escape_path)
                search += quote_url(really_unicode(search_term).encode('utf-8'))
            else:
                search += ':' + url_escape_path(really_unicode(search_term))

```
FWIW both of the following work but are messy
```
.browse(ml_item=type('obj', (object,), {'item_id' : "S://nas/my folder"}))
.browse(ml_item=type('obj', (object,), {'item_id' : "S://nas/my%20folder"}))

```
I didn't have the confidence to do a pull so I was advised to post here

Thanks
Mike
[edit]
FWIW a Wireshark of the Android app shows it does not escape anything in the ObjectID when accessing shares (e.g. <ObjectID>S://nas/my folder</ObjectID>)

**Comment by pwt** [comment]
As noted above, I've opened a PR for this.
