### ISSUE TITLE
Error removing Alarms

### ISSUE THREAD

**Issue by rvhu-cl** [SoCo/SoCo#731]
Adding alarms works fine but remove them I get error messages
python code
```python
from soco.alarms import Alarm
import soco
import soco.alarms

sonos = SoCo('192.168.2.XXX')
alarm = Alarm(sonos)
alarms = soco.alarms.get_alarms(sonos)
print(alarms)
print (alarm.volume)
print (alarm)
alarm.remove()
```

```
 File "sonos_alarm.py", line 11, in <module>
    alarm.remove()
  File "/home/xxxxx/.local/lib/python3.6/site-packages/soco/alarms.py", line 243, in remove
    ('ID', self._alarm_id)
  File "/home/xxxxx/.local/lib/python3.6/site-packages/soco/services.py", line 217, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/home/xxxxxx/.local/lib/python3.6/site-packages/soco/services.py", line 501, in send_command
    self.handle_upnp_error(response.text)
  File "/home/xxxxx/.local/lib/python3.6/site-packages/soco/services.py", line 560, in handle_upnp_error
    error_xml=xml_error
soco.exceptions.SoCoUPnPException: UPnP Error 800 received:  from 192.168.2.XXX
```

**Comment by rvhu-cl** [comment]
I have check the code but self_alarm_id needs to be filled in remove() so it only works if you save a alarm just before but if you want to delete a existing alarm it cannot be used.
 I added an new function. 
    def remove_id(self,alarm_id):
        """Remove the alarm from the Sonos system.

        There is no need to call `save`. The Python instance is not deleted,
        and can be saved back to Sonos again if desired.
        """
        self._alarm_id = alarm_id
        self.zone.alarmClock.DestroyAlarm([
            ('ID', self._alarm_id)
        ])
        alarm_id = self._alarm_id
        try:
            del Alarm._all_alarms[alarm_id]
        except KeyError:
            pass
        self._alarm_id = None

now it's can delete alarms id's

Perhaps you can add this function in new release.

**Comment by rvhu-cl** [comment]
pull request: add save by id and remove by id.

something for the new release.

    def remove_id(self,alarm_id):
        """Remove the alarm from the Sonos system.

        There is no need to call `save`. The Python instance is not deleted,
        and can be saved back to Sonos again if desired.
        """
        self._alarm_id = alarm_id
        self.zone.alarmClock.DestroyAlarm([
            ('ID', self._alarm_id)
        ])
        alarm_id = self._alarm_id
        try:
            del Alarm._all_alarms[alarm_id]
        except KeyError:
            pass
        self._alarm_id = None

    def save_id(self):
        """Save the alarm to the Sonos system.

        Raises:
            ~soco.exceptions.SoCoUPnPException: if the alarm cannot be created
                because there
                is already an alarm for this room at the specified time.
        """
        # pylint: disable=bad-continuation
        args = [
            ('StartLocalTime', self.start_time.strftime(TIME_FORMAT)),
            ('Duration', '' if self.duration is None else
                self.duration.strftime(TIME_FORMAT)),
            ('Recurrence', self.recurrence),
            ('Enabled', '1' if self.enabled else '0'),
            ('RoomUUID', self.zone.uid),
            ('ProgramURI', "x-rincon-buzzer:0" if self.program_uri is None
                else self.program_uri),
            ('ProgramMetaData', self.program_metadata),
            ('PlayMode', self.play_mode),
            ('Volume', self.volume),
            ('IncludeLinkedZones', '1' if self.include_linked_zones else '0')
        ]
        if self._alarm_id is None:
            response = self.zone.alarmClock.CreateAlarm(args)
            self._alarm_id = response['AssignedID']
            Alarm._all_alarms[self._alarm_id] = self
        else:
            # The alarm has been saved before. Update it instead.
            args.insert(0, ('ID', self._alarm_id))
            self.zone.alarmClock.UpdateAlarm(args)
        return self._alarm_id

**Comment by pwt** [comment]
@rvhu-cl Would you like to create a 'formal' PR for this? I can help if you haven't done so before.

I'll tentatively add it to the v0.21 milestone, which would give us about 4 weeks to get it ready.

**Comment by rvhu-cl** [comment]
I have not create a PR before, so if you can help me please do.

Verstuurd vanaf mijn iPhone

**Comment by pwt** [comment]
> I have not create a PR before, so if you can help me please do.

I was going to write something, but here's an excellent summary that shows all the steps needed both on GitHub and in your local git repository: https://opensource.com/article/19/7/create-pull-request-github. Once you get the hang of it, it's easy.

Once you have your local repo set up, and a branch created for your change:

1. Get set up for development
2. Develop your code changes and check that they work locally
3. Run the basic SoCo check jobs: flake8, pylint, pytest, and black, and address any failures
4. Commit your changes to your local repo, push to GitHub, create the PR.

Here are the steps to **get set up for development** (you can get hints about this by looking in the [SoCo/.travis.yml](https://github.com/SoCo/SoCo/blob/master/.travis.yml) file)

1. [Recommended] Create and activate Python venv for SoCo development if you haven't already done so
2. Install SoCo's functional and development requirements: `pip install -r requirements.txt -r requirements-dev.txt`
3. Install SoCo in 'editable' mode: from within the `SoCo` directory: `pip install -e .`

Before you commit/push your changes, **run the basic checks** from within the `SoCo` directory:

1. `flake8 soco`
2. `pylint soco`
3. `pytest .`
4. `black --check soco tests`

Good luck ... I'm happy to try to help if you hit any snags.

**Comment by pwt** [comment]
Just to respond to the original defect report, copied below.

The reason this is failing is that **the new alarm is not saved**, so it hasn't been sent to the Sonos speaker. The code should include an `alarm.save()`, after which `alarm.remove()` will work, as per the [documentation](http://docs.python-soco.com/en/v0.20/api/soco.alarms.html).

> Adding alarms works fine but remove them I get error messages
> python code
> 
> ```python
> from soco.alarms import Alarm
> import soco
> import soco.alarms
> 
> sonos = SoCo('192.168.2.XXX')
> alarm = Alarm(sonos)
> alarms = soco.alarms.get_alarms(sonos)
> print(alarms)
> print (alarm.volume)
> print (alarm)
> alarm.remove()
> ```
> 
> ```
>  File "sonos_alarm.py", line 11, in <module>
>     alarm.remove()
>   File "/home/xxxxx/.local/lib/python3.6/site-packages/soco/alarms.py", line 243, in remove
>     ('ID', self._alarm_id)
>   File "/home/xxxxx/.local/lib/python3.6/site-packages/soco/services.py", line 217, in _dispatcher
>     return self.send_command(action, *args, **kwargs)
>   File "/home/xxxxxx/.local/lib/python3.6/site-packages/soco/services.py", line 501, in send_command
>     self.handle_upnp_error(response.text)
>   File "/home/xxxxx/.local/lib/python3.6/site-packages/soco/services.py", line 560, in handle_upnp_error
>     error_xml=xml_error
> soco.exceptions.SoCoUPnPException: UPnP Error 800 received:  from 192.168.2.XXX
> ```

**Comment by pwt** [comment]
I'm going to close this based on the original defect report. I'll leave it up to @rvhu-cl to pick up the suggested PR for alarm manipulation by ID, if desired.
