### ISSUE TITLE
Does this work with Spotify Free on Sonos?

### ISSUE THREAD

**Issue by probonopd** [SoCo/SoCo#737]
Does this work with Spotify Free on Sonos? (No paid Spotify account)

**Comment by DPH** [comment]
Hi, Sonos only works with a paid Spotify account. 
SoCo is for controlling Sonos by sending IP commands.
So the answer to your question is No.

Cheers David

**Comment by probonopd** [comment]
Are you sure?

https://support.sonos.com/s/article/1153?language=en_US says

> Sonos supports Spotify Free and Spotify Premium accounts.

**Comment by pwt** [comment]
Spotify does now permit the use of free accounts on Sonos. That's a relatively recent change.

However, SoCo has limitations in controlling Spotify (and some other streaming services): see the notes in the README: https://github.com/SoCo/SoCo#warning

**Comment by probonopd** [comment]
Thanks for the explanation.
