### ISSUE TITLE
type object 'SoCo' has no attribute 'discover'

### ISSUE THREAD

**Issue by realwakils** [SoCo/SoCo#743]
I get that error on SoCo.discover()
is there any other way to get all connected sonos devices

**Comment by pwt** [comment]
Use `speakers = soco.discover()`. This will return a list of SoCo objects representing each visible Sonos device.

**Comment by realwakils** [comment]
i'm currently using from soco import SoCo
is that the right import?

**Comment by pwt** [comment]
Either:
- `from soco import discover` then use `discover()` directly, or:
- `import soco` then use `soco.discover()`

**Comment by realwakils** [comment]
ah i fixed it. just imported both from soco import SoCo and also just import soco!

**Comment by realwakils** [comment]
a quick question:
when i run this:
for device in soco.discover():
    print(device.volume())

it return the error:
   print(device.volume())
TypeError: 'int' object is not callable

**Comment by pwt** [comment]
Use `device.volume` (no parentheses). It's an attribute (using a getter), not a function.

http://docs.python-soco.com/en/v0.19/api/soco.core.html

**Comment by pwt** [comment]
By the way, if you want a less obscure way to use SoCo's features, you might want to try my command-line wrapper:

https://github.com/avantrec/soco-cli

**Comment by realwakils** [comment]
tysm have a great day
