### ISSUE TITLE
discovery() only enumerates first ipv4 address for host name

### ISSUE THREAD

**Issue by gfischershaw** [SoCo/SoCo#764]
Running VirtualBox with a Host-Only Ethernet Adapter. The **discovery()** method picks up that address first and so cannot enumerate the devices on the local network. Switching to **gethostbyname_ex()** seems to work.

```
`        addresses = set()
        try:
            _,_,addressList = socket.gethostbyname_ex(socket.gethostname())
            addresses.update(addressList)
        except socket.error:
            pass
        try:
            _,_,addressList = socket.gethostbyname_ex(socket.getfqdn())
            addresses.update(addressList)
        except socket.error:
            pass
````

**Comment by pwt** [comment]
Note that you can supply an `interface_addr` as an optional parameter to `soco.discovery.discover()` [1]. Perhaps you could give that a try. Also, there's a new discovery technique arriving in SoCo 0.21 that can search all interfaces for Sonos devices, which will circumvent problems with selecting the right network interface(s).

[1] http://docs.python-soco.com/en/v0.20/api/soco.discovery.html
[2] http://docs.python-soco.com/en/latest/api/soco.discovery.html#soco.discovery.scan_network

**Comment by gfischershaw** [comment]
When I first ran into this problem I did indeed hardcode the correct IP, but it did not seem like a good solution to do that for each and every device on which I ran a script. The function is also used in discovery.any_soco(), discovery.by_name(), and get_alarms(). It seemed better to just fix the problem, which is to get all the interface IPs. The new code looks like it just uses the current methodology before then calling discovery.scan_network(). Seems like first portion could be switched to from gethostbyname() to using gethostbyname_ex(), and therefore better deal with most cases and never need to call scan_network().

**Comment by pwt** [comment]
> When I first ran into this problem I did indeed hardcode the correct IP, but it did not seem like a good solution to do that for each and every device on which I ran a script. And the function is also used in discovery.any_soco(), discovery.by_name(), and get_alarms(). It seemed better to just fix the problem, which is to get all the interface IPs.

Your proposed change looks like a good improvement for single interface hosts with multiple IP addresses. Would you like to create a PR for review?

> The new code looks like it just uses the current methodology before then calling discovery.scan_network(). Seems like first portion could be switched from gethostbyname() to using gethostbyname_ex(), and therefore better deal with most cases and never need to call scan_network().

Just to add that `scan_network()` is intended as a standalone function that works with multihomed hosts, with multi-household Sonos systems, and works on networks where normal discovery fails due to SSDP forwarding misbehaviour. It's just provided as a fall-through for the regular `discover()` functions as a convenience.

**Comment by pwt** [comment]
Reflecting on this, perhaps a more comprehensive approach would be to use the `ifaddr` package, as is done in `scan_network()`. That would enumerate all IP addresses, across all interfaces, so it would cover this issue as well as the broader problem.

**Comment by pwt** [comment]
> Reflecting on this, perhaps a more comprehensive approach would be to use the `ifaddr` package, as is done in `scan_network()`. That would enumerate all IP addresses, across all interfaces, so it would cover this issue as well as the broader problem.

PR #767 takes this approach.

**Comment by gfischershaw** [comment]
I thought that I should mention socket.gethostbyname_ex() deals with multiple network interfaces and multiple addresses on each interface. It may indeed already do everything you want.

**Comment by pwt** [comment]
> I thought that I should mention socket.gethostbyname_ex() deals with multiple network interfaces and multiple addresses on each interface. It may indeed already do everything you want.

Not when I tested it on a couple of multi-homed hosts (using `socket.gethostname()` and `socket.getfqdn()`).

**Comment by gfischershaw** [comment]
So only returns addresses on all interfaces using the same host name then? I don't have a multihomed setup. Oh well, at least it got you cogitating on the issue.

**Comment by pwt** [comment]
> So only returns addresses on all interfaces using the same host name then?

Sone hosts/adapters don't have resolvable hostnames, so nothing is returned using either `gethostbyname()` or `gethostbyname_ex()`. E.g.:

```
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.gethostbyname_ex(socket.gethostname())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno -5] No address associated with hostname
>>> socket.gethostbyname_ex(socket.getfqdn())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno -5] No address associated with hostname
>>>
```

Whereas `ifaddr` will enumerate all adapters, and all IP addresses on those adapters:

```
>>> import ifaddr
>>> ifaddr.get_adapters()
odict_values([Adapter(name='lo', nice_name='lo', ips=[IP(ip='127.0.0.1', network_prefix=8, nice_name='lo'), IP(ip=('::1', 0, 0), network_prefix=128, nice_name='lo')], index=1), Adapter(name='eth0', nice_name='eth0', ips=[IP(ip='192.168.0.254', network_prefix=24, nice_name='eth0'), IP(ip=('fe80::7b88:964b:52dc:9cb3', 0, 2), network_prefix=64, nice_name='eth0')], index=2), Adapter(name='resin-dns', nice_name='resin-dns', ips=[IP(ip='10.114.102.1', network_prefix=24, nice_name='resin-dns'), IP(ip=('fe80::a802:40ff:fe4c:5cf6', 0, 4), network_prefix=64, nice_name='resin-dns')], index=4), Adapter(name='br-36977ce39f4f', nice_name='br-36977ce39f4f', ips=[IP(ip='172.17.0.1', network_prefix=16, nice_name='br-36977ce39f4f'), IP(ip=('fe80::42:4cff:fe22:fe08', 0, 5), network_prefix=64, nice_name='br-36977ce39f4f')], index=5), Adapter(name='supervisor0', nice_name='supervisor0', ips=[IP(ip='10.114.104.1', network_prefix=25, nice_name='supervisor0')], index=6), Adapter(name='balena0', nice_name='balena0', ips=[IP(ip='10.114.101.1', network_prefix=24, nice_name='balena0')], index=7), Adapter(name='resin-vpn', nice_name='resin-vpn', ips=[IP(ip='10.240.96.254', network_prefix=32, nice_name='resin-vpn'), IP(ip=('fe80::4b1d:3e46:9a52:2d79', 0, 12), network_prefix=64, nice_name='resin-vpn')], index=12), Adapter(name='veth9a1aee4', nice_name='veth9a1aee4', ips=[IP(ip=('fe80::8c12:37ff:fed4:c072', 0, 9), network_prefix=64, nice_name='veth9a1aee4')], index=9)])
>>>
```

> I don't have a multihomed setup. Oh well, at least it got you cogitating on the issue.

It did, and I learnt a couple of things. From my work on network scan discovery, I was aware that we could improve the current discovery code, and your issue was a good prompt to do so. With the new scanning method and the improved multicast method, I think that SoCo 0.21 will address the vast majority of issues that people encounter with discovery.

**If you have time, could you test my PR?** I'd just like confirmation that it works on aliased (multi-IP) interfaces, and that it addresses the issue.

You can just temporarily replace `discovery.py` in your installation with my version at: https://raw.githubusercontent.com/pwt/SoCo/discover_multi_IP/soco/discovery.py.

You'll also need to install `ifaddr` (`pip install ifaddr`).

**Comment by gfischershaw** [comment]
That functions. A couple comments:
The preferred address for my disabled wifi interface is on the list returned by ifaddr. Also returns a couple Windows 169 APIPA addresses, which may have been generated long ago during setup of the machine before it was connected to the network. Lastly, the preferred unicast route is added to the end of the list. Should it be first in order to get that query going as soon as possible?

**Comment by pwt** [comment]
Thanks for testing -- I appreciate the help.

> The preferred address for my disabled wifi interface is on the list returned by ifaddr. Also returns a couple Windows 169.x.y.z APIPA addresses, which may have been generated long ago during setup of the machine before it was connected to the network.

Yes -- that's a necessary consequence of obtaining a full list of adapters/IPs. I get similar results on my Windows machines. It's not easily possible, in general, to determine which are the 'right' ones on a given host. Fortunately, it's inexpensive to issue the multicast requests for each address.

> Lastly, the preferred unicast route is added to the end of the list. Should it be first in order to get that query going as soon as possible?

I don't think the ordering makes much difference. All of the multicast requests are sent in a tight loop before the timeout counter is started.

I did a quick test on a Raspberry Pi 4, executing `discover()` 10 times on all of its IP addresses, then 10 times using only its primary interface IP address. The average discovery time is around 50ms in each case.

```
# python3 discover_perftest.py 
Interface addresses: {'10.240.96.254', '10.114.104.1', '172.17.0.1', '10.114.102.1', '10.114.101.1', '192.168.0.254'}
Average time to execute 'discover()': 0.043s
Average time to execute 'discover(interface_addr='192.168.0.254')': 0.053s
Devices discovered: {SoCo("192.168.0.38"), SoCo("192.168.0.30"), SoCo("192.168.0.32"), SoCo("192.168.0.36"), SoCo("192.168.0.35"), SoCo("192.168.0.41")}
#
```

**Comment by gfischershaw** [comment]
Well that is unfortunate. Looking at the iphlpapi.GetAdaptersAddresses doc it should not be returning the wifi adaptor address, but obviously is. Anyway, that leaves the 169.254.0.0/16 addresses returned. One would presume that they can be ignored, as without DHCP, Sonos devices would have a difficult time. Or am I not considering some situation?

**Comment by pwt** [comment]
> Anyway, that leaves the 169.254.0.0/16 addresses returned. One would presume that they can be ignored, as without DHCP, Sonos devices would have a difficult time. Or am I not considering some situation?

I'll take a look at whether the the 169.254 addresses can be safely excluded. I doubt it makes any practical difference, but it would be neater.

**Comment by gfischershaw** [comment]
Would like to try out the new version whenever you are ready.

**Comment by pwt** [comment]
> Would like to try out the new version whenever you are ready.

It's ready for release, but I'd like a few more people to test it because it changes a long-standing and central function. Feel free to try it out by pulling #767 (instructions [here](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally) if you need them).
