### ISSUE TITLE
device.player_name return none, even though device answers

### ISSUE THREAD

**Issue by simoneggler** [SoCo/SoCo#771]
after creating a device with device = soco.SoCo('ip')

the call to device.group dumps the soap response (debug log) (with oldscool encoding &<t; &gt; &quot;):

but the answer ist None.

example: 
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetZoneGroupStateResponse xmlns:u="urn:schemas-upnp-org:service:ZoneGroupTopology:1"><ZoneGroupState>&lt;ZoneGroupState&gt;&lt;ZoneGroups&gt;&lt;ZoneGroup Coordinator=&quot;RINCON_5CAAFDF67FFA01400&quot; ID=&quot;RINCON_5CAAFDF67FFA01400:3415358236&quot;&gt;&lt;ZoneGroupMember UUID=&quot;RINCON_5CAAFD5ED3AA01400&quot; Location=&quot;http://192.168.1.161:1400/xml/device_description.xml&quot; ZoneName=&quot;Küche&quot; Icon=&quot;x-rincon-roomicon:kitchen&quot; Configuration=&quot;1&quot; SoftwareVersion=&quot;61.1-83170&quot; SWGen=&quot;2&quot; MinCompatibleVersion=&quot;60.0-00000&quot; LegacyCompatibleVersion=&quot;58.0-00000&quot; HTForwardEnabled=&quot;0&quot; BootSeq=&quot;161&quot; TVConfigurationError=&quot;0&quot; HdmiCecAvailable=&quot;0&quot; WirelessMode=&quot;0&quot; WirelessLeafOnly=&quot;0&quot; HasConfiguredSSID=&quot;1&quot; ChannelFreq=&quot;2412&quot; BehindWifiExtender=&quot;0&quot; WifiEnabled=&quot;1&quot; Orientation=&quot;0&quot; RoomCalibrationState=&quot;1&quot; SecureRegState=&quot;3&quot; VoiceConfigState=&quot;0&quot; MicEnabled=&quot;0&quot; AirPlayEnabled=&quot;0&quot; IdleState=&quot;0&quot; MoreInfo=&quot;&quot;/&gt;&lt;ZoneGroupMember UUID=&quot;RINCON_5CAAFD5ED3A801400&quot; Location=&quot;http://192.168.1.159:1400/xml/device_description.xml&quot; ZoneName=&quot;Sofa&quot; Icon=&quot;x-rincon-roomicon:masterbedroom&quot; Configuration=&quot;1&quot; SoftwareVersion=&quot;61.1-83170&quot; SWGen=&quot;2&quot; MinCompatibleVersion=&quot;60.0-00000&quot; LegacyCompatibleVersion=&quot;58.0-00000&quot; HTForwardEnabled=&quot;0&quot; BootSeq=&quot;176&quot; TVConfigurationError=&quot;0&quot; HdmiCecAvailable=&quot;0&quot; WirelessMode=&quot;0&quot; WirelessLeafOnly=&quot;0&quot; HasConfiguredSSID=&quot;1&quot; ChannelFreq=&quot;2412&quot; BehindWifiExtender=&quot;0&quot; WifiEnabled=&quot;1&quot; Orientation=&quot;0&quot; RoomCalibrationState=&quot;1&quot; SecureRegState=&quot;3&quot; VoiceConfigState=&quot;0&quot; MicEnabled=&quot;0&quot; AirPlayEnabled=&quot;0&quot; IdleState=&quot;0&quot; MoreInfo=&quot;&quot;/&gt;&lt;ZoneGroupMember UUID=&quot;RINCON_5CAAFDF67FFA01400&quot; Location=&quot;http://192.168.1.223:1400/xml/device_description.xml&quot; ZoneName=&quot;Wohnzimmer&quot; Icon=&quot;x-rincon-roomicon:living&quot; Configuration=&quot;1&quot; SoftwareVersion=&quot;61.1-83170&quot; SWGen=&quot;2&quot; MinCompatibleVersion=&quot;60.0-00000&quot; LegacyCompatibleVersion=&quot;58.0-00000&quot; HTForwardEnabled=&quot;0&quot; BootSeq=&quot;139&quot; TVConfigurationError=&quot;0&quot; HdmiCecAvailable=&quot;0&quot; WirelessMode=&quot;0&quot; WirelessLeafOnly=&quot;0&quot; HasConfiguredSSID=&quot;1&quot; ChannelFreq=&quot;2412&quot; BehindWifiExtender=&quot;0&quot; WifiEnabled=&quot;1&quot; Orientation=&quot;0&quot; RoomCalibrationState=&quot;1&quot; SecureRegState=&quot;3&quot; VoiceConfigState=&quot;0&quot; MicEnabled=&quot;0&quot; AirPlayEnabled=&quot;1&quot; VirtualLineInSource=&quot;airplay&quot; IdleState=&quot;0&quot; MoreInfo=&quot;&quot;/&gt;&lt;/ZoneGroup&gt;&lt;/ZoneGroups&gt;&lt;VanishedDevices&gt;&lt;/VanishedDevices&gt;&lt;/ZoneGroupState&gt;</ZoneGroupState></u:GetZoneGroupStateResponse></s:Body></s:Envelope>

**Comment by pwt** [comment]
Could you describe your speaker configuration in a little more detail, please? What are the speakers involved, how are they grouped/paired/bonded, etc? Thanks.

**Comment by simoneggler** [comment]
i have removed the umlauf. same result.
this is my setup:
Python 3.7.3
SoCo Version: 0.11.1

I have three speakers (play 5 and two play 3), together in one group.

I wonder why I do not have version 0.20? I just pipped it to my raspberry...

**Comment by simoneggler** [comment]
i force upgrades to version 0.20, I works fine now. thanks for the hint. one more question, tough
soco.discover() returns None. Here's the debug output (my hue bridge is answering):

DEBUG:soco.discovery:Received discovery response from ('192.168.1.88', 1900): "b'HTTP/1.1 200 OK\r\nHOST: 239.255.255.250:1900\r\nEXT:\r\nCACHE-CONTROL: max-age=100\r\nLOCATION: http://192.168.1.88:80/description.xml\r\nSERVER: Hue/1.0 UPnP/1.0 IpBridge/1.41.0\r\nhue-bridgeid: ECB5FAFFFE01FEB8\r\nST: urn:schemas-upnp-org:device:basic:1\r\nUSN: uuid:2f402f80-da50-11e1-9b23-ecb5fa01feb8\r\n\r\n'"

**Comment by simoneggler** [comment]
great software bye the way. thanks!

**Comment by pwt** [comment]
> SoCo Version: 0.11.1

That would certainly cause some issues! :)

>... one more question, tough soco.discover() returns None. Here's the debug output (my hue bridge is answering): ...

The response from the Hue is being (correctly) ignored.

There are two reasons I've come across for `discover()` returning `None` when there are Sonos devices on the network:

1. The MCAST request is being sent on the wrong interface(s): you can use (e.g.) `discover(interface_addr="host_IP_address")` to force discovery on a specific interface. You may also want to try increasing the timeout (although I doubt that's the issue).

2. The network is not passing SSDP multicast packets correctly. This can happen on complex networks with bridging where forwarding has not been set up correctly, or on some networks with routers that (e.g.) don't forward SSDP packets between the wired and wireless interfaces.

Is it possible you're encountering one of these problems? (Incidentally, both will be addressed in SoCo 0.21.)

> great software bye the way. thanks!

Thanks, even if I can only take a very tiny amount of credit for that!

**Comment by simoneggler** [comment]
this might be a silly question, but how do i find out if a speaker is currently playing music?

**Comment by simoneggler** [comment]
thanks, everything ist working fine after the upgrade
