### ISSUE TITLE
Reinstate Check Jobs for SoCo Development

### ISSUE THREAD

**Issue by pwt** [SoCo/SoCo#790]
Travis CI withdrew the ability for open source projects to run check jobs, during the development of SoCo v0.21.

It's important that we reinstate an alternative process, otherwise SoCo development velocity will be significantly impeded and there'll need to be excessive manual testing.

**Comment by rytilahti** [comment]
Take a look at https://hynek.me/articles/python-github-actions/ (for github actions) or https://hynek.me/articles/simple-python-azure-pipelines/ (for azure pipelines, which requires quite a bit more effort but is not bound to github).

**Comment by KennethNielsen** [comment]
I'm already working on a tox configuration for SoCo, which makes it easier to setup Github Actions. I will post a PR shortly.

**Comment by pwt** [comment]
As a temporary measure, I've instantiated a 'brute force' Github actions workflow that performs the same checks as the previous Travis job, across Python 3.5 to 3.9. It appears to be working correctly for PRs and merges to master.

This can be junked when we have a tox configuration.
