### ISSUE TITLE
Arc SL not recognized as soundbar

### ISSUE THREAD

**Issue by runningwolfie** [SoCo/SoCo#794]
I noticed that the is_soundbar property uses endswith to identify soundbars from a list of product names, but this doesn't work for the Arc SL (silent version without Google Assistant microphone). A simple fix would be to change to startswith or to add Arc SL to the soundbars list.

**Comment by runningwolfie** [comment]
Looks like the model_name is listed as 'Sonos Arc SL', so startswith wouldn't work. Can Arc SL be added to SOUNDBARS in core.py please?

**Comment by pwt** [comment]
Yes, I can do this.

**Comment by pwt** [comment]
Fix released in SoCo v0.21.1.
