### ISSUE TITLE
How to get if the device is playing a song atm or if it's stopped?

### ISSUE THREAD

**Issue by realwakils** [SoCo/SoCo#798]
Stopped/paused. i don't really know what the difference is

**Comment by pwt** [comment]
If `speaker` is a `SoCo` instance, then `speaker.get_current_transport_info()["current_transport_state"]` will return a string that is one of `PLAYING`, `PAUSED_PLAYBACK`, `STOPPED`, or `TRANSITIONING`.

(There may be other states for sounder devices, etc.).

Streams in the `PAUSED_PLAYBACK` state can be resumed from their current point, whereas `STOPPED` streams (e.g., radio streams) cannot -- they have to be restarted.
