### ISSUE TITLE
soco.discover() returning nothing at all

### ISSUE THREAD

**Issue by realwakils** [SoCo/SoCo#799]
![image](https://user-images.githubusercontent.com/19620638/105903348-0e4bca00-6020-11eb-90e1-244140dba8e8.png)
Hello. I am getting this issue on my Raspberry Pi 4. The function works on my Windows PC, but not on my Raspberry Pi unfortunately.
It's running Raspbian. I suspect it might have something to do with ports, because I closed most? Maybe not at all.
I'm just really lost and need this function. Not sure which extra info to provide, so just ask me questions.

Thanks and have a great day.

**Comment by pwt** [comment]
First, make sure you're using SoCo v0.21.

If that's already the case, try: `soco.discovery.scan_network()`

**Comment by realwakils** [comment]
> First, make sure you're using SoCo v0.21.
> 
> If that's already the case, try: `soco.discovery.scan_network()`
> 
> Edit: note that the 'normal' `discover()` function requires incoming UDP/1900 to be open, to receive multicast discovery responses.

Thank you `soco.discovery.scan_network()` works. For some reason it didn't work in the python interpreter (`python`, `import soco`, `soco.discovery.scan_network()` - `AttributeError: module 'soco.discovery' has no attribute 'scan_network' `)

**Comment by pwt** [comment]
`from soco.discovery import scan_network`.

**Comment by realwakils** [comment]
Thanks. It does seem to be **very** inconsistent though. I often get None and then in periods I actually receive the set...

**Comment by pwt** [comment]
Generally, it's better if you can use `discover()`, but some networks have problems with multicast forwarding, and some systems have the required incoming port blocked. Both of these will prevent 'normal' discovery from working.

`scan_network` probes the network for Sonos devices. You can improve its chances of success by increasing the timeout for each IP probe. There's full documentation at: http://docs.python-soco.com/en/v0.21.1/api/soco.discovery.html#soco.discovery.scan_network.
