### ISSUE TITLE
How can I check of play() and previous() track are available?

### ISSUE THREAD

**Issue by marcovandewater** [SoCo/SoCo#800]
When playing radio the play() and previous() track methods are not available and raise an exception when called. How can I check this? when I check is_playing_radio attributed it returns False even when Sonos Radio is played.

**Comment by pwt** [comment]
There's a long-standing PR (#594) to provide a simple check for what actions are available at any given time, that I'm looking to include in the next release (v0.22) if it's in good enough shape.

In the meantime, we just have to catch the exception, or you could look at using the `AVTransport.GetCurrentTransportActions()` call that's the basis for #594.

**Comment by marcovandewater** [comment]
Thanks!
