### ISSUE TITLE
Cant play music anymore

### ISSUE THREAD

**Issue by Phill030** [SoCo/SoCo#806]
How do i play music with the new version? When i try `soco.discover()` it'll return an empty list and so i cant play any music on the speaker. Could someone give me an example for the current version?

**Comment by pwt** [comment]
As an experiment, try the following instead to see what it returns:

`soco.discovery.scan_network(scan_timeout=5)`

**Comment by Phill030** [comment]
zone_list = list(soco.discovery.scan_network(scan_timeout=5))

Error: `Traceback (most recent call last):
  File "controller.py", line 6, in <module>
    zone_list = list(soco.discovery.scan_network(scan_timeout=5))
AttributeError: module 'soco.discovery' has no attribute 'scan_network'
`

**Comment by Phill030** [comment]
and when i change it: `  File "controller.py", line 24, in <module>
    zone_list.play_uri(uri)
AttributeError: 'list' object has no attribute 'play_uri'
`

**Comment by Phill030** [comment]
So i replaced scan_network with discover and there wasnt any error but i cant use it as a group anymore:
`zone_list = list(soco.discovery.discover(timeout=5))` is not working

**Comment by pwt** [comment]
Make sure you're using the latest version of SoCo (v0.21.1).

**Comment by Phill030** [comment]
how do i update it?

**Comment by Phill030** [comment]
![image](https://user-images.githubusercontent.com/50775241/108532826-8e401980-72d8-11eb-9700-4b7ad3f77d12.png)
so this is what i installed 3 days ago with `pip install soco`

**Comment by Phill030** [comment]
got it, but still error cause list(soco.discovery.scan_network(scan_timeout=5));

**Comment by pwt** [comment]
Looks like something is broken in your environment. SoCo v0.11.1 is ancient.
Try: `pip install -U soco`.

**Comment by Phill030** [comment]
Another error: 
![image](https://user-images.githubusercontent.com/50775241/108534607-9f8a2580-72da-11eb-8c26-d7f15c121aba.png)

**Comment by pwt** [comment]
You need `play_uri()` for URIs. `add_to_queue()` takes queuable items.

See: http://docs.python-soco.com/en/v0.21.1/api/soco.core.html#soco.core.SoCo.play_uri

(You may want to consider using [SoCo-CLI](https://github.com/avantrec/soco-cli) instead. Easier to get to grip with, if it does what you want.)

**Comment by Phill030** [comment]
Again: 
![image](https://user-images.githubusercontent.com/50775241/108536256-83878380-72dc-11eb-8d24-95c923cd3f56.png)

**Comment by pwt** [comment]
Impossible to debug from screenshots. I'll opt out here.

**Comment by Phill030** [comment]
Solved it, caused from my Youtube URL

**Comment by Phill030** [comment]
but one question left: how do i play a spotify or Youtube link with the new version? it said spotify is deprecated and soco.data_strcutures import URI is not working anymore

**Comment by pwt** [comment]
> but one question left: how do i play a spotify or Youtube link with the new version? it said spotify is deprecated and soco.data_strcutures import URI is not working anymore

Can't be done at the moment (as discussed in the README), since Sonos changed how it authenticates with music services.

If you add tracks to Sonos favourites or Sonos playlists, these can usually be played. You have to obtain the queueable items using the SoCo search functions, then add them to the queue.

Restoring music service support is being worked on in #763, but it's not guaranteed to be successful.
