### ISSUE TITLE
SoCo 0.22.0 fails to install on some platforms due to requirement to build 'yarl' and 'mutlidict'

### ISSUE THREAD

**Issue by pwt** [SoCo/SoCo#819]
The inclusion of `events_asyncio` in v0.22.0 brought in a dependency on the `aiohttp` package, which in turn depends on `yarl` and `multidict`.

It turns out that both `yarl` and `multidict` have binary wheels, with prebuilt versions available for some platforms (Linux, macOS, Windows), meaning that installs on these platforms will work without error.

However, build/installation failures can occur on other platforms, including on Raspberry PIs running PiOS (Raspbian). In order to install successfully, the `build-essential` (compiler, etc.) and `python3-dev` (Python headers) packages must be present:

`sudo apt install build-essential python3-dev`

These new dependencies may also cause install failures on other platforms.

We need to determine whether this is going to be a major problem, and look for workarounds.

**Comment by pwt** [comment]
@bdraco : Do you have any thoughts on this? I'm worried that the inclusion of the new `aiohttp` dependency is going to prevent SoCo installs on some platforms.

**Comment by bdraco** [comment]
How about making it an extra? so you can do something like

pip install 'SoCo[asyncio]'

extras_require = {
   'asyncio': ['aiohttp']
}

Typing this on a mobile so hopefully it makes sense.

**Comment by bdraco** [comment]
Also FWITW, both yarl and multidict have pure python install options and can be installed as follows:

MULTIDICT_NO_EXTENSIONS=1 pip install multidict
YARL_NO_EXTENSIONS=1 pip install yarl

I think the extra route is the safer one though

**Comment by pwt** [comment]
Great -- thanks @bdraco.

I'll have a play with removing the hard requirement, and the `extras_require` approach.
