### ISSUE TITLE
Add EndDirectControlSession to AVTransport class

### ISSUE THREAD

**Issue by amaten69** [SoCo/SoCo#826]
Add EndDirectControlSession to avtransport class. Its a good method to clear all sessions on sonos.

(this https://github.com/amaten69/SoCo/tree/iss826)

**Comment by pwt** [comment]
Hi @amaten69:

1. Could you provide an example of the circumstances under which this would be used?
2. Could you create a pull request with your changes?

Thanks.

**Comment by amaten69** [comment]
The circumstances when to use this is when you start a music stream from a music service through a third party (for me its alexa). It doesn't create a queue, instead it creates a session via there content service. For me if I left the session open by simply stoping or pausing the music things acted very buggy. Its essentially the "end session" button in the sonos app.

Below is a little snipet of how i use it to kill all sessions everynight:
`import soco
import xmltodict

devices = soco.discover()

for device in devices:
    track = device.get_current_track_info()
    if track["metadata"] != '':
        metadata_uri = xmltodict.parse(track["metadata"])
        if "r:contentService" in metadata_uri["DIDL-Lite"]["item"].keys():
            device.enddirectcontrolsession()`
