### ISSUE TITLE
Spotify ShareLink plugin fails on Sonos S2 (UPnP 800)

### ISSUE THREAD

**Issue by pwt** [SoCo/SoCo#847]
Using the new ShareLink plugin (#838) in SoCo v0.23.0, I find that it works for Spotify on Sonos S1 (11.2.9) but fails on Sonos S2 (13.1.4), returning a UPnP 800 error.

I'm in the UK, using a Spotify Premium subscription.

@amelchio : Any ideas? Happy to perform debugging suggestions.

**Comment by pwt** [comment]
Update: it's now started working with S2 (at least in one context, while not in another). I'll continue to investigate.

**Comment by amelchio** [comment]
I don't have much time right now but there is a similar issue with some information in home-assistant/core#52707.

I also discovered that `MusicService.get_data_for_name()` will end up calling `discovery.any_soco()`, that might cause issues as well(?)

**Comment by pwt** [comment]
> I also discovered that `MusicService.get_data_for_name()` will end up calling `discovery.any_soco()`, that might cause issues as well(?)

That's probably it.

I have a split S1/S2 system, so the results of calling `any_soco()` are non-deterministic in terms of to which system the returned speaker belongs. That would explain why I'm getting inconsistent results.

Thanks for your help.

**Comment by amelchio** [comment]
That's interesting, do you have any idea why one of your systems fail?

**Comment by pwt** [comment]
> That's interesting, do you have any idea why one of your systems fail?

Right now, I don't understand what's going on. I'm looking into it.

However, it's certainly not as simple as "does not work on S2".
