### ISSUE TITLE
pypi sources hasn't got `tests/data/data_structures_entry_integration`

### ISSUE THREAD

**Issue by catap** [SoCo/SoCo#873]
Sources which I've download from https://pypi.org/project/soco/ for version 0.25.0 hasn't got `tests/data/data_structures_entry_integration`. This leads to broken tests.

**Comment by pwt** [comment]
Hi @catap:

I was surprised to find that **any** tests are shipped with the SoCo distribution! I'll investigate whether the `tests` directory really needs to be there ... I don't know what the general convention is for this.

I'd always expected that folks who want to run the tests would clone the repo and install the necessary dependencies.

**Comment by catap** [comment]
@pwt it is a good practice to ship tests. For example it can be used for packet manager like macports to confirm that an application works well :)

**Comment by pwt** [comment]
> @pwt it is a good practice to ship tests. For example it can be used for packet manager like macports to confirm that an application works well :)

Thanks. Yes, I'm gathering that :) I've found the problem and I have a fix that I'll push up shortly. Note that this is a long-standing issue, not something new in 0.25.

**Comment by pwt** [comment]
Since this issue has been around for a while without attracting complaint, I'm minded not to issue an immediate patch release. It'll get included in 0.25.1 or 0.26.0.

**Comment by catap** [comment]
0.25.1 doesn't include the fix :)

**Comment by pwt** [comment]
> 0.25.1 doesn't include the fix :)

Could you check again?

v0.25.1 definitely includes https://github.com/SoCo/SoCo/commit/02700ff61733b8af8f32b2b152a6872383b114fa which implements the fix, and the [source distribution](https://files.pythonhosted.org/packages/c1/cb/138c31711301f34a0acf97801202b66bbcb01ea0bf97419c80e63474d403/soco-0.25.1.tar.gz) includes the relevant files.

**Comment by catap** [comment]
@pwt my bad, I've tested it via macports, and by some reason I've checked 0.25.0, not 0.25.1.

**Comment by pwt** [comment]
> @pwt my bad, I've tested it via macports, and by some reason I've checked 0.25.0, not 0.25.1.

No problem. Thanks for confirming.
