### ISSUE TITLE
Unknown audio input format: 84934718 (and 33554494)

### ISSUE THREAD

**Issue by tangix** [SoCo/SoCo#877]
Seeing errors in Home Assistant about unknown format:
```
Logger: root
Source: /usr/local/lib/python3.9/site-packages/soco/core.py:1273
First occurred: 14:06:38 (585 occurrences)
Last logged: 18:59:09

Unknown audio input format: 33554494
Unknown audio input format: 84934718
```
The Sonos app reports this from the Sonos Arc:
![image](https://user-images.githubusercontent.com/1013635/147496840-86b6cfc6-b183-4234-a831-c61795d68743.png)
And in Sonos Controller desktop:
```
Sonos Arc: Vardagsrum
Serial Number: 48-A6-B8-**-**-**:0
Sonos OS: S2
Version: 13.4.1 (build 66423300)
Hardware Version: 1.27.1.8-2.2
Series ID: A100
IP Address: 192.168.x.y
Audio In: Dolby Multichannel PCM 5.1
WM: 0
```

**Comment by jjlawren** [comment]
These have already been addressed by https://github.com/SoCo/SoCo/pull/871 and should be fixed in Home Assistant 2021.12.6 when it is released.
