### ISSUE TITLE
[question] add_to_queue for spotify tracks / albums

### ISSUE THREAD

**Issue by jonasripperger** [SoCo/SoCo#88]
Hi all,

I saw what jasperla build over at soffes/sonos "https://github.com/soffes/sonos/pull/26". And tought it would be cool to have it also in SoCo but I think I miss something...

playing a spotify track is no problem:
track = "x-sonos-spotify:spotify%3atrack%3a0GfUZrIeoQ1TVZFnLSZYJY?sid=9&amp;flags=32"
print(sonos.play_uri(track))

But what I want is to alos be able to play albums and playlists. So I wiresharked a little bit to be sure to have a valid URI.

album = "x-rincon-cpcontainer:0004006cspotify%3aalbum%3a4agvS3xuy9p0I7aDMQVFEp"

but this wont work with the play uri method. Jasperla gave me the hint that its not possible to play a album but to queue it, so I tryed to use add_to_queue but I think I miss something because the method wants meta data but has only one arument to pass. 
print(sonos.add_to_queue(track))

So how would I call the method correct and how do I get the correct meta data? Just use the meta data logged with wireshark?

maybe someone can see what im missing and point me into the right direction (-:

cheers
Malchio

**Comment by jeantristan** [comment]
Hi there,
I've got exactly the same need. I know this issued is dated from 2014, but is it solved since ?

**Comment by KennethNielsen** [comment]
@jeantristan not really. We have a music service implementation now, which also covers spotify and which should be able to produce items which can be added to the queue. But since then, Sonos made changes in authentication, which we have been unable to overcome :(
