### ISSUE TITLE
Unable to refresh token with Spotify and Amazon Music music services

### ISSUE THREAD

**Issue by goldyfruit** [SoCo/SoCo#890]
The main authentication with Spotify music service works well but when the token expires, SoCo is not able to refresh it.

With the code in PR #763 is was working as expected but since the merge of PR #883 the refresh doesn't work anymore.

In PR #763, we had this:
```python
                auth_token = exc.detail.find(
                    ".//xmlns:authToken", {"xmlns": self.namespace}
                ).text
                private_key = exc.detail.find(
                    ".//xmlns:privateKey", {"xmlns": self.namespace}
                ).text
```

In PR #883 we have this:
```python
                auth_token = exc.detail.findtext(".//authToken")
                private_key = exc.detail.findtext(".//privateKey")
```

If I cherry-pick the code from PR #763 I'm able to get a refresh token with SoCo 0.26.2.

**Comment by jjlawren** [comment]
I'd suggest to try the namespace-specific search first, and use the current `findtext()` method as a backup if the results are empty. Should cover all cases we've seen so far.
