### ISSUE TITLE
For music services - how get from album item_id/uri to individual tracks

### ISSUE THREAD

**Issue by slzatz** [SoCo/SoCo#919]
First of all, it is amazing to me that you have music services working such that you can search for a track on the service and queue it up and play it.  What I can't figure out and don't see examples of is searching a music service for an album and not an individual track and then being able to place the album (or its individual tracks) in the queue for playing.  So for example:

result =  ms.search(category='tracks', term='harvest')

produces a list that can be played based on item_ids.

However, I can't figure out what to do with:

result = ms.search(category='albums', term='harvest')

The returned results are an MSAlbum object which has an item_id but I don't see any examples of taking that album item_id and turning it into a uri that can either be played directly or can be used to retrieve the individual tracks.  I understand the ability to use music services is a work in progress but is it currently possible to retrieve an album (vs. an individual track) from a music service search and play it?

Thanks,

Steve

**Comment by pwt** [comment]
The test code at https://github.com/SoCo/SoCo/pull/763#issue-753004109 might provide some hints. You'll have to add the item to the queue, then play from the queue.

**Comment by slzatz** [comment]
Thanks for pointing me to the test code -- I had thought I needed to write a custom add_to_queue but clearly not -- so searching on albums and then placing one of the returned items on the queue using add_to_queue in core.py works perfectly.  Really appreciate the work that was done to be able to use music services -- it makes this project incredibly useful.
