### ISSUE TITLE
discover() not working

### ISSUE THREAD

**Issue by ScottOKirkpatrick** [SoCo/SoCo#923]
I use a script to backup my Sonos playlists nightly.  I haven't checked my backup report for a while but I noticed that the discover() function now always returns None.
    `print(list(soco.discover()))`
I know that SoCo can see my devices because
    `print(soco.SoCo('192.168.0.120').player_name)`
works fine.

**Comment by pwt** [comment]
What version of SoCo are you using?

Discovery is pretty solid these days, provided the network/firewall are passing SSDP multicast packets correctly. Is it possible your network has changed in some way?

A couple of things you could try:

1. Use DEBUG logging to see what's going on during discovery
2. Use `soco.discovery.discover(allow_network_scan=True)`. This will fall back to scanning the network for Sonos devices if none are found by multicast discovery.

**Comment by ScottOKirkpatrick** [comment]
v0.28.0

hmmm, soco.discovery.discover(allow_network_scan=True) does seem to work.  I think when I changed my Linux box from a desktop to a server install, ufw mucked up some of the ports.  Right now, it shows

```
scott@Warren:~$ sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
22/tcp                     ALLOW       Anywhere
Samba                      ALLOW       Anywhere
22/tcp (v6)                ALLOW       Anywhere (v6)
Samba (v6)                 ALLOW       Anywhere (v6)

```

However, I cannot seem to find the right settings for ufw to allow the SSDP multicast packets.  Nothing I've tried seems to work.

**Comment by pwt** [comment]
If you haven't already done so, you could try:
```
sudo ufw allow 1900/udp
```
However, I have a vague recollection that the multicast responses come back on a range of different ports, so the above may not work.

If it does work, you can then refine it to allow traffic from a more restricted range of addresses.

The network scanning approach is also a perfectly reasonable one. If you wish, you can opt to use that as the default by using `soco.discovery.scan_network()`.

**Comment by pwt** [comment]
> > However, I have a vague recollection that the multicast responses come back on a range of different ports, so the above may not work.
> 
> SSDP responses are sent to the source port of the original multicast request. This is chosen randomly, so you'd need to allow UDP packets back from your Sonos devices to your host running SoCo on the ephemeral port range appropriate for the OS it's running. On most Linux distributions that's 32768–60999.

Thanks for clarifying that, @jjlawren -- very helpful.
