### ISSUE TITLE
BBC sounds 

### ISSUE THREAD

**Issue by imjamesf** [SoCo/SoCo#928]
Can you load a radio station on BBC sounds?

**Comment by pwt** [comment]
Yes.

First add the required station to your Sonos Favourites using a Sonos app, then:

1. Use `music_library.get_sonos_favorites(complete_result=True)` to get the list of favourites, followed by
2. `play_uri()` with the selected favourite from the list above.

There's a general purpose example that might (or might not) be helpful at: https://github.com/avantrec/soco-cli/blob/49bc7df15f1eaca2a475a9e158574b324f417443/soco_cli/action_processor.py#L638
