### ISSUE TITLE
How to "Select Music Source" to "Line-In" "Computer: Office (L)"

### ISSUE THREAD

**Issue by GitHubKitten** [SoCo/SoCo#929]
Hi,

I would like to set the "music source" to "Line-In" and the "Line-In" source, using SoCo.

So, I am wondering if it is possible. For example to "Select Music Source" to "Line-In" "Computer: Office (L)"?

Details of the "problem". In the Windows Sonos S1 Controller program, I often manually have to first "Select Music Source" and double-click "Line-In". Then, I also have to manually double-click on "Computer: (Office (L)" as well.

I would like to automate this. 

To help explain my S1 system configuration: Two paired Play 5 speakers. The left speaker audio input cable is from Computer (PC). One Playbar. Grouped with the "Office" pair.

Here is the list of the 3 speakers in my S1 system:

Associated Product: 192.168.1.241
---------------------------------
Play:5: Office (L)
Sonos OS: S1
IP Address: 192.168.1.241
---------------------------------
Play:5: Office (R)
Sonos OS: S1
IP Address: 192.168.1.140
---------------------------------
Playbar: Office Playbar
Sonos OS: S1
IP Address: 192.168.1.146
---------------------------------

**Comment by pwt** [comment]
Yes, use: `SoCo.switch_to_line_in()`. See docs at: http://docs.python-soco.com/en/latest/api/soco.core.html.

**Comment by GitHubKitten** [comment]
> SoCo.switch_to_line_in()

C:\Users\Anders>sonos SoCo.switch_to_line_in()
Error: At least 2 parameters required in action sequence '['SoCo.switch_to_line_in()']'; did you supply a speaker name?

**Comment by pwt** [comment]
> > SoCo.switch_to_line_in()
> 
> C:\Users\Anders>sonos SoCo.switch_to_line_in() Error: At least 2 parameters required in action sequence '['SoCo.switch_to_line_in()']'; did you supply a speaker name?

You need to create a SoCo object, and then call the method on it, e.g.:

```
from soco import SoCo
office_l = SoCo("192.168.1.241")
office_l.switch_to_line_in()
```

**Comment by GitHubKitten** [comment]
Thanks pwt. Where do I put this SoCo object? in the top of the script?

**Comment by pwt** [comment]
Oh, wait. If you're using SoCo-CLI, you just use:
```
C:\Users\Anders> sonos Office line_in on
```
from the command line. See documentation for `line_in` at: https://github.com/avantrec/soco-cli#playback-control
