### ISSUE TITLE
event.variables.get('transport_state') returns PLAYING even when music is paused

### ISSUE THREAD

**Issue by mdstricklin** [SoCo/SoCo#944]
As title states. I have a Connect in a group with several other players with another room as primary. If I go from playing to paused, PLAYING is still reported.

**Comment by pwt** [comment]
That's just reflecting the state held in the Sonos system.

When a player isn't the coordinator, you need to interrogate the coordinator for the correct playback state: `speaker.group.coordinator`.

**Comment by mdstricklin** [comment]
> That's just reflecting the state held in the Sonos system.
> 
> When a player isn't the coordinator, you need to interrogate the coordinator for the correct playback state: `speaker.group.coordinator`.

Oh! Thank you for the prompt reply. Sorry for opening the issue. I'm still very much in a learning phase.
