### ISSUE TITLE
Read the Docs out of date due to build failure

### ISSUE THREAD

**Issue by DaAwesomeP** [SoCo/SoCo#954]
Hello,

I noticed that Read the Docs did not have the latest version shown. There appears to be a build failure: https://readthedocs.org/projects/soco/builds/22855890/

I'm not certain if this will require a v0.30.1 release to get it to run a tagged build again.

**Comment by pwt** [comment]
Thanks for spotting this. Documentation builds appear to have been failing for about 9 months, but my understanding of the SoCo docs build process is rudimentary so I'm not sure why.

I've fixed it by following the breadcrumb trail of error messages. Master is now updated, and I've also released v0.30.1 off the `fixes` branch to catch up the documentation for `stable`.
