### ISSUE TITLE
[Question] - high level event interface description

### ISSUE THREAD

**Issue by q6276270** [SoCo/SoCo#957]
Hi there,
i was wondering how the event queues in soco work on a high level. I was wondering whether the feedback actually becomes bidirectional, i.e. is there a way to make sonos actually send http requests to the soco service (when an event occurs) or whether http requests are send periodically by soco only to update the status.

It seems to be a bit too much effort to understand the code for answering such a simple question but I was curious anyway.
Thanks a lot for your help.

**Comment by pwt** [comment]
SoCo-based applications can subscribe to various event streams emitted by speakers. Speakers will then make HTTP callbacks to the SoCo application when events occur, and without the application needing to poll. Events are used extensively within Sonos's own software ecosystem, so they're well supported.

http://docs.python-soco.com/en/v0.30.1/advanced/events.html

**Comment by q6276270** [comment]
Thank you for the answer,
I've already read and skimmed a part of the documentation but could not find a definitive response.

Now if I want to know how to do this I can just read the code myself.

Thanks again.
