### ISSUE TITLE
SoCo throws UPnP Error 701 on specific station

### ISSUE THREAD

**Issue by jgkamat** [SoCo/SoCo#958]
Hello, and thanks for taking a look. I can play most radio stations normally like this: 

```
my_zone = SoCo('192.168.1.190')
my_zone.play_uri('x-rincon-mp3radio://dancewave.online/dance.mp3')
```
However, the gensokyo radio station causes a UpNP Error:

```
>>> my_zone.play_uri('x-rincon-mp3radio://stream.gensokyoradio.net/3')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jay/Code/SoCo/soco/core.py", line 148, in inner_function
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/Code/SoCo/soco/core.py", line 838, in play_uri
    return self.play()
           ^^^^^^^^^^^
  File "/home/jay/Code/SoCo/soco/core.py", line 148, in inner_function
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/Code/SoCo/soco/core.py", line 753, in play
    self.avTransport.Play([("InstanceID", 0), ("Speed", 1)])
  File "/home/jay/Code/SoCo/soco/services.py", line 207, in _dispatcher
    return self.send_command(action, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/Code/SoCo/soco/services.py", line 515, in send_command
    self.handle_upnp_error(response.text)
  File "/home/jay/Code/SoCo/soco/services.py", line 571, in handle_upnp_error
    raise SoCoUPnPException(
soco.exceptions.SoCoUPnPException: UPnP Error 701 received: Transition not available from 192.168.1.190
```

I can play this station with this same stream URL using this android app: https://github.com/watea/RadioUpnp - so I suspect that some configuration is differing between the two, which is preventing the stream from starting. I was trying to reconstruct their metadata here - but it seems a lot more complex than I'm hoping (to reconstruct it manually): https://github.com/watea/RadioUpnp/blob/0cee62ba3be75f295a0e4046ac5f485d6aa948fe/app/src/main/java/com/watea/radio_upnp/adapter/UpnpPlayerAdapter.java#L446

I think this is different from previous issues (eg: https://github.com/SoCo/SoCo/issues/454, https://github.com/SoCo/SoCo/issues/761) because I'm not doing anything fancy with play/pause or snapshots here - I'm just requesting a radio to play. 

I'm testing on IKEA SYMFONISK speakers.

**Comment by jgkamat** [comment]
I'm unable to reliably play from this url on the official app, so I'm guessing this is a problem somewhere in the device, not in the library. Sorry for the noise.

**Comment by pwt** [comment]
> I'm unable to reliably play from this url on the official app, so I'm guessing this is a problem somewhere in the device, not in the library. Sorry for the noise.

That was my guess, but I haven't had a time to test it. Thanks for confirming.
