### ISSUE TITLE
Adding Sharelinks to the queue fails on Sonos S2 with UPnP 800 errors

### ISSUE THREAD

**Issue by awilson133** [SoCo/SoCo#969]
Hi there,

This is a duplicate of https://github.com/home-assistant/core/issues/133052, but I was able to replicate the same issue in SoCo. Trying to play anything to any of my Sonos speakers generates the following error:

```
Traceback (most recent call last):
  File "/var/home/andrew/socoscript.py", line 56, in <module>
    add_from_service(track_id, service, device, True)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/andrew/socoscript.py", line 53, in add_from_service
    device.add_to_queue(didl)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/var/home/andrew/soco/lib64/python3.13/site-packages/soco/core.py", line 146, in inner_function
    return function(self, *args, **kwargs)
  File "/var/home/andrew/soco/lib64/python3.13/site-packages/soco/core.py", line 2277, in add_to_queue
    response = self.avTransport.AddURIToQueue(
        [
    ...<6 lines>...
        **kwargs,
    )
  File "/var/home/andrew/soco/lib64/python3.13/site-packages/soco/services.py", line 207, in _dispatcher
    return self.send_command(action, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/andrew/soco/lib64/python3.13/site-packages/soco/services.py", line 515, in send_command
    self.handle_upnp_error(response.text)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/var/home/andrew/soco/lib64/python3.13/site-packages/soco/services.py", line 571, in handle_upnp_error
    raise SoCoUPnPException(
    ...<6 lines>...
    )
soco.exceptions.SoCoUPnPException: UPnP Error 800 received:  from X.X.X.X
```

I have reset my Sonos system entirely, removed and re-added all Spotify accounts from Sonos, and the same thing happens. It works properly if any local, web-based, or stream from a non-Spotify service is started.

**Comment by awilson133** [comment]
The script I am attempting to run when I get this error is: https://gist.github.com/lawrenceakka/2d21dca590b4fa7e3af2

**Comment by pwt** [comment]
Some time ago (not sure when, but it'll be in the issue history!), Sonos prevented simple addition of URIs to queue for anything requiring authentication, including most music services:
https://docs.python-soco.com/en/latest/faq.html#why-can-t-i-play-a-uri-from-music-service-x-with-the-play-uri-method

A couple of years ago, nascent support was re-added for music services, supporting the required auth.: https://docs.python-soco.com/en/stable/api/soco.music_services.music_service.html#module-soco.music_services.music_service

There's also a simpler mechanism that allows ShareLinks from selected music services to be added to the Sonos queue, using the ShareLink plugin:

```python
from soco.plugins.sharelink import ShareLinkPlugin
share_link = ShareLinkPlugin(speaker)  # speaker is a SoCo object
queue_position = share_link.add_share_link_to_queue(uri, position)
```
The `uri` can take the form of (e.g.):
- `https://open.spotify.com/track/6cpcorzV5cmVjBsuAXq4wD`
- `spotify:album:6wiUBliPe76YAVpNEdidpY`
- `https://tidal.com/browse/album/157273956`
- `https://www.deezer.com/en/playlist/5390258182`
- `https://music.apple.com/dk/album/black-velvet/217502930?i=217503142`

**Comment by awilson133** [comment]
This issue is not resolved, it still occurs when the URI is formatted like the above:

```
>>> from soco import SoCo
>>> device = SoCo('192.168.3.20')
>>> from soco.plugins.sharelink import ShareLinkPlugin
>>> share_link = ShareLinkPlugin(device)
>>> share_link.add_share_link_to_queue('https://open.spotify.com/track/5m3rVRNkTv5EQnPuF293we?si=cd2c86feb7924e77')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\awilson\Downloads\sonos\Lib\site-packages\soco\plugins\sharelink.py", line 279, in add_share_link_to_queue
    raise fault
  File "C:\Users\awilson\Downloads\sonos\Lib\site-packages\soco\plugins\sharelink.py", line 261, in add_share_link_to_queue
    response = self.soco.avTransport.AddURIToQueue(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\awilson\Downloads\sonos\Lib\site-packages\soco\services.py", line 207, in _dispatcher
    return self.send_command(action, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\awilson\Downloads\sonos\Lib\site-packages\soco\services.py", line 515, in send_command
    self.handle_upnp_error(response.text)
  File "C:\Users\awilson\Downloads\sonos\Lib\site-packages\soco\services.py", line 571, in handle_upnp_error
    raise SoCoUPnPException(
soco.exceptions.SoCoUPnPException: UPnP Error 800 received:  from 192.168.3.20
```
I get the same result using the exact share link from your example too. Of note, playing Spotify from Sonos works fine, and SoCo can do everything else (play, pause, volume, speaker info) on this speaker with no issue.

I have also reset everything in Sonos (removed all services, restarted speakers multiple times, re-added just the one Spotify account) and it still occurs. This is an active issue on the Home Assistant Github with multiple reports similar to mine with this issue happening suddenly with no configuration changes, and it appears to be originating with SoCo and not just HA. I appreciate your help and am happy to test or troubleshoot anything to assist!

**Comment by pwt** [comment]
Right, adding sharelinks to the queue still works on Sonos S1, but not on S2, so Sonos has recently changed something in S2.

I've tested Spotify and Apple Music, and both fail.

It'll require investigation to find out if this is fixable, but I'm probably not the person to do this.

**Comment by monstergubl** [comment]
same issue since yesterday and tried all above no chance to get a single track or playlist played on one speaker (tryd readding on android and ios spotify )

**Comment by awilson133** [comment]
@monstergubl @pwt this suddenly started working for me after Sonos pushed an update. Assuming this was something they broke on their end and will be fixed as people get the update.
