### ISSUE TITLE
Text to speech attempt and metadata

### ISSUE THREAD

**Issue by rodhall** [SoCo/SoCo#99]
All - similar to aProgrammer, I think I am running into metadata problems on a little project I have been working on using SoCo.  google.translate has an API that will return a TTS conversion as an MP3 for anything you throw at it.  My initial little test program is as follows:

import requests
from soco import SoCo
import sys
import os
lr_sonos = SoCo('192.168.0.148')
tts_string = input('Enter something to say:  ')
speech_uri = 'http://translate.google.com/translate_tts?q='+tts_string
lr_sonos.play_uri(uri=speech_uri,meta='')
print('Done!')

However, this isn't working and it seems like the problems are mainly associated with metadata (though I am not completely sure).  Error return is as follows:

Enter something to say:  hello
Traceback (most recent call last):
  File "/Users/rodhall/Dropbox/Python/speaksonos.py", line 9, in <module>
    lr_sonos.play_uri(uri=speech_uri,meta='')
  File "/Users/rodhall/Dropbox/Python/soco/core.py", line 253, in play_uri
    ('CurrentURIMetaData', meta)
  File "/Users/rodhall/Dropbox/Python/soco/services.py", line 153, in _dispatcher
    return self.send_command(action, args)
  File "/Users/rodhall/Dropbox/Python/soco/services.py", line 316, in send_command
    self.handle_upnp_error(response.text)
  File "/Users/rodhall/Dropbox/Python/soco/services.py", line 377, in handle_upnp_error
    error_xml=xml_error
soco.exceptions.SoCoUPnPException: UPnP Error 714 received: Illegal MIME-Type from 192.168.0.148

I just think it would be super cool to get my Sonos to talk when various things happen (cameras detect motion, doorbell, etc etc.) however I am a newbie to SoCo and need some advice.

**Comment by kylewill** [comment]
I'm working on a similar project and trying @robwebset code. I made some updates for Python 3 but I get an error from the Sonos controller "Unable to play station Speech - station not found". 

Anyone have this working?

**Comment by robwebset** [comment]
There was a change in the google link a while ago:

trans_URI = "x-rincon-mp3radio://translate.google.com/translate_tts?tl=%s&q=%s&client=t" % (glang, msg)

New location of full file:

https://github.com/robwebset/script.sonos/blob/master/resources/lib/speech.py

Rob

**Comment by leanto** [comment]
I just tried this and, as far as I can tell, the Google API isn't working anymore.

**Comment by leanto** [comment]
OK, I actually got it to work. I needed to convert https://github.com/Boudewijn26/gTTS-token to python3 (no actual changes required) and add the following:

```python
    def __init__(self, device):
        # The device that the speech will be sent to                                                                    
        self.device = device
        self.token = gtts_token.Token()

    def say(self, message):
        ...
        msg = cgi.escape(message)
        tk = self.token.calculate_token(msg)
        trans_URI = "x-rincon-mp3radio://translate.google.com/translate_tts?tl=%s&q=%s&tk=%s&client=tw-ob&textlen=%d" %\
 ('en', msg, tk, len(msg))
        self.device.play_uri(trans_URI, title="Speech")
```

This is not elegant by any means, but it works.

**Comment by jeffehobbs** [comment]
For those of you still interested in this, AWS's "Polly" API (based on the Ivona API, which they purchased the company behind) is a wonderful service that takes text and returns an mp3, which works great.

**Comment by KennethNielsen** [comment]
Hi all. This is really old by now and is really more of a discussion about what you can do with SoCo anyway. If you think there is still something we should look at feel free to reopen.

In any case. An updated version of the code posted by @robwebset here: https://github.com/SoCo/SoCo/issues/99#issuecomment-55504774 would make fore a really neat SoCo example. If anyone feels up to making a PR out of it, I think that would be a great addition, as it is definitely something many are fiddling with.

**Comment by ghcs27** [comment]
Here's my version of the script (updated for new version, restructured and commented):
```python
# -*- coding: utf-8 -*-
try:
    from html import escape
except ImportError:
    from cgi import escape

try:
    from queue import Empty
except ImportError:
    from Queue import Empty

import time

# Load the Soco classes
from soco.snapshot import Snapshot
from soco.events import event_listener, _subscriptions


#########################################################################
# Sonos Speech class to get a device to talk
#########################################################################
class Speech(object):

    def __init__(self, device, translate_uri):
        """Create a text-to-speech agent.

        Args:
            device (SoCo): The device that the speech will be sent to
            translate_uri (str): The uri to get the speech from. This should
                be a format string, containing ``{message}`` for the place
                the message should be inserted in, and ``{<argname>}`` for
                keyword args that should be passed to `say()`. Example:
                ``x-rincon-mp3radio://translate.google.com/translate_tts
                ?tl={language}&q={message}&client=t``
        """
        self.device = device
        self.translate_uri = translate_uri

    def text_to_speech_uri(self, message, uri_args):
        """Convert the message to a playable speech uri.

        Args:
            message (str): The message to be spoken.
            uri_args (dict): Passed keyword arguments.

        This may be overridden to e.g. format the message or retrieve an
        api key.
        """
        escaped_message = escape(message)
        return self.translate_uri.format(message=escaped_message, **uri_args)

    def play_uri_and_reset(self, uri, max_duration=20, title="Speech"):
        """Play an uri and reset the player to its previous state afterwards.

        Args:
            uri (str): The uri to play.
            max_duration (int): The maximum time to wait for the speech to end.
            title (str): The title to show in the controller.
        """
        # Need to subscribe to transport events, this is so that we know
        # when a given track has finished, and so we can stop it, if
        # we do not stop it, then it will repeat the text for a second time
        with self.device.avTransport.subscribe() as sub, Snapshot(self.device):
            self.device.play_uri(uri, title=title)
            end_time = time.time() + max_duration
            while time.time() < end_time:
                try:
                    event = sub.events.get(timeout=end_time - time.time())
                    # Check to see if there is a message saying that it is
                    # waiting to restart the audio stream.  This happens
                    # because it is being treated like a radio stream, so Sonos
                    # end of the mp3 file playing is reached that there has
                    # been a connection error and needs to reconnect. If left
                    # to itself it would play the mp3 file again
                    restart_pending = event.variables.get('restart_pending',
                                                          None)
                    if restart_pending == '1':
                        break
                except Empty:
                    pass
            # Stop the stream playing
            self.device.stop()
            # Unsubscribe and restore snapshot

        # Only stop the listener if no running subscriptions
        # Remove this when the event listener is stopped automatically
        if not _subscriptions:
            event_listener.stop()

    def say(self, message, max_duration=20, title="Speech", **kwargs):
        """Play an announcement on the speaker.

        The player will be reset to its previous state afterwards.

        Args:
            message (str): The message to be spoken.
            max_duration (int): The maximum time to wait for the speech to end.
            title (str): The title to show in the controller.
            **kwargs: Arguments to pass to the translation service
        """
        speech_uri = self.text_to_speech_uri(message, kwargs)
        self.play_uri_and_reset(speech_uri, max_duration, title)
```

**Comment by KennethNielsen** [comment]
@ghcs27 Looks good. As I said I think it would make a good example. Can I get you to make a PR out of it. #588 is just merged ;)
